apiVersion: v1
kind: Service
metadata:
  name: ai-security-service
  namespace: ai-services
  labels:
    app: ai-security-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-security-service
  ports:
  - name: http
    port: 8263
    targetPort: 8263
    protocol: TCP
