apiVersion: v1
kind: Secret
metadata:
  name: status-broadcast-service-secrets
  namespace: transaction-orchestration
  labels:
    app: status-broadcast-service
    team: team-b-transaction
type: Opaque
stringData:
  database-username: "status_broadcast_user"
  database-password: "CHANGE_ME_PROD_PASSWORD"
