package com.gogidix.sales.crm.domain.port.in;

import com.gogidix.sales.crm.domain.model.Customer;
import com.gogidix.sales.crm.domain.port.in.CustomerCommand;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class CustomerCommand_CreateCustomerCommandTest {

        @Test
    void testSettersAndGetters() {
        CustomerCommand.CreateCustomerCommand dto = new CustomerCommand.CreateCustomerCommand();
        dto.setTenantId("val-tenantId");
        dto.setCreatedBy("val-createdBy");
        dto.setCompanyName("val-companyName");
        dto.setIndustry("val-industry");
        dto.setLeadSource("val-leadSource");
        dto.setWebsite("val-website");
        dto.setDescription("val-description");
        dto.setEmployeeCount(99);
        dto.setOwnerId("val-ownerId");
        dto.setOwnerName("val-ownerName");
        dto.setTerritory("val-territory");
        dto.setBillingAddressStreet("val-billingAddressStreet");
        dto.setBillingAddressCity("val-billingAddressCity");
        dto.setBillingAddressState("val-billingAddressState");
        dto.setBillingAddressPostalCode("val-billingAddressPostalCode");
        dto.setBillingAddressCountry("val-billingAddressCountry");
        dto.setShippingAddressStreet("val-shippingAddressStreet");
        dto.setShippingAddressCity("val-shippingAddressCity");
        dto.setShippingAddressState("val-shippingAddressState");
        dto.setShippingAddressPostalCode("val-shippingAddressPostalCode");
        dto.setShippingAddressCountry("val-shippingAddressCountry");
        dto.setPhoneNumber("val-phoneNumber");
        dto.setEmail("val-email");
        dto.setAccountNumber("val-accountNumber");
        dto.setParentAccountId("val-parentAccountId");
        dto.setTaxId("val-taxId");
        dto.setPaymentTerms("val-paymentTerms");
        dto.setCurrency("val-currency");
        dto.setNotes("val-notes");
        assertEquals("val-tenantId", dto.getTenantId());
        assertEquals("val-createdBy", dto.getCreatedBy());
        assertEquals("val-companyName", dto.getCompanyName());
        assertEquals("val-industry", dto.getIndustry());
        assertEquals("val-leadSource", dto.getLeadSource());
        assertEquals("val-website", dto.getWebsite());
        assertEquals("val-description", dto.getDescription());
        assertEquals(99, dto.getEmployeeCount());
        assertEquals("val-ownerId", dto.getOwnerId());
        assertEquals("val-ownerName", dto.getOwnerName());
        assertEquals("val-territory", dto.getTerritory());
        assertEquals("val-billingAddressStreet", dto.getBillingAddressStreet());
        assertEquals("val-billingAddressCity", dto.getBillingAddressCity());
        assertEquals("val-billingAddressState", dto.getBillingAddressState());
        assertEquals("val-billingAddressPostalCode", dto.getBillingAddressPostalCode());
        assertEquals("val-billingAddressCountry", dto.getBillingAddressCountry());
        assertEquals("val-shippingAddressStreet", dto.getShippingAddressStreet());
        assertEquals("val-shippingAddressCity", dto.getShippingAddressCity());
        assertEquals("val-shippingAddressState", dto.getShippingAddressState());
        assertEquals("val-shippingAddressPostalCode", dto.getShippingAddressPostalCode());
        assertEquals("val-shippingAddressCountry", dto.getShippingAddressCountry());
        assertEquals("val-phoneNumber", dto.getPhoneNumber());
        assertEquals("val-email", dto.getEmail());
        assertEquals("val-accountNumber", dto.getAccountNumber());
        assertEquals("val-parentAccountId", dto.getParentAccountId());
        assertEquals("val-taxId", dto.getTaxId());
        assertEquals("val-paymentTerms", dto.getPaymentTerms());
        assertEquals("val-currency", dto.getCurrency());
        assertEquals("val-notes", dto.getNotes());
    }

    @Test
    void testEqualsAndHashCode() {
        CustomerCommand.CreateCustomerCommand dto1 = new CustomerCommand.CreateCustomerCommand();
        CustomerCommand.CreateCustomerCommand dto2 = new CustomerCommand.CreateCustomerCommand();
        dto1.setTenantId("test");
        dto1.setCreatedBy("test");
        dto1.setCompanyName("test");
        dto1.setIndustry("test");
        dto1.setSegment(Customer.CustomerSegment.ENTERPRISE);
        dto1.setLifecycleStage(Customer.CustomerLifecycleStage.LEAD);
        dto1.setLeadSource("test");
        dto1.setWebsite("test");
        dto1.setDescription("test");
        dto1.setEmployeeCount(42);
        dto1.setAnnualRevenue(null);
        dto1.setOwnerId("test");
        dto1.setOwnerName("test");
        dto1.setTerritory("test");
        dto1.setBillingAddressStreet("test");
        dto1.setBillingAddressCity("test");
        dto1.setBillingAddressState("test");
        dto1.setBillingAddressPostalCode("test");
        dto1.setBillingAddressCountry("test");
        dto1.setShippingAddressStreet("test");
        dto1.setShippingAddressCity("test");
        dto1.setShippingAddressState("test");
        dto1.setShippingAddressPostalCode("test");
        dto1.setShippingAddressCountry("test");
        dto1.setPhoneNumber("test");
        dto1.setEmail("test");
        dto1.setAccountNumber("test");
        dto1.setAccountType(Customer.AccountType.STRATEGIC);
        dto1.setParentAccountId("test");
        dto1.setTaxId("test");
        dto1.setPaymentTerms("test");
        dto1.setCurrency("test");
        dto1.setCreditLimit(null);
        dto1.setTags(Collections.emptyList());
        dto1.setNotes("test");
        dto2.setTenantId("test");
        dto2.setCreatedBy("test");
        dto2.setCompanyName("test");
        dto2.setIndustry("test");
        dto2.setSegment(Customer.CustomerSegment.ENTERPRISE);
        dto2.setLifecycleStage(Customer.CustomerLifecycleStage.LEAD);
        dto2.setLeadSource("test");
        dto2.setWebsite("test");
        dto2.setDescription("test");
        dto2.setEmployeeCount(42);
        dto2.setAnnualRevenue(null);
        dto2.setOwnerId("test");
        dto2.setOwnerName("test");
        dto2.setTerritory("test");
        dto2.setBillingAddressStreet("test");
        dto2.setBillingAddressCity("test");
        dto2.setBillingAddressState("test");
        dto2.setBillingAddressPostalCode("test");
        dto2.setBillingAddressCountry("test");
        dto2.setShippingAddressStreet("test");
        dto2.setShippingAddressCity("test");
        dto2.setShippingAddressState("test");
        dto2.setShippingAddressPostalCode("test");
        dto2.setShippingAddressCountry("test");
        dto2.setPhoneNumber("test");
        dto2.setEmail("test");
        dto2.setAccountNumber("test");
        dto2.setAccountType(Customer.AccountType.STRATEGIC);
        dto2.setParentAccountId("test");
        dto2.setTaxId("test");
        dto2.setPaymentTerms("test");
        dto2.setCurrency("test");
        dto2.setCreditLimit(null);
        dto2.setTags(Collections.emptyList());
        dto2.setNotes("test");
        assertEquals(dto1, dto2);
        assertEquals(dto1.hashCode(), dto2.hashCode());
        dto2.setTenantId(null);
        assertNotEquals(dto1, dto2);
    }

    @Test
    void testToString() {
        CustomerCommand.CreateCustomerCommand dto = new CustomerCommand.CreateCustomerCommand();
        dto.setTenantId("test");
        dto.setCreatedBy("test");
        dto.setCompanyName("test");
        dto.setIndustry("test");
        dto.setSegment(Customer.CustomerSegment.ENTERPRISE);
        dto.setLifecycleStage(Customer.CustomerLifecycleStage.LEAD);
        dto.setLeadSource("test");
        dto.setWebsite("test");
        dto.setDescription("test");
        dto.setEmployeeCount(42);
        dto.setAnnualRevenue(null);
        dto.setOwnerId("test");
        dto.setOwnerName("test");
        dto.setTerritory("test");
        dto.setBillingAddressStreet("test");
        dto.setBillingAddressCity("test");
        dto.setBillingAddressState("test");
        dto.setBillingAddressPostalCode("test");
        dto.setBillingAddressCountry("test");
        dto.setShippingAddressStreet("test");
        dto.setShippingAddressCity("test");
        dto.setShippingAddressState("test");
        dto.setShippingAddressPostalCode("test");
        dto.setShippingAddressCountry("test");
        dto.setPhoneNumber("test");
        dto.setEmail("test");
        dto.setAccountNumber("test");
        dto.setAccountType(Customer.AccountType.STRATEGIC);
        dto.setParentAccountId("test");
        dto.setTaxId("test");
        dto.setPaymentTerms("test");
        dto.setCurrency("test");
        dto.setCreditLimit(null);
        dto.setTags(Collections.emptyList());
        dto.setNotes("test");
        String str = dto.toString();
        assertNotNull(str);
        assertTrue(str.length() > 0);
    }

    @Test
    void testEqualsNullAndOtherType() {
        CustomerCommand.CreateCustomerCommand dto = new CustomerCommand.CreateCustomerCommand();
        dto.setTenantId("test");
        dto.setCreatedBy("test");
        dto.setCompanyName("test");
        dto.setIndustry("test");
        dto.setSegment(Customer.CustomerSegment.ENTERPRISE);
        dto.setLifecycleStage(Customer.CustomerLifecycleStage.LEAD);
        dto.setLeadSource("test");
        dto.setWebsite("test");
        dto.setDescription("test");
        dto.setEmployeeCount(42);
        dto.setAnnualRevenue(null);
        dto.setOwnerId("test");
        dto.setOwnerName("test");
        dto.setTerritory("test");
        dto.setBillingAddressStreet("test");
        dto.setBillingAddressCity("test");
        dto.setBillingAddressState("test");
        dto.setBillingAddressPostalCode("test");
        dto.setBillingAddressCountry("test");
        dto.setShippingAddressStreet("test");
        dto.setShippingAddressCity("test");
        dto.setShippingAddressState("test");
        dto.setShippingAddressPostalCode("test");
        dto.setShippingAddressCountry("test");
        dto.setPhoneNumber("test");
        dto.setEmail("test");
        dto.setAccountNumber("test");
        dto.setAccountType(Customer.AccountType.STRATEGIC);
        dto.setParentAccountId("test");
        dto.setTaxId("test");
        dto.setPaymentTerms("test");
        dto.setCurrency("test");
        dto.setCreditLimit(null);
        dto.setTags(Collections.emptyList());
        dto.setNotes("test");
        assertNotEquals(null, dto);
        assertNotEquals("string", dto);
        assertEquals(dto, dto);
    }

}