spring:
  application:
    name: ocean-shipping-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_oceanshipping
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        oceanshippingEvents-out-0:
          destination: oceanshipping-events
          content-type: application/json
server:
  port: 8074
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.oceanshipping: DEBUG
