spring:
  application:
    name: loyalty-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_loyalty
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        loyaltyEvents-out-0:
          destination: loyalty-events
          content-type: application/json
server:
  port: 8079
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.loyalty: DEBUG
