server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: budget-management-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:budget-management-service_db}
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
