spring:
  application:
    name: ai-feature-store-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/feature_store
  redis:
    host: localhost
    port: 6379

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.gogidix: INFO
