apiVersion: v1
kind: Secret
metadata:
  name: voice-recognition-service-secrets
  namespace: ai-services
  labels:
    app: voice-recognition-service
    team: team-f-ai-services
type: Opaque
stringData:
  mongodb-user: "voice-recognition-service_user"
  mongodb-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
