apiVersion: v1
kind: Service
metadata:
  name: voice-recognition-service
  namespace: ai-services
  labels:
    app: voice-recognition-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: voice-recognition-service
  ports:
  - name: http
    port: 8238
    targetPort: 8238
    protocol: TCP
