spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_analytics
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        analyticsEvents-out-0:
          destination: analytics-events
          content-type: application/json
server:
  port: 8067
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.analytics: DEBUG
