package com.gogidix.hr.globalpolicymanagement.domain.enums;

/**
 * PolicyType enum for HR policies
 */
public enum PolicyType {
    EMPLOYEE_CONDUCT,
    ANTI_HARASSMENT,
    ANTI_DISCRIMINATION,
    CODE_OF_ETHICS,
    DATA_PROTECTION,
    HEALTH_AND_SAFETY,
    LEAVE_POLICY,
    WORK_FROM_HOME,
    ATTENDANCE_POLICY,
    PERFORMANCE_MANAGEMENT,
    RECRUITMENT_POLICY,
    COMPENSATION_POLICY,
    BENEFITS_POLICY,
    DISCIPLINARY_POLICY,
    GRIEVANCE_POLICY,
    TERMINATION_POLICY,
    PRIVACY_POLICY,
    SOCIAL_MEDIA_POLICY,
    TRAVEL_POLICY,
    EXPENSE_POLICY,
    TRAINING_POLICY,
    DIVERSITY_AND_INCLUSION,
    WHISTLE_BLOWER_POLICY,
    CONFLICT_OF_INTEREST,
    DRUG_AND_ALCOHOL_POLICY,
    SECURITY_POLICY,
    ACCESS_CONTROL_POLICY,
    RECORD_RETENTION_POLICY
}
