export enum RuleType {
  AMOUNT_THRESHOLD = 'AMOUNT_THRESHOLD',
  VENDOR_CATEGORY = 'VENDOR_CATEGORY',
  PAYMENT_SCHEDULE = 'PAYMENT_SCHEDULE',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  DUPLICATE_CHECK = 'DUPLICATE_CHECK',
  AUTOMATION_CONDITION = 'AUTOMATION_CONDITION',
}
