-- ============================================================================
-- Global Marketing Dashboard Service - Supabase Database Setup
-- ============================================================================
-- Project: jbtozjinbrfibzwxbnpl
-- Date: 2024-03-27
-- ============================================================================

-- Enable UUID extension (if not enabled by default)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. Dashboard Metrics Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS dashboard_metrics (
    -- Primary Key
    id BIGSERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Tenant Information (for multi-tenancy)
    tenant_id VARCHAR(255) NOT NULL,

    -- Metric Data
    name VARCHAR(255) NOT NULL,
    value NUMERIC(20, 4) NOT NULL,
    change NUMERIC(20, 4),
    change_percent NUMERIC(10, 4),
    category VARCHAR(100) NOT NULL,

    -- Timestamp
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Period
    period VARCHAR(50),

    -- Unit
    unit VARCHAR(50),

    -- Trend
    trend VARCHAR(20) DEFAULT 'STABLE',

    -- JSONB columns for flexible data
    dimensions JSONB,
    metadata JSONB,

    -- Audit Fields
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_tenant ON dashboard_metrics(tenant_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_category ON dashboard_metrics(category);
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_timestamp ON dashboard_metrics(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_tenant_category ON dashboard_metrics(tenant_id, category);

-- ============================================================================
-- 2. Country Stats Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS country_stats (
    -- Primary Key
    id BIGSERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Tenant Information
    tenant_id VARCHAR(255) NOT NULL,

    -- Country Information
    country_code VARCHAR(3) NOT NULL,
    country_name VARCHAR(255) NOT NULL,
    region VARCHAR(100),

    -- Metrics (JSONB for flexibility)
    metrics JSONB,

    -- Time Tracking
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    period VARCHAR(50),

    -- Campaign Data
    active_campaigns INTEGER DEFAULT 0,
    total_budget NUMERIC(20, 2),
    spent_budget NUMERIC(20, 2),

    -- Conversion & Leads
    leads_generated INTEGER DEFAULT 0,
    conversion_rate NUMERIC(10, 4),

    -- Team
    team_size INTEGER,

    -- Metadata
    metadata JSONB,

    -- Audit Fields
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_country_stats_tenant ON country_stats(tenant_id);
CREATE INDEX IF NOT EXISTS idx_country_stats_country ON country_stats(country_code);
CREATE INDEX IF NOT EXISTS idx_country_stats_region ON country_stats(region);
CREATE INDEX IF NOT EXISTS idx_country_stats_last_updated ON country_stats(last_updated DESC);

-- ============================================================================
-- 3. Global Alerts Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS global_alerts (
    -- Primary Key
    id BIGSERIAL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- Tenant Information
    tenant_id VARCHAR(255) NOT NULL,

    -- Alert Data
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    message TEXT NOT NULL,
    title VARCHAR(255),
    affected_country VARCHAR(3),

    -- Status Tracking
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by VARCHAR(255),
    is_acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by VARCHAR(255),
    acknowledged_at TIMESTAMP WITH TIME ZONE,

    -- Expiry
    expires_at TIMESTAMP WITH TIME ZONE,

    -- Metadata
    data JSONB,

    -- Audit Fields
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_global_alerts_tenant ON global_alerts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_global_alerts_type ON global_alerts(type);
CREATE INDEX IF NOT EXISTS idx_global_alerts_severity ON global_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_global_alerts_resolved_at ON global_alerts(resolved_at);
CREATE INDEX IF NOT EXISTS idx_global_alerts_is_acknowledged ON global_alerts(is_acknowledged);
CREATE INDEX IF NOT EXISTS idx_global_alerts_affected_country ON global_alerts(affected_country);
CREATE INDEX IF NOT EXISTS idx_global_alerts_created_at ON global_alerts(created_at DESC);

-- ============================================================================
-- Row Level Security (RLS) - Enable Tenant Isolation
-- ============================================================================

-- Create a tenant_id function to enforce row-level security
CREATE OR REPLACE FUNCTION get_tenant_id() RETURNS TRIGGER AS $$
BEGIN
    RETURN COALESCE(NULLIF(current_setting(), 'tenant_id'), 'default');
END;
$$ LANGUAGE plpgsql;

-- Apply RLS to tables
ALTER TABLE dashboard_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY dashboard_metrics_tenant_policy ON dashboard_metrics
    USING (get_tenant_id())
    FOR SELECT
    WITH CHECK (tenant_id = get_tenant_id());

ALTER TABLE country_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY country_stats_tenant_policy ON country_stats
    USING (get_tenant_id())
    FOR SELECT
    WITH CHECK (tenant_id = get_tenant_id());

ALTER TABLE global_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY global_alerts_tenant_policy ON global_alerts
    USING (get_tenant_id())
    FOR SELECT
    WITH CHECK (tenant_id = get_tenant_id());

-- ============================================================================
-- Initial Data (Optional - Sample Data)
-- ============================================================================

-- Insert sample metrics for testing
INSERT INTO dashboard_metrics (tenant_id, name, value, category, period, trend)
VALUES
    ('default', 'Total Revenue', 125000.50, 'REVENUE', 'DAILY', 'UP'),
    ('default', 'Active Users', 15234, 'USERS', 'DAILY', 'UP'),
    ('default', 'Conversion Rate', 3.2, 'PERFORMANCE', 'DAILY', 'STABLE');

-- Insert sample country stats
INSERT INTO country_stats (tenant_id, country_code, country_name, region, last_updated, period)
VALUES
    ('default', 'US', 'United States', 'North America', NOW(), 'DAILY');

-- Insert sample alerts
INSERT INTO global_alerts (tenant_id, type, severity, message, title, is_acknowledged, expires_at)
VALUES
    ('default', 'PERFORMANCE', 'HIGH', 'API response time increased', 'Performance Warning', FALSE, NOW() + INTERVAL '24 hours');

-- ============================================================================
-- Grant Permissions (if needed for your database user)
-- ============================================================================

-- Uncomment and run these if you have a specific database user:
-- GRANT ALL ON SCHEMA public TO your_gogidix_user;
-- GRANT ALL ON ALL TABLES IN SCHEMA public TO your_gogidix_user;

-- ============================================================================
-- Complete
-- ============================================================================
