server:
  port: 8085

spring:
  application:
    name: Sms-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_sms
  cloud:
    stream:
      function:
        definition: smsEvents
      bindings:
        smsEvents-out-0:
          destination: smsEvents
          contentType: application/json

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true