spring:
  application:
    name: discount-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_discount
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        discountEvents-out-0:
          destination: discount-events
          content-type: application/json
server:
  port: 8070
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.discount: DEBUG
