spring:
  application:
    name: sms-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_sms
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        smsEvents-out-0:
          destination: sms-events
          content-type: application/json
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.sms: DEBUG
