package com.gogidix.aiservices.aidocumentprocessingservice.infrastructure.config;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

@DisplayName("OCR Service Properties Configuration Tests")
class OcrServicePropertiesTest {

    @Nested
    @DisplayName("Default Values Tests")
    class DefaultValuesTests {

        @Test
        @DisplayName("Should have default service URL")
        void shouldHaveDefaultServiceUrl() {
            OcrServiceProperties properties = new OcrServiceProperties();
            assertThat(properties.getServiceUrl()).isEqualTo("http://localhost:8080");
        }

        @Test
        @DisplayName("Should have default health endpoint")
        void shouldHaveDefaultHealthEndpoint() {
            OcrServiceProperties properties = new OcrServiceProperties();
            assertThat(properties.getHealthEndpoint()).isEqualTo("/health");
        }

        @Test
        @DisplayName("Should have default timeout")
        void shouldHaveDefaultTimeout() {
            OcrServiceProperties properties = new OcrServiceProperties();
            assertThat(properties.getTimeoutMs()).isEqualTo(30000);
        }
    }

    @Nested
    @DisplayName("Setter and Getter Tests")
    class SetterGetterTests {

        @Test
        @DisplayName("Should set and get service URL")
        void shouldSetAndGetServiceUrl() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setServiceUrl("http://custom-ocr-service:9090");
            assertThat(properties.getServiceUrl()).isEqualTo("http://custom-ocr-service:9090");
        }

        @Test
        @DisplayName("Should set and get health endpoint")
        void shouldSetAndGetHealthEndpoint() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setHealthEndpoint("/status");
            assertThat(properties.getHealthEndpoint()).isEqualTo("/status");
        }

        @Test
        @DisplayName("Should set and get timeout")
        void shouldSetAndGetTimeout() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setTimeoutMs(60000);
            assertThat(properties.getTimeoutMs()).isEqualTo(60000);
        }
    }

    @Nested
    @DisplayName("Configuration Annotations Tests")
    class ConfigurationAnnotationsTests {

        @Test
        @DisplayName("Should be instantiable for Spring")
        void shouldBeInstantiable() {
            OcrServiceProperties properties = new OcrServiceProperties();
            assertThat(properties).isNotNull();
        }

        @Test
        @DisplayName("Should support lombok Data annotation")
        void shouldSupportLombokData() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setServiceUrl("http://test");
            properties.setHealthEndpoint("/health");
            properties.setTimeoutMs(10000);

            // Test equals/hashCode/toString generated by Lombok
            OcrServiceProperties properties2 = new OcrServiceProperties();
            properties2.setServiceUrl("http://test");
            properties2.setHealthEndpoint("/health");
            properties2.setTimeoutMs(10000);

            assertThat(properties).isEqualTo(properties2);
            assertThat(properties.hashCode()).isEqualTo(properties2.hashCode());
        }
    }

    @Nested
    @DisplayName("Edge Cases Tests")
    class EdgeCasesTests {

        @Test
        @DisplayName("Should accept empty service URL")
        void shouldAcceptEmptyServiceUrl() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setServiceUrl("");
            assertThat(properties.getServiceUrl()).isEqualTo("");
        }

        @Test
        @DisplayName("Should accept null health endpoint")
        void shouldAcceptNullHealthEndpoint() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setHealthEndpoint(null);
            assertThat(properties.getHealthEndpoint()).isNull();
        }

        @Test
        @DisplayName("Should accept zero timeout")
        void shouldAcceptZeroTimeout() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setTimeoutMs(0);
            assertThat(properties.getTimeoutMs()).isEqualTo(0);
        }

        @Test
        @DisplayName("Should accept negative timeout (edge case)")
        void shouldAcceptNegativeTimeout() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setTimeoutMs(-1000);
            assertThat(properties.getTimeoutMs()).isEqualTo(-1000);
        }

        @Test
        @DisplayName("Should accept very large timeout value")
        void shouldAcceptLargeTimeout() {
            OcrServiceProperties properties = new OcrServiceProperties();
            properties.setTimeoutMs(Integer.MAX_VALUE);
            assertThat(properties.getTimeoutMs()).isEqualTo(Integer.MAX_VALUE);
        }
    }
}
