apiVersion: v1
kind: Service
metadata:
  name: expiration-service
  namespace: warehousing-core
  labels:
    app: expiration-service
    service: expiration-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 8217
    targetPort: http
    protocol: TCP
  - name: management
    port: 8218
    targetPort: management
    protocol: TCP
  selector:
    app: expiration-service
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-service-headless
  namespace: warehousing-core
  labels:
    app: expiration-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8217
    targetPort: http
    protocol: TCP
  selector:
    app: expiration-service
