export enum ActionType {
  // Communication actions
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_SMS = 'SEND_SMS',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  SEND_WEBHOOK = 'SEND_WEBHOOK',

  // Task actions
  CREATE_TASK = 'CREATE_TASK',
  ASSIGN_TASK = 'ASSIGN_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  COMPLETE_TASK = 'COMPLETE_TASK',

  // Lead actions
  UPDATE_LEAD_STATUS = 'UPDATE_LEAD_STATUS',
  ASSIGN_LEAD = 'ASSIGN_LEAD',
  SCORE_LEAD = 'SCORE_LEAD',
  ADD_LEAD_TAG = 'ADD_LEAD_TAG',
  REMOVE_LEAD_TAG = 'REMOVE_LEAD_TAG',

  // Deal actions
  UPDATE_DEAL_STAGE = 'UPDATE_DEAL_STAGE',
  UPDATE_DEAL_AMOUNT = 'UPDATE_DEAL_AMOUNT',
  ASSIGN_DEAL = 'ASSIGN_DEAL',
  ADD_DEAL_NOTE = 'ADD_DEAL_NOTE',

  // Contact actions
  ADD_CONTACT_TAG = 'ADD_CONTACT_TAG',
  REMOVE_CONTACT_TAG = 'REMOVE_CONTACT_TAG',
  UPDATE_CONTACT_FIELD = 'UPDATE_CONTACT_FIELD',

  // Field actions
  UPDATE_FIELD = 'UPDATE_FIELD',
  INCREMENT_FIELD = 'INCREMENT_FIELD',
  DECREMENT_FIELD = 'DECREMENT_FIELD',

  // Workflow actions
  START_WORKFLOW = 'START_WORKFLOW',
  STOP_WORKFLOW = 'STOP_WORKFLOW',
  EXECUTE_WORKFLOW = 'EXECUTE_WORKFLOW',

  // Custom actions
  CUSTOM_SCRIPT = 'CUSTOM_SCRIPT',
  CUSTOM_FUNCTION = 'CUSTOM_FUNCTION',
}
