export enum TriggerType {
  // Lead triggers
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  LEAD_SCORE_CHANGED = 'LEAD_SCORE_CHANGED',

  // Deal triggers
  DEAL_CREATED = 'DEAL_CREATED',
  DEAL_UPDATED = 'DEAL_UPDATED',
  DEAL_STAGE_CHANGED = 'DEAL_STAGE_CHANGED',
  DEAL_AMOUNT_CHANGED = 'DEAL_AMOUNT_CHANGED',
  DEAL_WON = 'DEAL_WON',
  DEAL_LOST = 'DEAL_LOST',

  // Activity triggers
  ACTIVITY_LOGGED = 'ACTIVITY_LOGGED',
  ACTIVITY_TYPE_SPECIFIC = 'ACTIVITY_TYPE_SPECIFIC',
  EMAIL_OPENED = 'EMAIL_OPENED',
  EMAIL_CLICKED = 'EMAIL_CLICKED',
  EMAIL_REPLIED = 'EMAIL_REPLIED',

  // Contact triggers
  CONTACT_CREATED = 'CONTACT_CREATED',
  CONTACT_UPDATED = 'CONTACT_UPDATED',
  CONTACT_TAGGED = 'CONTACT_TAGGED',

  // Task triggers
  TASK_CREATED = 'TASK_CREATED',
  TASK_DUE = 'TASK_DUE',
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_COMPLETED = 'TASK_COMPLETED',

  // Schedule triggers
  SCHEDULED = 'SCHEDULED',
  CRON = 'CRON',

  // Webhook triggers
  WEBHOOK = 'WEBHOOK',

  // Custom triggers
  CUSTOM = 'CUSTOM',
}
