import type {
  RegionalMetrics,
  CountryMetrics,
  Currency,
  GBMKPI,
  AggregationBatch,
  RealTimeDataStream,
  GBMReport,
  ReportTemplate,
  GBMDashboard,
  DataExport,
  Language,
  LocalizationSettings,
} from '@shared/types'

// Regional Metrics Mock Data
export const regionalMetricsData: RegionalMetrics[] = [
  {
    id: 'reg-na-001',
    region: 'north-america',
    regionName: 'North America',
    countries: ['US', 'CA'],
    totalRevenue: 18500000,
    revenueTarget: 20000000,
    growthRate: 12.3,
    marketShare: 28.5,
    customerCount: 45000,
    activeBusinesses: 3200,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-eu-001',
    region: 'europe',
    regionName: 'Europe',
    countries: ['UK'],
    totalRevenue: 12000000,
    revenueTarget: 15000000,
    growthRate: -5.2,
    marketShare: 18.2,
    customerCount: 28000,
    activeBusinesses: 1900,
    status: 'at_risk',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-af-n-001',
    region: 'africa-north',
    regionName: 'Africa North',
    countries: ['EG'],
    totalRevenue: 5200000,
    revenueTarget: 6000000,
    growthRate: 8.7,
    marketShare: 7.8,
    customerCount: 15000,
    activeBusinesses: 850,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-af-w-001',
    region: 'africa-west',
    regionName: 'Africa West',
    countries: ['NG', 'GH'],
    totalRevenue: 8900000,
    revenueTarget: 8500000,
    growthRate: 18.7,
    marketShare: 13.5,
    customerCount: 35000,
    activeBusinesses: 2400,
    status: 'ahead',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-af-e-001',
    region: 'africa-east',
    regionName: 'Africa East',
    countries: ['KE'],
    totalRevenue: 3200000,
    revenueTarget: 4000000,
    growthRate: 15.2,
    marketShare: 4.8,
    customerCount: 12000,
    activeBusinesses: 680,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-af-s-001',
    region: 'africa-south',
    regionName: 'Africa South',
    countries: ['ZA'],
    totalRevenue: 2800000,
    revenueTarget: 3500000,
    growthRate: 6.5,
    marketShare: 4.2,
    customerCount: 8500,
    activeBusinesses: 520,
    status: 'behind',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-ap-001',
    region: 'asia-pacific',
    regionName: 'Asia Pacific',
    countries: ['IN', 'JP', 'AU'],
    totalRevenue: 14200000,
    revenueTarget: 16000000,
    growthRate: 9.8,
    marketShare: 21.5,
    customerCount: 38000,
    activeBusinesses: 2100,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'reg-la-001',
    region: 'latin-america',
    regionName: 'Latin America',
    countries: ['BR', 'MX'],
    totalRevenue: 6500000,
    revenueTarget: 7500000,
    growthRate: 7.2,
    marketShare: 9.8,
    customerCount: 18000,
    activeBusinesses: 1150,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
]

// Country Metrics Mock Data
export const countryMetricsData: CountryMetrics[] = [
  {
    id: 'ctry-us-001',
    country: 'US',
    countryName: 'United States',
    region: 'north-america',
    currency: 'USD',
    totalRevenue: 15500000,
    revenueTarget: 17000000,
    localCurrencyRevenue: 15500000,
    growthRate: 11.5,
    marketShare: 23.5,
    customerCount: 38000,
    activeBusinesses: 2800,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-ca-001',
    country: 'CA',
    countryName: 'Canada',
    region: 'north-america',
    currency: 'CAD',
    totalRevenue: 3000000,
    revenueTarget: 3000000,
    localCurrencyRevenue: 4050000,
    growthRate: 15.2,
    marketShare: 4.5,
    customerCount: 7000,
    activeBusinesses: 400,
    status: 'ahead',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-ng-001',
    country: 'NG',
    countryName: 'Nigeria',
    region: 'africa-west',
    currency: 'NGN',
    totalRevenue: 7200000,
    revenueTarget: 7000000,
    localCurrencyRevenue: 5625000000,
    growthRate: 19.5,
    marketShare: 10.9,
    customerCount: 28000,
    activeBusinesses: 1950,
    status: 'ahead',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-ke-001',
    country: 'KE',
    countryName: 'Kenya',
    region: 'africa-east',
    currency: 'KES',
    totalRevenue: 3200000,
    revenueTarget: 4000000,
    localCurrencyRevenue: 416000000,
    growthRate: 15.2,
    marketShare: 4.8,
    customerCount: 12000,
    activeBusinesses: 680,
    status: 'on_track',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-za-001',
    country: 'ZA',
    countryName: 'South Africa',
    region: 'africa-south',
    currency: 'ZAR',
    totalRevenue: 2800000,
    revenueTarget: 3500000,
    localCurrencyRevenue: 53200000,
    growthRate: 6.5,
    marketShare: 4.2,
    customerCount: 8500,
    activeBusinesses: 520,
    status: 'behind',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-gh-001',
    country: 'GH',
    countryName: 'Ghana',
    region: 'africa-west',
    currency: 'GHS',
    totalRevenue: 1700000,
    revenueTarget: 1500000,
    localCurrencyRevenue: 26000000,
    growthRate: 16.8,
    marketShare: 2.6,
    customerCount: 7000,
    activeBusinesses: 450,
    status: 'ahead',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'ctry-uk-001',
    country: 'UK',
    countryName: 'United Kingdom',
    region: 'europe',
    currency: 'GBP',
    totalRevenue: 12000000,
    revenueTarget: 15000000,
    localCurrencyRevenue: 9500000,
    growthRate: -5.2,
    marketShare: 18.2,
    customerCount: 28000,
    activeBusinesses: 1900,
    status: 'at_risk',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
]

// Currency Mock Data
export const currenciesData: Currency[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸', exchangeRate: 1.0, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺', exchangeRate: 0.92, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧', exchangeRate: 0.79, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬', exchangeRate: 0.0013, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪', exchangeRate: 0.0077, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦', exchangeRate: 0.053, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭', exchangeRate: 0.092, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', flag: '🇪🇬', exchangeRate: 0.032, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳', exchangeRate: 0.012, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵', exchangeRate: 0.0067, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: '🇦🇺', exchangeRate: 0.65, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷', exchangeRate: 0.20, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', flag: '🇲🇽', exchangeRate: 0.059, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: '🇨🇦', exchangeRate: 0.74, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪', exchangeRate: 0.27, baseCurrency: 'USD', lastUpdated: '2024-03-01T00:00:00Z', isActive: true },
]

// KPI Mock Data
export const gbmKPIData: GBMKPI[] = [
  {
    id: 'kpi-001',
    name: 'Global Revenue',
    description: 'Total revenue across all regions',
    category: 'revenue',
    value: 68900000,
    target: 75000000,
    unit: 'USD',
    trend: 'up',
    trendValue: 8.5,
    status: 'on_track',
    scope: 'global',
    owner: 'GBM Team',
    frequency: 'monthly',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'kpi-002',
    name: 'Market Share',
    description: 'Overall market share percentage',
    category: 'market',
    value: 24.8,
    target: 25.0,
    unit: '%',
    trend: 'up',
    trendValue: 2.3,
    status: 'on_track',
    scope: 'global',
    owner: 'GBM Team',
    frequency: 'monthly',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'kpi-003',
    name: 'Customer Growth',
    description: 'New customer acquisition rate',
    category: 'growth',
    value: 198500,
    target: 200000,
    unit: 'customers',
    trend: 'up',
    trendValue: 12.7,
    status: 'on_track',
    scope: 'global',
    owner: 'GBM Team',
    frequency: 'monthly',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
  {
    id: 'kpi-004',
    name: 'Active Businesses',
    description: 'Total active business accounts',
    category: 'operational',
    value: 12800,
    target: 15000,
    unit: 'businesses',
    trend: 'up',
    trendValue: 9.2,
    status: 'behind',
    scope: 'global',
    owner: 'GBM Team',
    frequency: 'monthly',
    lastUpdated: '2024-03-01T10:30:00Z',
  },
]

// Aggregation Batches Mock Data
export const aggregationBatchesData: AggregationBatch[] = [
  {
    id: 'agg-001',
    name: 'Monthly Global Aggregation',
    type: 'monthly',
    status: 'completed',
    sourceRegions: ['north-america', 'europe', 'africa-north', 'africa-west', 'africa-east', 'africa-south', 'asia-pacific', 'latin-america'],
    sourceCountries: [],
    dataPoints: 245000,
    startedAt: '2024-03-01T00:00:00Z',
    completedAt: '2024-03-01T02:30:00Z',
  },
  {
    id: 'agg-002',
    name: 'Weekly Regional Snapshot',
    type: 'weekly',
    status: 'running',
    sourceRegions: ['africa-west', 'africa-east'],
    sourceCountries: [],
    dataPoints: 45000,
    startedAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'agg-003',
    name: 'Daily Country Sync',
    type: 'daily',
    status: 'pending',
    sourceRegions: [],
    sourceCountries: ['NG', 'KE', 'ZA', 'GH'],
    dataPoints: 12000,
    startedAt: '2024-03-01T10:00:00Z',
  },
]

// Real-time Data Streams Mock Data
export const realTimeDataStreamsData: RealTimeDataStream[] = [
  {
    id: 'stream-001',
    name: 'Global Revenue Stream',
    source: 'north-america',
    metrics: ['revenue', 'orders', 'customers'],
    updateFrequency: 30,
    isActive: true,
    lastUpdate: '2024-03-01T10:30:00Z',
  },
  {
    id: 'stream-002',
    name: 'Africa Regional Stream',
    source: 'africa-west',
    metrics: ['revenue', 'growth', 'market_share'],
    updateFrequency: 60,
    isActive: true,
    lastUpdate: '2024-03-01T10:29:00Z',
  },
  {
    id: 'stream-003',
    name: 'Country Metrics Stream',
    source: 'NG',
    metrics: ['revenue', 'customers', 'active_businesses'],
    updateFrequency: 15,
    isActive: true,
    lastUpdate: '2024-03-01T10:30:00Z',
  },
]

// Reports Mock Data
export const gbmReportsData: GBMReport[] = [
  {
    id: 'rpt-001',
    name: 'Q1 2024 Global Performance Report',
    type: 'executive',
    description: 'Comprehensive quarterly performance analysis across all regions',
    createdBy: 'Amanda Sterling',
    createdAt: '2024-02-28T15:30:00Z',
    format: 'pdf',
    size: 2450000,
    downloadUrl: '/downloads/q1-2024-global-report.pdf',
    schedule: {
      frequency: 'quarterly',
      dayOfMonth: 1,
      time: '09:00',
      recipients: ['gbm-admin@gogidix.com', 'ceo@gogidix.com'],
      isActive: true,
    },
    parameters: [
      { name: 'regions', value: ['all'], type: 'array' },
      { name: 'includeCharts', value: true, type: 'boolean' },
      { name: 'currency', value: 'USD', type: 'string' },
    ],
  },
  {
    id: 'rpt-002',
    name: 'Africa West Regional Analysis',
    type: 'regional',
    description: 'Detailed analysis of West Africa regional performance',
    createdBy: 'Chinedu Okonkwo',
    createdAt: '2024-02-25T10:00:00Z',
    format: 'excel',
    size: 1850000,
    downloadUrl: '/downloads/africa-west-analysis.xlsx',
    parameters: [
      { name: 'region', value: 'africa-west', type: 'region' },
      { name: 'countries', value: ['NG', 'GH'], type: 'array' },
    ],
  },
  {
    id: 'rpt-003',
    name: 'Nigeria Monthly Metrics',
    type: 'country',
    description: 'Monthly performance metrics for Nigeria',
    createdBy: 'Ngozi Adewale',
    createdAt: '2024-02-20T14:00:00Z',
    format: 'powerpoint',
    size: 890000,
    downloadUrl: '/downloads/nigeria-monthly-metrics.pptx',
    schedule: {
      frequency: 'monthly',
      dayOfMonth: 1,
      time: '08:00',
      recipients: ['country-admin-nigeria@gogidix.com'],
      isActive: true,
    },
    parameters: [
      { name: 'country', value: 'NG', type: 'country' },
      { name: 'currency', value: 'NGN', type: 'string' },
    ],
  },
]

// Report Templates Mock Data
export const reportTemplatesData: ReportTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Executive Summary Template',
    description: 'High-level executive overview with key metrics',
    category: 'executive',
    parameters: [
      { name: 'timeRange', value: '30', type: 'number' },
      { name: 'includeProjections', value: true, type: 'boolean' },
    ],
    createdBy: 'System',
    createdAt: '2024-01-01T00:00:00Z',
    isPublic: true,
  },
  {
    id: 'tpl-002',
    name: 'Regional Performance Template',
    description: 'Detailed regional performance analysis',
    category: 'operational',
    parameters: [
      { name: 'regions', value: [], type: 'array' },
      { name: 'metrics', value: ['revenue', 'growth', 'market_share'], type: 'array' },
    ],
    createdBy: 'System',
    createdAt: '2024-01-01T00:00:00Z',
    isPublic: true,
  },
  {
    id: 'tpl-003',
    name: 'Country Deep Dive Template',
    description: 'Comprehensive country-level analysis',
    category: 'financial',
    parameters: [
      { name: 'country', value: '', type: 'country' },
      { name: 'includeCurrency', value: true, type: 'boolean' },
    ],
    createdBy: 'System',
    createdAt: '2024-01-01T00:00:00Z',
    isPublic: true,
  },
]

// Dashboards Mock Data
export const gbmDashboardsData: GBMDashboard[] = [
  {
    id: 'dash-001',
    name: 'Executive Overview',
    description: 'High-level view of global business metrics',
    type: 'executive',
    owner: 'Amanda Sterling',
    widgets: [
      {
        id: 'wgt-001',
        type: 'metric',
        title: 'Total Revenue',
        position: { x: 0, y: 0, w: 3, h: 2 },
        dataSource: 'global-revenue',
        config: { format: 'currency', showTrend: true },
      },
      {
        id: 'wgt-002',
        type: 'chart',
        title: 'Revenue by Region',
        position: { x: 3, y: 0, w: 6, h: 3 },
        dataSource: 'regional-revenue',
        config: { chartType: 'bar' },
      },
    ],
    filters: [
      { id: 'flt-001', name: 'Date Range', type: 'date', defaultValue: 'last30days' },
      { id: 'flt-002', name: 'Region', type: 'region', defaultValue: 'all' },
    ],
    isPublic: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-02-28T00:00:00Z',
  },
  {
    id: 'dash-002',
    name: 'Africa Performance',
    description: 'Detailed Africa regional metrics',
    type: 'regional',
    owner: 'Chinedu Okonkwo',
    widgets: [
      {
        id: 'wgt-003',
        type: 'map',
        title: 'Africa Revenue Map',
        position: { x: 0, y: 0, w: 12, h: 4 },
        dataSource: 'africa-revenue',
        config: { mapType: 'africa' },
      },
    ],
    filters: [
      { id: 'flt-003', name: 'Country', type: 'multiselect', defaultValue: ['NG', 'KE', 'ZA', 'GH'], options: [] },
    ],
    isPublic: false,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-25T00:00:00Z',
  },
]

// Data Exports Mock Data
export const dataExportsData: DataExport[] = [
  {
    id: 'exp-001',
    name: 'Monthly Revenue Export',
    type: 'revenue',
    format: 'csv',
    status: 'completed',
    fileSize: 2450000,
    downloadUrl: '/exports/monthly-revenue-2024-02.csv',
    createdAt: '2024-02-29T23:59:00Z',
    completedAt: '2024-03-01T00:05:00Z',
    createdBy: 'Amanda Sterling',
    parameters: [
      { name: 'month', value: '2024-02' },
      { name: 'includeRegions', value: true },
    ],
  },
  {
    id: 'exp-002',
    name: 'Customer Data Export',
    type: 'customers',
    format: 'excel',
    status: 'processing',
    createdAt: '2024-03-01T10:00:00Z',
    createdBy: 'David Kim',
    parameters: [
      { name: 'regions', value: ['all'] },
      { name: 'includeInactive', value: false },
    ],
  },
  {
    id: 'exp-003',
    name: 'Regional Summary PDF',
    type: 'regional',
    format: 'pdf',
    status: 'pending',
    createdAt: '2024-03-01T10:15:00Z',
    createdBy: 'Chinedu Okonkwo',
    parameters: [
      { name: 'regions', value: ['africa-west', 'africa-east'] },
      { name: 'includeCharts', value: true },
    ],
  },
]

// Languages Mock Data
export const languagesData: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', isActive: true, completionPercentage: 100 },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', isActive: true, completionPercentage: 95 },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', isActive: true, completionPercentage: 90 },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', isActive: true, completionPercentage: 85 },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', isActive: true, completionPercentage: 80 },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪', isActive: true, completionPercentage: 75 },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', flag: '🇳🇬', isActive: false, completionPercentage: 40 },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬', isActive: false, completionPercentage: 35 },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo', flag: '🇳🇬', isActive: false, completionPercentage: 30 },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', isActive: true, completionPercentage: 88 },
]

// Localization Settings Mock Data
export const localizationSettingsData: LocalizationSettings = {
  defaultLanguage: 'en',
  supportedLanguages: ['en', 'fr', 'es', 'pt', 'ar', 'sw', 'ja'],
  defaultCurrency: 'USD',
  supportedCurrencies: ['USD', 'EUR', 'GBP', 'NGN', 'KES', 'ZAR', 'GHS', 'EGP', 'INR', 'JPY', 'AUD', 'BRL', 'MXN', 'CAD', 'AED'],
  dateFormat: 'MM/DD/YYYY',
  timeFormat: '12h',
  numberFormat: 'US',
}
