apiVersion: v1
kind: Service
metadata:
  name: ai-authentication-service
  namespace: ai-services
  labels:
    app: ai-authentication-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-authentication-service
  ports:
  - name: http
    port: 8260
    targetPort: 8260
    protocol: TCP
