package com.gogidix.finance.accountsreceivable.domain.port.in;

import com.gogidix.finance.accountsreceivable.domain.port.in.CustomerCommand;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class CustomerCommand_UpdateCustomerCommandTest {

        @Test
    void testSettersAndGetters() {
        CustomerCommand.UpdateCustomerCommand dto = new CustomerCommand.UpdateCustomerCommand();
        dto.setTenantId("val-tenantId");
        dto.setCustomerId("val-customerId");
        dto.setCustomerName("val-customerName");
        dto.setEmail("val-email");
        dto.setPhone("val-phone");
        dto.setWebsite("val-website");
        dto.setBillingAddressLine1("val-billingAddressLine1");
        dto.setBillingAddressLine2("val-billingAddressLine2");
        dto.setBillingCity("val-billingCity");
        dto.setBillingState("val-billingState");
        dto.setBillingPostalCode("val-billingPostalCode");
        dto.setBillingCountry("val-billingCountry");
        dto.setShippingAddressLine1("val-shippingAddressLine1");
        dto.setShippingAddressLine2("val-shippingAddressLine2");
        dto.setShippingCity("val-shippingCity");
        dto.setShippingState("val-shippingState");
        dto.setShippingPostalCode("val-shippingPostalCode");
        dto.setShippingCountry("val-shippingCountry");
        dto.setPaymentTerms("val-paymentTerms");
        dto.setCreditLimit(99);
        dto.setCreditDays(99);
        dto.setSalesRepresentative("val-salesRepresentative");
        dto.setIndustry("val-industry");
        dto.setNotes("val-notes");
        dto.setDefaultPaymentMethod("val-defaultPaymentMethod");
        dto.setBankAccountNumber("val-bankAccountNumber");
        dto.setBankName("val-bankName");
        dto.setBankRoutingNumber("val-bankRoutingNumber");
        dto.setAllowCredit(true);
        dto.setSendElectronicInvoices(true);
        dto.setInvoiceDeliveryEmail("val-invoiceDeliveryEmail");
        dto.setPaymentGatewayCustomerId("val-paymentGatewayCustomerId");
        dto.setAutoChargePaymentMethod(true);
        assertEquals("val-tenantId", dto.getTenantId());
        assertEquals("val-customerId", dto.getCustomerId());
        assertEquals("val-customerName", dto.getCustomerName());
        assertEquals("val-email", dto.getEmail());
        assertEquals("val-phone", dto.getPhone());
        assertEquals("val-website", dto.getWebsite());
        assertEquals("val-billingAddressLine1", dto.getBillingAddressLine1());
        assertEquals("val-billingAddressLine2", dto.getBillingAddressLine2());
        assertEquals("val-billingCity", dto.getBillingCity());
        assertEquals("val-billingState", dto.getBillingState());
        assertEquals("val-billingPostalCode", dto.getBillingPostalCode());
        assertEquals("val-billingCountry", dto.getBillingCountry());
        assertEquals("val-shippingAddressLine1", dto.getShippingAddressLine1());
        assertEquals("val-shippingAddressLine2", dto.getShippingAddressLine2());
        assertEquals("val-shippingCity", dto.getShippingCity());
        assertEquals("val-shippingState", dto.getShippingState());
        assertEquals("val-shippingPostalCode", dto.getShippingPostalCode());
        assertEquals("val-shippingCountry", dto.getShippingCountry());
        assertEquals("val-paymentTerms", dto.getPaymentTerms());
        assertEquals(99, dto.getCreditLimit());
        assertEquals(99, dto.getCreditDays());
        assertEquals("val-salesRepresentative", dto.getSalesRepresentative());
        assertEquals("val-industry", dto.getIndustry());
        assertEquals("val-notes", dto.getNotes());
        assertEquals("val-defaultPaymentMethod", dto.getDefaultPaymentMethod());
        assertEquals("val-bankAccountNumber", dto.getBankAccountNumber());
        assertEquals("val-bankName", dto.getBankName());
        assertEquals("val-bankRoutingNumber", dto.getBankRoutingNumber());
        assertTrue(dto.getAllowCredit());
        assertTrue(dto.getSendElectronicInvoices());
        assertEquals("val-invoiceDeliveryEmail", dto.getInvoiceDeliveryEmail());
        assertEquals("val-paymentGatewayCustomerId", dto.getPaymentGatewayCustomerId());
        assertTrue(dto.getAutoChargePaymentMethod());
    }

    @Test
    void testEqualsAndHashCode() {
        CustomerCommand.UpdateCustomerCommand dto1 = new CustomerCommand.UpdateCustomerCommand();
        CustomerCommand.UpdateCustomerCommand dto2 = new CustomerCommand.UpdateCustomerCommand();
        dto1.setTenantId("test");
        dto1.setCustomerId("test");
        dto1.setCustomerName("test");
        dto1.setEmail("test");
        dto1.setPhone("test");
        dto1.setWebsite("test");
        dto1.setBillingAddressLine1("test");
        dto1.setBillingAddressLine2("test");
        dto1.setBillingCity("test");
        dto1.setBillingState("test");
        dto1.setBillingPostalCode("test");
        dto1.setBillingCountry("test");
        dto1.setShippingAddressLine1("test");
        dto1.setShippingAddressLine2("test");
        dto1.setShippingCity("test");
        dto1.setShippingState("test");
        dto1.setShippingPostalCode("test");
        dto1.setShippingCountry("test");
        dto1.setPaymentTerms("test");
        dto1.setCreditLimit(42);
        dto1.setCreditDays(42);
        dto1.setSalesRepresentative("test");
        dto1.setIndustry("test");
        dto1.setNotes("test");
        dto1.setDefaultPaymentMethod("test");
        dto1.setBankAccountNumber("test");
        dto1.setBankName("test");
        dto1.setBankRoutingNumber("test");
        dto1.setAllowCredit(true);
        dto1.setSendElectronicInvoices(true);
        dto1.setInvoiceDeliveryEmail("test");
        dto1.setTags(Collections.emptyList());
        dto1.setPaymentGatewayCustomerId("test");
        dto1.setAutoChargePaymentMethod(true);
        dto2.setTenantId("test");
        dto2.setCustomerId("test");
        dto2.setCustomerName("test");
        dto2.setEmail("test");
        dto2.setPhone("test");
        dto2.setWebsite("test");
        dto2.setBillingAddressLine1("test");
        dto2.setBillingAddressLine2("test");
        dto2.setBillingCity("test");
        dto2.setBillingState("test");
        dto2.setBillingPostalCode("test");
        dto2.setBillingCountry("test");
        dto2.setShippingAddressLine1("test");
        dto2.setShippingAddressLine2("test");
        dto2.setShippingCity("test");
        dto2.setShippingState("test");
        dto2.setShippingPostalCode("test");
        dto2.setShippingCountry("test");
        dto2.setPaymentTerms("test");
        dto2.setCreditLimit(42);
        dto2.setCreditDays(42);
        dto2.setSalesRepresentative("test");
        dto2.setIndustry("test");
        dto2.setNotes("test");
        dto2.setDefaultPaymentMethod("test");
        dto2.setBankAccountNumber("test");
        dto2.setBankName("test");
        dto2.setBankRoutingNumber("test");
        dto2.setAllowCredit(true);
        dto2.setSendElectronicInvoices(true);
        dto2.setInvoiceDeliveryEmail("test");
        dto2.setTags(Collections.emptyList());
        dto2.setPaymentGatewayCustomerId("test");
        dto2.setAutoChargePaymentMethod(true);
        assertEquals(dto1, dto2);
        assertEquals(dto1.hashCode(), dto2.hashCode());
        dto2.setTenantId(null);
        assertNotEquals(dto1, dto2);
    }

    @Test
    void testToString() {
        CustomerCommand.UpdateCustomerCommand dto = new CustomerCommand.UpdateCustomerCommand();
        dto.setTenantId("test");
        dto.setCustomerId("test");
        dto.setCustomerName("test");
        dto.setEmail("test");
        dto.setPhone("test");
        dto.setWebsite("test");
        dto.setBillingAddressLine1("test");
        dto.setBillingAddressLine2("test");
        dto.setBillingCity("test");
        dto.setBillingState("test");
        dto.setBillingPostalCode("test");
        dto.setBillingCountry("test");
        dto.setShippingAddressLine1("test");
        dto.setShippingAddressLine2("test");
        dto.setShippingCity("test");
        dto.setShippingState("test");
        dto.setShippingPostalCode("test");
        dto.setShippingCountry("test");
        dto.setPaymentTerms("test");
        dto.setCreditLimit(42);
        dto.setCreditDays(42);
        dto.setSalesRepresentative("test");
        dto.setIndustry("test");
        dto.setNotes("test");
        dto.setDefaultPaymentMethod("test");
        dto.setBankAccountNumber("test");
        dto.setBankName("test");
        dto.setBankRoutingNumber("test");
        dto.setAllowCredit(true);
        dto.setSendElectronicInvoices(true);
        dto.setInvoiceDeliveryEmail("test");
        dto.setTags(Collections.emptyList());
        dto.setPaymentGatewayCustomerId("test");
        dto.setAutoChargePaymentMethod(true);
        String str = dto.toString();
        assertNotNull(str);
        assertTrue(str.length() > 0);
    }

    @Test
    void testEqualsNullAndOtherType() {
        CustomerCommand.UpdateCustomerCommand dto = new CustomerCommand.UpdateCustomerCommand();
        dto.setTenantId("test");
        dto.setCustomerId("test");
        dto.setCustomerName("test");
        dto.setEmail("test");
        dto.setPhone("test");
        dto.setWebsite("test");
        dto.setBillingAddressLine1("test");
        dto.setBillingAddressLine2("test");
        dto.setBillingCity("test");
        dto.setBillingState("test");
        dto.setBillingPostalCode("test");
        dto.setBillingCountry("test");
        dto.setShippingAddressLine1("test");
        dto.setShippingAddressLine2("test");
        dto.setShippingCity("test");
        dto.setShippingState("test");
        dto.setShippingPostalCode("test");
        dto.setShippingCountry("test");
        dto.setPaymentTerms("test");
        dto.setCreditLimit(42);
        dto.setCreditDays(42);
        dto.setSalesRepresentative("test");
        dto.setIndustry("test");
        dto.setNotes("test");
        dto.setDefaultPaymentMethod("test");
        dto.setBankAccountNumber("test");
        dto.setBankName("test");
        dto.setBankRoutingNumber("test");
        dto.setAllowCredit(true);
        dto.setSendElectronicInvoices(true);
        dto.setInvoiceDeliveryEmail("test");
        dto.setTags(Collections.emptyList());
        dto.setPaymentGatewayCustomerId("test");
        dto.setAutoChargePaymentMethod(true);
        assertNotEquals(null, dto);
        assertNotEquals("string", dto);
        assertEquals(dto, dto);
    }

}