package com.gogidix.finance.accountsreceivable.domain.port.in;

import com.gogidix.finance.accountsreceivable.domain.model.Invoice;
import com.gogidix.finance.accountsreceivable.domain.port.in.InvoiceCommand;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class InvoiceCommand_CreateInvoiceCommandTest {

        @Test
    void testSettersAndGetters() {
        InvoiceCommand.CreateInvoiceCommand dto = new InvoiceCommand.CreateInvoiceCommand();
        dto.setTenantId("val-tenantId");
        dto.setCustomerId("val-customerId");
        dto.setCustomerName("val-customerName");
        dto.setInvoiceNumber("val-invoiceNumber");
        dto.setInvoiceDate(LocalDate.of(2025,6,1));
        dto.setDueDate(LocalDate.of(2025,6,1));
        dto.setCurrency("val-currency");
        dto.setSalesDate(LocalDate.of(2025,6,1));
        dto.setPurchaseOrderNumber("val-purchaseOrderNumber");
        dto.setCustomerEmail("val-customerEmail");
        dto.setBillingAddressLine1("val-billingAddressLine1");
        dto.setBillingAddressLine2("val-billingAddressLine2");
        dto.setBillingCity("val-billingCity");
        dto.setBillingState("val-billingState");
        dto.setBillingPostalCode("val-billingPostalCode");
        dto.setBillingCountry("val-billingCountry");
        dto.setShippingAddressLine1("val-shippingAddressLine1");
        dto.setShippingAddressLine2("val-shippingAddressLine2");
        dto.setShippingCity("val-shippingCity");
        dto.setShippingState("val-shippingState");
        dto.setShippingPostalCode("val-shippingPostalCode");
        dto.setShippingCountry("val-shippingCountry");
        dto.setPaymentTerms("val-paymentTerms");
        dto.setNotes("val-notes");
        dto.setInternalNotes("val-internalNotes");
        dto.setSalesperson("val-salesperson");
        dto.setProjectId("val-projectId");
        dto.setDepartmentId("val-departmentId");
        dto.setLocationId("val-locationId");
        dto.setTemplateId("val-templateId");
        dto.setTaxInclusive(true);
        dto.setTaxRegistered(true);
        dto.setTaxCode("val-taxCode");
        dto.setTaxRate(BigDecimal.ONE);
        dto.setShippingAmount(BigDecimal.ONE);
        dto.setDiscountCode("val-discountCode");
        dto.setDiscountRate(BigDecimal.ONE);
        dto.setShippingMethod("val-shippingMethod");
        dto.setTrackingNumber("val-trackingNumber");
        dto.setRecurringInvoiceId("val-recurringInvoiceId");
        dto.setIsRecurring(true);
        dto.setParentId("val-parentId");
        dto.setCustomerReference("val-customerReference");
        dto.setGroupId("val-groupId");
        assertEquals("val-tenantId", dto.getTenantId());
        assertEquals("val-customerId", dto.getCustomerId());
        assertEquals("val-customerName", dto.getCustomerName());
        assertEquals("val-invoiceNumber", dto.getInvoiceNumber());
        assertEquals(LocalDate.of(2025,6,1), dto.getInvoiceDate());
        assertEquals(LocalDate.of(2025,6,1), dto.getDueDate());
        assertEquals("val-currency", dto.getCurrency());
        assertEquals(LocalDate.of(2025,6,1), dto.getSalesDate());
        assertEquals("val-purchaseOrderNumber", dto.getPurchaseOrderNumber());
        assertEquals("val-customerEmail", dto.getCustomerEmail());
        assertEquals("val-billingAddressLine1", dto.getBillingAddressLine1());
        assertEquals("val-billingAddressLine2", dto.getBillingAddressLine2());
        assertEquals("val-billingCity", dto.getBillingCity());
        assertEquals("val-billingState", dto.getBillingState());
        assertEquals("val-billingPostalCode", dto.getBillingPostalCode());
        assertEquals("val-billingCountry", dto.getBillingCountry());
        assertEquals("val-shippingAddressLine1", dto.getShippingAddressLine1());
        assertEquals("val-shippingAddressLine2", dto.getShippingAddressLine2());
        assertEquals("val-shippingCity", dto.getShippingCity());
        assertEquals("val-shippingState", dto.getShippingState());
        assertEquals("val-shippingPostalCode", dto.getShippingPostalCode());
        assertEquals("val-shippingCountry", dto.getShippingCountry());
        assertEquals("val-paymentTerms", dto.getPaymentTerms());
        assertEquals("val-notes", dto.getNotes());
        assertEquals("val-internalNotes", dto.getInternalNotes());
        assertEquals("val-salesperson", dto.getSalesperson());
        assertEquals("val-projectId", dto.getProjectId());
        assertEquals("val-departmentId", dto.getDepartmentId());
        assertEquals("val-locationId", dto.getLocationId());
        assertEquals("val-templateId", dto.getTemplateId());
        assertTrue(dto.getTaxInclusive());
        assertTrue(dto.getTaxRegistered());
        assertEquals("val-taxCode", dto.getTaxCode());
        assertEquals(BigDecimal.ONE, dto.getTaxRate());
        assertEquals(BigDecimal.ONE, dto.getShippingAmount());
        assertEquals("val-discountCode", dto.getDiscountCode());
        assertEquals(BigDecimal.ONE, dto.getDiscountRate());
        assertEquals("val-shippingMethod", dto.getShippingMethod());
        assertEquals("val-trackingNumber", dto.getTrackingNumber());
        assertEquals("val-recurringInvoiceId", dto.getRecurringInvoiceId());
        assertTrue(dto.getIsRecurring());
        assertEquals("val-parentId", dto.getParentId());
        assertEquals("val-customerReference", dto.getCustomerReference());
        assertEquals("val-groupId", dto.getGroupId());
    }

    @Test
    void testEqualsAndHashCode() {
        InvoiceCommand.CreateInvoiceCommand dto1 = new InvoiceCommand.CreateInvoiceCommand();
        InvoiceCommand.CreateInvoiceCommand dto2 = new InvoiceCommand.CreateInvoiceCommand();
        dto1.setTenantId("test");
        dto1.setCustomerId("test");
        dto1.setCustomerName("test");
        dto1.setInvoiceNumber("test");
        dto1.setInvoiceType(Invoice.InvoiceType.STANDARD);
        dto1.setInvoiceDate(LocalDate.of(2025,1,1));
        dto1.setDueDate(LocalDate.of(2025,1,1));
        dto1.setCurrency("test");
        dto1.setLineItems(Collections.emptyList());
        dto1.setSalesDate(LocalDate.of(2025,1,1));
        dto1.setPurchaseOrderNumber("test");
        dto1.setCustomerEmail("test");
        dto1.setBillingAddressLine1("test");
        dto1.setBillingAddressLine2("test");
        dto1.setBillingCity("test");
        dto1.setBillingState("test");
        dto1.setBillingPostalCode("test");
        dto1.setBillingCountry("test");
        dto1.setShippingAddressLine1("test");
        dto1.setShippingAddressLine2("test");
        dto1.setShippingCity("test");
        dto1.setShippingState("test");
        dto1.setShippingPostalCode("test");
        dto1.setShippingCountry("test");
        dto1.setPaymentTerms("test");
        dto1.setNotes("test");
        dto1.setInternalNotes("test");
        dto1.setSalesperson("test");
        dto1.setProjectId("test");
        dto1.setDepartmentId("test");
        dto1.setLocationId("test");
        dto1.setTemplateId("test");
        dto1.setTaxInclusive(true);
        dto1.setTaxRegistered(true);
        dto1.setTaxCode("test");
        dto1.setTaxRate(BigDecimal.TEN);
        dto1.setShippingAmount(BigDecimal.TEN);
        dto1.setDiscountCode("test");
        dto1.setDiscountRate(BigDecimal.TEN);
        dto1.setShippingMethod("test");
        dto1.setTrackingNumber("test");
        dto1.setRecurringInvoiceId("test");
        dto1.setIsRecurring(true);
        dto1.setParentId("test");
        dto1.setCustomerReference("test");
        dto1.setGroupId("test");
        dto1.setTags(Collections.emptyList());
        dto2.setTenantId("test");
        dto2.setCustomerId("test");
        dto2.setCustomerName("test");
        dto2.setInvoiceNumber("test");
        dto2.setInvoiceType(Invoice.InvoiceType.STANDARD);
        dto2.setInvoiceDate(LocalDate.of(2025,1,1));
        dto2.setDueDate(LocalDate.of(2025,1,1));
        dto2.setCurrency("test");
        dto2.setLineItems(Collections.emptyList());
        dto2.setSalesDate(LocalDate.of(2025,1,1));
        dto2.setPurchaseOrderNumber("test");
        dto2.setCustomerEmail("test");
        dto2.setBillingAddressLine1("test");
        dto2.setBillingAddressLine2("test");
        dto2.setBillingCity("test");
        dto2.setBillingState("test");
        dto2.setBillingPostalCode("test");
        dto2.setBillingCountry("test");
        dto2.setShippingAddressLine1("test");
        dto2.setShippingAddressLine2("test");
        dto2.setShippingCity("test");
        dto2.setShippingState("test");
        dto2.setShippingPostalCode("test");
        dto2.setShippingCountry("test");
        dto2.setPaymentTerms("test");
        dto2.setNotes("test");
        dto2.setInternalNotes("test");
        dto2.setSalesperson("test");
        dto2.setProjectId("test");
        dto2.setDepartmentId("test");
        dto2.setLocationId("test");
        dto2.setTemplateId("test");
        dto2.setTaxInclusive(true);
        dto2.setTaxRegistered(true);
        dto2.setTaxCode("test");
        dto2.setTaxRate(BigDecimal.TEN);
        dto2.setShippingAmount(BigDecimal.TEN);
        dto2.setDiscountCode("test");
        dto2.setDiscountRate(BigDecimal.TEN);
        dto2.setShippingMethod("test");
        dto2.setTrackingNumber("test");
        dto2.setRecurringInvoiceId("test");
        dto2.setIsRecurring(true);
        dto2.setParentId("test");
        dto2.setCustomerReference("test");
        dto2.setGroupId("test");
        dto2.setTags(Collections.emptyList());
        assertEquals(dto1, dto2);
        assertEquals(dto1.hashCode(), dto2.hashCode());
        dto2.setTenantId(null);
        assertNotEquals(dto1, dto2);
    }

    @Test
    void testToString() {
        InvoiceCommand.CreateInvoiceCommand dto = new InvoiceCommand.CreateInvoiceCommand();
        dto.setTenantId("test");
        dto.setCustomerId("test");
        dto.setCustomerName("test");
        dto.setInvoiceNumber("test");
        dto.setInvoiceType(Invoice.InvoiceType.STANDARD);
        dto.setInvoiceDate(LocalDate.of(2025,1,1));
        dto.setDueDate(LocalDate.of(2025,1,1));
        dto.setCurrency("test");
        dto.setLineItems(Collections.emptyList());
        dto.setSalesDate(LocalDate.of(2025,1,1));
        dto.setPurchaseOrderNumber("test");
        dto.setCustomerEmail("test");
        dto.setBillingAddressLine1("test");
        dto.setBillingAddressLine2("test");
        dto.setBillingCity("test");
        dto.setBillingState("test");
        dto.setBillingPostalCode("test");
        dto.setBillingCountry("test");
        dto.setShippingAddressLine1("test");
        dto.setShippingAddressLine2("test");
        dto.setShippingCity("test");
        dto.setShippingState("test");
        dto.setShippingPostalCode("test");
        dto.setShippingCountry("test");
        dto.setPaymentTerms("test");
        dto.setNotes("test");
        dto.setInternalNotes("test");
        dto.setSalesperson("test");
        dto.setProjectId("test");
        dto.setDepartmentId("test");
        dto.setLocationId("test");
        dto.setTemplateId("test");
        dto.setTaxInclusive(true);
        dto.setTaxRegistered(true);
        dto.setTaxCode("test");
        dto.setTaxRate(BigDecimal.TEN);
        dto.setShippingAmount(BigDecimal.TEN);
        dto.setDiscountCode("test");
        dto.setDiscountRate(BigDecimal.TEN);
        dto.setShippingMethod("test");
        dto.setTrackingNumber("test");
        dto.setRecurringInvoiceId("test");
        dto.setIsRecurring(true);
        dto.setParentId("test");
        dto.setCustomerReference("test");
        dto.setGroupId("test");
        dto.setTags(Collections.emptyList());
        String str = dto.toString();
        assertNotNull(str);
        assertTrue(str.length() > 0);
    }

    @Test
    void testEqualsNullAndOtherType() {
        InvoiceCommand.CreateInvoiceCommand dto = new InvoiceCommand.CreateInvoiceCommand();
        dto.setTenantId("test");
        dto.setCustomerId("test");
        dto.setCustomerName("test");
        dto.setInvoiceNumber("test");
        dto.setInvoiceType(Invoice.InvoiceType.STANDARD);
        dto.setInvoiceDate(LocalDate.of(2025,1,1));
        dto.setDueDate(LocalDate.of(2025,1,1));
        dto.setCurrency("test");
        dto.setLineItems(Collections.emptyList());
        dto.setSalesDate(LocalDate.of(2025,1,1));
        dto.setPurchaseOrderNumber("test");
        dto.setCustomerEmail("test");
        dto.setBillingAddressLine1("test");
        dto.setBillingAddressLine2("test");
        dto.setBillingCity("test");
        dto.setBillingState("test");
        dto.setBillingPostalCode("test");
        dto.setBillingCountry("test");
        dto.setShippingAddressLine1("test");
        dto.setShippingAddressLine2("test");
        dto.setShippingCity("test");
        dto.setShippingState("test");
        dto.setShippingPostalCode("test");
        dto.setShippingCountry("test");
        dto.setPaymentTerms("test");
        dto.setNotes("test");
        dto.setInternalNotes("test");
        dto.setSalesperson("test");
        dto.setProjectId("test");
        dto.setDepartmentId("test");
        dto.setLocationId("test");
        dto.setTemplateId("test");
        dto.setTaxInclusive(true);
        dto.setTaxRegistered(true);
        dto.setTaxCode("test");
        dto.setTaxRate(BigDecimal.TEN);
        dto.setShippingAmount(BigDecimal.TEN);
        dto.setDiscountCode("test");
        dto.setDiscountRate(BigDecimal.TEN);
        dto.setShippingMethod("test");
        dto.setTrackingNumber("test");
        dto.setRecurringInvoiceId("test");
        dto.setIsRecurring(true);
        dto.setParentId("test");
        dto.setCustomerReference("test");
        dto.setGroupId("test");
        dto.setTags(Collections.emptyList());
        assertNotEquals(null, dto);
        assertNotEquals("string", dto);
        assertEquals(dto, dto);
    }

}