apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-model-training-service
  namespace: ai-services
  labels:
    app: ai-model-training-service
    team: team-ai-mlops
  annotations:
    iam.gke.io/gcp-service-account: ai-model-training-service@gogidix-ai.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-model-training-service-role
  namespace: ai-services
  labels:
    app: ai-model-training-service
    team: team-ai-mlops
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-model-training-service-rolebinding
  namespace: ai-services
  labels:
    app: ai-model-training-service
    team: team-ai-mlops
subjects:
- kind: ServiceAccount
  name: ai-model-training-service
  namespace: ai-services
roleRef:
  kind: Role
  name: ai-model-training-service-role
  apiGroup: rbac.authorization.k8s.io
