apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-processing-service-config
  namespace: business-operations
  labels:
    app: payment-processing-service
    team: team-d-business-operations
data:
  redis-host: "redis"
  redis-port: "6379"
  kafka-bootstrap-servers: "kafka:9092"
