import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  TrendingUp,
  Scale,
  DollarSign,
  BarChart3,
  Globe,
  Shield,
  FileText,
  Palette,
  ChevronRight,
  ChevronLeft,
  Check,
  Loader2,
  Download,
  RotateCcw,
} from 'lucide-react'
import { useReportsStore } from '@shared/store/reportsStore'
import type { ReportHistory } from '@shared/store/reportsStore'
import { cn } from '@shared/utils/cn'

const ICON_MAP: Record<string, React.ElementType> = {
  TrendingUp,
  Scale,
  DollarSign,
  BarChart3,
  Globe,
  Shield,
  FileText,
  Palette,
}

const COUNTRIES = ['United States', 'United Kingdom', 'Germany', 'France', 'Japan', 'Canada', 'Australia', 'Brazil']

const STEPS = ['Select Template', 'Configure', 'Format', 'Review & Generate']

export default function GenerateReportPage() {
  const {
    templates,
    generation,
    setGenerationStep,
    setGenerationField,
    startGeneration,
    completeGeneration,
    resetGeneration,
    user,
    setNotification,
  } = useReportsStore()
  const navigate = useNavigate()
  const [localGenerating, setLocalGenerating] = useState(false)

  useEffect(() => {
    return () => {
      if (generation.step === 4 && generation.result) {
        resetGeneration()
      }
    }
  }, [])

  const canProceed = () => {
    switch (generation.step) {
      case 1:
        return !!generation.selectedTemplate
      case 2:
        return !!generation.reportName && !!generation.period
      case 3:
        return !!generation.format
      case 4:
        return true
      default:
        return false
    }
  }

  const handleGenerate = async () => {
    startGeneration()
    setLocalGenerating(true)

    for (let i = 0; i <= 100; i += 5) {
      await new Promise((r) => setTimeout(r, 120))
      setGenerationField('progress', i)
    }

    const template = templates.find((t) => t.id === generation.selectedTemplate)

    const report: ReportHistory = {
      id: `rep-${Date.now()}`,
      name: generation.reportName,
      type: template?.name || 'Custom Report',
      period: generation.period,
      generatedDate: new Date().toISOString(),
      format: generation.format,
      size: `${(Math.random() * 5 + 0.5).toFixed(1)} MB`,
      status: 'Completed',
      generatedBy: user?.name || 'Unknown',
      downloadUrl: '#',
    }

    completeGeneration(report)
    setLocalGenerating(false)
    setNotification(`Report "${report.name}" generated successfully!`)
  }

  const selectedTemplate = templates.find((t) => t.id === generation.selectedTemplate)

  if (generation.result && !localGenerating) {
    return (
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4">
            <Check size={32} className="text-green-600" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Report Generated Successfully</h1>
          <p className="text-gray-500 mt-2">Your report is ready for download</p>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-gray-500">Report Name</p>
              <p className="font-medium text-gray-900">{generation.result.name}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Type</p>
              <p className="font-medium text-gray-900">{generation.result.type}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Period</p>
              <p className="font-medium text-gray-900">{generation.result.period}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Format</p>
              <p className="font-medium text-gray-900">{generation.result.format}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Size</p>
              <p className="font-medium text-gray-900">{generation.result.size}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Generated By</p>
              <p className="font-medium text-gray-900">{generation.result.generatedBy}</p>
            </div>
          </div>
        </div>

        <div className="flex items-center justify-center gap-3">
          <button
            onClick={() => {
              resetGeneration()
            }}
            className="flex items-center gap-2 px-4 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg font-medium transition-colors"
          >
            <RotateCcw size={18} />
            Generate Another
          </button>
          <button className="flex items-center gap-2 px-4 py-2.5 bg-amber-600 hover:bg-amber-700 text-white rounded-lg font-medium transition-colors">
            <Download size={18} />
            Download Report
          </button>
          <button
            onClick={() => navigate('/history')}
            className="px-4 py-2.5 text-amber-600 hover:bg-amber-50 rounded-lg font-medium transition-colors"
          >
            View in History
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Generate Report</h1>
        <p className="text-gray-500 mt-1">Create a new financial report in 4 easy steps</p>
      </div>

      <div className="flex items-center gap-1">
        {STEPS.map((label, i) => (
          <div key={label} className="flex-1 flex items-center">
            <div
              className={cn(
                'flex items-center justify-center w-8 h-8 rounded-full text-sm font-medium shrink-0',
                generation.step > i + 1
                  ? 'bg-amber-600 text-white'
                  : generation.step === i + 1
                  ? 'bg-amber-600 text-white'
                  : 'bg-gray-200 text-gray-500'
              )}
            >
              {generation.step > i + 1 ? <Check size={16} /> : i + 1}
            </div>
            <span
              className={cn(
                'hidden sm:block ml-2 text-xs font-medium',
                generation.step >= i + 1 ? 'text-amber-700' : 'text-gray-400'
              )}
            >
              {label}
            </span>
            {i < STEPS.length - 1 && (
              <div
                className={cn(
                  'flex-1 h-0.5 mx-2',
                  generation.step > i + 1 ? 'bg-amber-600' : 'bg-gray-200'
                )}
              />
            )}
          </div>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-gray-200 p-6">
        {generation.step === 1 && (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Select a Template</h2>
            <div className="grid grid-cols-2 gap-3">
              {templates.map((template) => {
                const Icon = ICON_MAP[template.icon] || FileText
                return (
                  <button
                    key={template.id}
                    onClick={() => setGenerationField('selectedTemplate', template.id)}
                    className={cn(
                      'flex items-center gap-3 p-4 rounded-lg border-2 text-left transition-all',
                      generation.selectedTemplate === template.id
                        ? 'border-amber-500 bg-amber-50'
                        : 'border-gray-200 hover:border-amber-300'
                    )}
                  >
                    <div className="p-2 bg-amber-50 rounded-lg">
                      <Icon size={20} className="text-amber-600" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-900 text-sm">{template.name}</p>
                      <p className="text-xs text-gray-500 line-clamp-1">{template.description}</p>
                    </div>
                  </button>
                )
              })}
            </div>
          </div>
        )}

        {generation.step === 2 && (
          <div className="space-y-5">
            <h2 className="text-lg font-semibold text-gray-900">Configure Report</h2>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Report Name</label>
              <input
                type="text"
                value={generation.reportName}
                onChange={(e) => setGenerationField('reportName', e.target.value)}
                placeholder="e.g., Q1 2026 P&L Consolidated"
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Reporting Period</label>
              <input
                type="text"
                value={generation.period}
                onChange={(e) => setGenerationField('period', e.target.value)}
                placeholder="e.g., Q1 2026, March 2026"
                className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Countries</label>
              <div className="flex flex-wrap gap-2">
                {COUNTRIES.map((country) => (
                  <button
                    key={country}
                    onClick={() => {
                      const next = generation.countries.includes(country)
                        ? generation.countries.filter((c) => c !== country)
                        : [...generation.countries, country]
                      setGenerationField('countries', next)
                    }}
                    className={cn(
                      'px-3 py-1.5 text-sm rounded-lg border transition-colors',
                      generation.countries.includes(country)
                        ? 'bg-amber-50 border-amber-400 text-amber-700'
                        : 'border-gray-200 text-gray-600 hover:border-amber-300'
                    )}
                  >
                    {country}
                  </button>
                ))}
              </div>
            </div>
            {selectedTemplate && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Sections</label>
                <div className="flex flex-wrap gap-2">
                  {selectedTemplate.sections.map((section) => (
                    <button
                      key={section}
                      onClick={() => {
                        const next = generation.sections.includes(section)
                          ? generation.sections.filter((s) => s !== section)
                          : [...generation.sections, section]
                        setGenerationField('sections', next)
                      }}
                      className={cn(
                        'px-3 py-1.5 text-sm rounded-lg border transition-colors',
                        generation.sections.includes(section)
                          ? 'bg-amber-50 border-amber-400 text-amber-700'
                          : 'border-gray-200 text-gray-600 hover:border-amber-300'
                      )}
                    >
                      {section}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {generation.step === 3 && (
          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Select Output Format</h2>
            <div className="grid grid-cols-3 gap-4">
              {(['PDF', 'Excel', 'CSV'] as const).map((fmt) => (
                <button
                  key={fmt}
                  onClick={() => setGenerationField('format', fmt)}
                  className={cn(
                    'p-6 rounded-xl border-2 text-center transition-all',
                    generation.format === fmt
                      ? 'border-amber-500 bg-amber-50'
                      : 'border-gray-200 hover:border-amber-300'
                  )}
                >
                  <p className="text-2xl font-bold text-gray-900">{fmt === 'PDF' ? '📄' : fmt === 'Excel' ? '📊' : '📋'}</p>
                  <p className="font-semibold text-gray-900 mt-2">{fmt}</p>
                  <p className="text-xs text-gray-500 mt-1">
                    {fmt === 'PDF'
                      ? 'Print-ready document'
                      : fmt === 'Excel'
                      ? 'Editable spreadsheet'
                      : 'Raw data export'}
                  </p>
                </button>
              ))}
            </div>
          </div>
        )}

        {generation.step === 4 && (
          <div className="space-y-5">
            <h2 className="text-lg font-semibold text-gray-900">Review & Generate</h2>

            {localGenerating && (
              <div className="space-y-2">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-600">Generating report...</span>
                  <span className="text-amber-600 font-medium">{generation.progress}%</span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2.5">
                  <div
                    className="bg-amber-600 h-2.5 rounded-full transition-all duration-200"
                    style={{ width: `${generation.progress}%` }}
                  />
                </div>
              </div>
            )}

            {!localGenerating && (
              <>
                <div className="bg-gray-50 rounded-lg p-4 space-y-3">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-xs text-gray-500">Report Name</p>
                      <p className="font-medium text-gray-900">{generation.reportName || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Template</p>
                      <p className="font-medium text-gray-900">{selectedTemplate?.name || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Period</p>
                      <p className="font-medium text-gray-900">{generation.period || '—'}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500">Format</p>
                      <p className="font-medium text-gray-900">{generation.format}</p>
                    </div>
                  </div>
                  {generation.countries.length > 0 && (
                    <div>
                      <p className="text-xs text-gray-500">Countries</p>
                      <div className="flex flex-wrap gap-1 mt-1">
                        {generation.countries.map((c) => (
                          <span key={c} className="text-xs bg-white border border-gray-200 px-2 py-0.5 rounded">
                            {c}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {generation.sections.length > 0 && (
                    <div>
                      <p className="text-xs text-gray-500">Sections</p>
                      <div className="flex flex-wrap gap-1 mt-1">
                        {generation.sections.map((s) => (
                          <span key={s} className="text-xs bg-white border border-gray-200 px-2 py-0.5 rounded">
                            {s}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </>
            )}
          </div>
        )}
      </div>

      <div className="flex items-center justify-between">
        <button
          onClick={() => setGenerationStep(generation.step - 1)}
          disabled={generation.step === 1}
          className={cn(
            'flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-colors',
            generation.step === 1
              ? 'text-gray-300 cursor-not-allowed'
              : 'text-gray-700 bg-gray-100 hover:bg-gray-200'
          )}
        >
          <ChevronLeft size={18} />
          Back
        </button>

        {generation.step < 4 ? (
          <button
            onClick={() => setGenerationStep(generation.step + 1)}
            disabled={!canProceed()}
            className={cn(
              'flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-colors',
              canProceed()
                ? 'bg-amber-600 hover:bg-amber-700 text-white'
                : 'bg-amber-300 text-amber-100 cursor-not-allowed'
            )}
          >
            Next
            <ChevronRight size={18} />
          </button>
        ) : (
          <button
            onClick={handleGenerate}
            disabled={localGenerating}
            className={cn(
              'flex items-center gap-2 px-6 py-2.5 rounded-lg font-medium transition-colors',
              localGenerating
                ? 'bg-amber-400 text-white cursor-not-allowed'
                : 'bg-amber-600 hover:bg-amber-700 text-white'
            )}
          >
            {localGenerating ? (
              <>
                <Loader2 size={18} className="animate-spin" />
                Generating...
              </>
            ) : (
              <>
                Generate Report
                <Check size={18} />
              </>
            )}
          </button>
        )}
      </div>
    </div>
  )
}
