apiVersion: v1
kind: Service
metadata:
  name: ai-data-processing-service
  namespace: ai-services
  labels:
    app: ai-data-processing-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-data-processing-service
  ports:
  - name: http
    port: 8241
    targetPort: 8241
    protocol: TCP
