// Mock Data for Development

import type {
  GlobalDashboardSummary,
  CountrySummary,
  CountryInfo,
  GlobalTopPerformer,
  MajorDeal,
  GlobalAlert,
  ForecastSummary,
  CountryComparison,
  GlobalPipelineSummary,
  GlobalPerformanceData,
  GlobalSalesForecast,
  Report,
  GlobalPartnersSummary,
  PartnerApplication,
  SalesTeamPartner,
} from '@domain/types';

// Mock Country Data
export const mockCountries: CountryInfo[] = [
  {
    code: 'NG',
    name: 'Nigeria',
    flag: '\uD83C\uDDF3\uD83C\uDDEC',
    currency: 'NGN',
    region: 'West Africa',
    directorId: 'usr-001',
    directorName: 'John Doe',
  },
  {
    code: 'KE',
    name: 'Kenya',
    flag: '\uD83C\uDDF0\uD83C\uDDEA',
    currency: 'KES',
    region: 'East Africa',
    directorId: 'usr-002',
    directorName: 'Jane Smith',
  },
  {
    code: 'GH',
    name: 'Ghana',
    flag: '\uD83C\uDDEC\uD83C\uDDED',
    currency: 'GHS',
    region: 'West Africa',
    directorId: 'usr-003',
    directorName: 'Bob Johnson',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    flag: '\uD83C\uDDFF\uD83C\uDDE6',
    currency: 'ZAR',
    region: 'Southern Africa',
    directorId: 'usr-004',
    directorName: 'Sarah Williams',
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    flag: '\uD83C\uDDEA\uD83C\uDDF9',
    currency: 'ETB',
    region: 'East Africa',
    directorId: 'usr-005',
    directorName: 'Michael Chen',
  },
  {
    code: 'UG',
    name: 'Uganda',
    flag: '\uD83C\uDDFA\uD83C\uDDEC',
    currency: 'UGX',
    region: 'East Africa',
    directorId: 'usr-006',
    directorName: 'Grace Amani',
  },
];

// Mock Country Summaries
export const mockCountrySummaries: CountrySummary[] = [
  {
    country: mockCountries[0],
    metrics: {
      revenue: 1200000,
      quota: 1300000,
      attainment: 92,
      dealsClosed: 245,
      pipelineValue: 3500000,
      winRate: 32,
      growth: 12,
    },
    trend: 'up',
    status: 'on_track',
  },
  {
    country: mockCountries[1],
    metrics: {
      revenue: 950000,
      quota: 900000,
      attainment: 106,
      dealsClosed: 189,
      pipelineValue: 2800000,
      winRate: 35,
      growth: 15,
    },
    trend: 'up',
    status: 'on_track',
  },
  {
    country: mockCountries[2],
    metrics: {
      revenue: 780000,
      quota: 850000,
      attainment: 92,
      dealsClosed: 156,
      pipelineValue: 2100000,
      winRate: 28,
      growth: 8,
    },
    trend: 'up',
    status: 'on_track',
  },
  {
    country: mockCountries[3],
    metrics: {
      revenue: 2100000,
      quota: 2000000,
      attainment: 105,
      dealsClosed: 312,
      pipelineValue: 4200000,
      winRate: 38,
      growth: 18,
    },
    trend: 'up',
    status: 'on_track',
  },
  {
    country: mockCountries[4],
    metrics: {
      revenue: 650000,
      quota: 700000,
      attainment: 93,
      dealsClosed: 98,
      pipelineValue: 1800000,
      winRate: 30,
      growth: 5,
    },
    trend: 'neutral',
    status: 'at_risk',
  },
  {
    country: mockCountries[5],
    metrics: {
      revenue: 420000,
      quota: 450000,
      attainment: 93,
      dealsClosed: 78,
      pipelineValue: 1200000,
      winRate: 29,
      growth: 10,
    },
    trend: 'up',
    status: 'on_track',
  },
];

// Mock Top Performers
export const mockTopPerformers: GlobalTopPerformer[] = [
  {
    userId: 'usr-101',
    name: 'Sarah Williams',
    avatar: 'https://i.pravatar.cc/150?img=1',
    country: mockCountries[3],
    department: 'Enterprise',
    revenue: 280000,
    quota: 200000,
    attainment: 140,
    dealsClosed: 35,
    rank: 1,
  },
  {
    userId: 'usr-102',
    name: 'John Doe',
    avatar: 'https://i.pravatar.cc/150?img=2',
    country: mockCountries[0],
    department: 'Enterprise',
    revenue: 250000,
    quota: 200000,
    attainment: 125,
    dealsClosed: 28,
    rank: 2,
  },
  {
    userId: 'usr-103',
    name: 'Jane Smith',
    avatar: 'https://i.pravatar.cc/150?img=3',
    country: mockCountries[1],
    department: 'SMB',
    revenue: 180000,
    quota: 150000,
    attainment: 120,
    dealsClosed: 42,
    rank: 3,
  },
  {
    userId: 'usr-104',
    name: 'Bob Johnson',
    avatar: 'https://i.pravatar.cc/150?img=4',
    country: mockCountries[2],
    department: 'Retail',
    revenue: 145000,
    quota: 150000,
    attainment: 97,
    dealsClosed: 38,
    rank: 4,
  },
  {
    userId: 'usr-105',
    name: 'Michael Chen',
    avatar: 'https://i.pravatar.cc/150?img=5',
    country: mockCountries[4],
    department: 'Enterprise',
    revenue: 135000,
    quota: 140000,
    attainment: 96,
    dealsClosed: 22,
    rank: 5,
  },
];

// Mock Major Deals
export const mockMajorDeals: MajorDeal[] = [
  {
    id: 'deal-5001',
    dealNumber: 'D-5001',
    name: 'Global Corp Enterprise Deal',
    company: 'Global Corporation Nigeria',
    country: mockCountries[0],
    value: 500000,
    currency: 'USD',
    stage: 'Negotiating',
    probability: 75,
    expectedCloseDate: new Date('2025-02-15'),
    owner: { id: 'usr-001', name: 'John Doe', country: 'NG' },
    isMajor: true,
  },
  {
    id: 'deal-5002',
    dealNumber: 'D-5002',
    name: 'TechPrime Africa Deal',
    company: 'TechPrime South Africa',
    country: mockCountries[3],
    value: 350000,
    currency: 'USD',
    stage: 'Proposal',
    probability: 50,
    expectedCloseDate: new Date('2025-02-20'),
    owner: { id: 'usr-004', name: 'Sarah Williams', country: 'ZA' },
    isMajor: true,
  },
  {
    id: 'deal-5003',
    dealNumber: 'D-5003',
    name: 'MegaTrade Expansion',
    company: 'MegaTrade Kenya',
    country: mockCountries[1],
    value: 280000,
    currency: 'USD',
    stage: 'Negotiating',
    probability: 70,
    expectedCloseDate: new Date('2025-02-18'),
    owner: { id: 'usr-002', name: 'Jane Smith', country: 'KE' },
    isMajor: true,
  },
  {
    id: 'deal-5004',
    dealNumber: 'D-5004',
    name: 'Prime Group Logistics',
    company: 'Prime Group Nigeria',
    country: mockCountries[0],
    value: 250000,
    currency: 'USD',
    stage: 'Proposal',
    probability: 60,
    expectedCloseDate: new Date('2025-02-25'),
    owner: { id: 'usr-001', name: 'John Doe', country: 'NG' },
    isMajor: true,
  },
  {
    id: 'deal-5005',
    dealNumber: 'D-5005',
    name: 'EliteCorp SA',
    company: 'Elite Corporation South Africa',
    country: mockCountries[3],
    value: 200000,
    currency: 'USD',
    stage: 'Qualified',
    probability: 40,
    expectedCloseDate: new Date('2025-03-01'),
    owner: { id: 'usr-004', name: 'Sarah Williams', country: 'ZA' },
    isMajor: true,
  },
];

// Mock Alerts
export const mockAlerts: GlobalAlert[] = [
  {
    id: 'alert-001',
    type: 'warning',
    category: 'quota',
    title: 'Countries Below Quota',
    message: '2 countries are below 80% quota attainment',
    affectedCountries: [mockCountries[2], mockCountries[4]],
    severity: 'medium',
    actionUrl: '/countries?filter=below_quota',
    createdAt: new Date(),
  },
  {
    id: 'alert-002',
    type: 'info',
    category: 'deal',
    title: 'Major Deals Closing',
    message: '12 major deals expected to close this week',
    severity: 'low',
    actionUrl: '/pipeline?filter=major_deals',
    createdAt: new Date(),
  },
  {
    id: 'alert-003',
    type: 'success',
    category: 'forecast',
    title: 'Forecast Achievement',
    message: 'Q1 forecast exceeded by 15%',
    severity: 'low',
    createdAt: new Date(),
  },
];

// Mock Global Dashboard Summary
export const mockGlobalDashboardSummary: GlobalDashboardSummary = {
  period: {
    start: new Date('2025-02-01'),
    end: new Date('2025-02-28'),
    type: 'monthly',
  },
  globalMetrics: {
    revenue: {
      value: 8500000,
      label: '$8.5M',
      change: 15,
      changeType: 'increase',
      target: 8500000,
      attainment: 100,
      currency: 'USD',
    },
    pipelineValue: {
      value: 25000000,
      label: '$25M',
      change: 12,
      changeType: 'increase',
      currency: 'USD',
    },
    dealsClosed: {
      value: 1245,
      label: '1,245',
      change: 18,
      changeType: 'increase',
    },
    activeDeals: {
      value: 4892,
      label: '4,892',
      change: 8,
      changeType: 'increase',
    },
    winRate: {
      value: 34,
      label: '34%',
      change: 2,
      changeType: 'increase',
    },
    avgDealSize: {
      value: 6827,
      label: '$6,827',
      change: -3,
      changeType: 'decrease',
      currency: 'USD',
    },
  },
  countriesSummary: mockCountrySummaries,
  topPerformers: mockTopPerformers,
  majorDeals: mockMajorDeals,
  alerts: mockAlerts,
  forecastSummary: {
    period: 'Q1 2025',
    forecast: 10500000,
    bestCase: 12800000,
    worstCase: 8200000,
    weightedPipeline: 25000000,
    currency: 'USD',
    accuracy: 94.2,
  },
};

// Mock Country Comparison
export const mockCountryComparison: CountryComparison = {
  countries: [mockCountries[0], mockCountries[1], mockCountries[2], mockCountries[3]],
  metrics: [
    {
      key: 'revenue',
      label: 'Revenue',
      format: 'currency',
      values: {
        NG: { value: 1200000, display: '$1.2M', rank: 2, vsTarget: 92, vsPrevious: 12 },
        KE: { value: 950000, display: '$950K', rank: 3, vsTarget: 106, vsPrevious: 15 },
        GH: { value: 780000, display: '$780K', rank: 4, vsTarget: 88, vsPrevious: 8 },
        ZA: { value: 2100000, display: '$2.1M', rank: 1, vsTarget: 105, vsPrevious: 18 },
      },
      trend: {
        NG: 'up',
        KE: 'up',
        GH: 'up',
        ZA: 'up',
      },
    },
    {
      key: 'quotaAttainment',
      label: 'Quota Attainment',
      format: 'percentage',
      values: {
        NG: { value: 92, display: '92%', rank: 3 },
        KE: { value: 106, display: '106%', rank: 2 },
        GH: { value: 88, display: '88%', rank: 4 },
        ZA: { value: 105, display: '105%', rank: 1 },
      },
    },
  ],
  rankings: [
    {
      category: 'revenue',
      rankings: [
        { rank: 1, country: mockCountries[3], value: 2100000, display: '$2.1M', change: 18 },
        { rank: 2, country: mockCountries[0], value: 1200000, display: '$1.2M', change: 12 },
        { rank: 3, country: mockCountries[1], value: 950000, display: '$950K', change: 15 },
      ],
    },
  ],
  period: {
    start: new Date('2025-02-01'),
    end: new Date('2025-02-28'),
    type: 'monthly',
  },
};

// Mock Pipeline Summary
export const mockPipelineSummary: GlobalPipelineSummary = {
  totalValue: 26000000,
  totalDeals: 983,
  weightedValue: 6700000,
  avgDealSize: 26449,
  byCountry: [
    {
      country: mockCountries[0],
      totalValue: 3500000,
      dealCount: 287,
      weightedValue: 1800000,
      avgDealSize: 12194,
      stageDistribution: { New: 45, Qualified: 68, Proposal: 52, Negotiating: 62, Closing: 60 },
      trend: 'up',
    },
    {
      country: mockCountries[1],
      totalValue: 2800000,
      dealCount: 198,
      weightedValue: 1400000,
      avgDealSize: 14141,
      stageDistribution: { New: 35, Qualified: 52, Proposal: 45, Negotiating: 38, Closing: 28 },
      trend: 'up',
    },
    {
      country: mockCountries[2],
      totalValue: 2100000,
      dealCount: 156,
      weightedValue: 1000000,
      avgDealSize: 13462,
      stageDistribution: { New: 28, Qualified: 42, Proposal: 32, Negotiating: 30, Closing: 24 },
      trend: 'neutral',
    },
    {
      country: mockCountries[3],
      totalValue: 4200000,
      dealCount: 342,
      weightedValue: 2500000,
      avgDealSize: 12281,
      stageDistribution: { New: 48, Qualified: 89, Proposal: 72, Negotiating: 78, Closing: 55 },
      trend: 'up',
    },
  ],
  byStage: [
    { stage: 'New', count: 156, totalValue: 780000, weightedValue: 0, percentage: 6, avgDaysInStage: 0 },
    { stage: 'Qualified', count: 287, totalValue: 2800000, weightedValue: 560000, percentage: 22, avgDaysInStage: 18 },
    { stage: 'Proposal', count: 245, totalValue: 4200000, weightedValue: 2100000, percentage: 33, avgDaysInStage: 35 },
    { stage: 'Negotiating', count: 198, totalValue: 3500000, weightedValue: 2600000, percentage: 28, avgDaysInStage: 15 },
    { stage: 'Closing', count: 97, totalValue: 1400000, weightedValue: 1300000, percentage: 11, avgDaysInStage: 5 },
  ],
  majorDeals: mockMajorDeals,
  velocity: {
    avgDaysInStage: { New: 0, Qualified: 18, Proposal: 35, Negotiating: 15, Closing: 5 },
    overallCycle: 96,
    cycleTarget: 90,
    cycleVariance: 6,
  },
};

// Mock Reports
export const mockReports: Report[] = [
  {
    id: 'rep-001',
    name: 'Monthly Executive Dashboard',
    description: 'Executive summary of global sales performance',
    type: 'EXECUTIVE_DASHBOARD',
    category: 'EXECUTIVE',
    createdBy: 'usr-001',
    createdAt: new Date('2025-01-15'),
    lastRunAt: new Date('2025-02-01'),
    schedule: {
      frequency: 'monthly',
      dayOfMonth: 1,
      time: '09:00',
      recipients: ['ceo@company.com', 'vp-sales@company.com'],
      active: true,
      nextRunAt: new Date('2025-03-01'),
    },
    config: {
      metrics: ['revenue', 'pipeline', 'deals', 'winRate'],
      countries: [],
      period: {
        start: new Date('2025-02-01'),
        end: new Date('2025-02-28'),
        type: 'monthly',
      },
      visualizations: [
        { type: 'number', title: 'Global Revenue', dataSource: 'revenue', config: {} },
        { type: 'bar', title: 'Revenue by Country', dataSource: 'countries', config: {} },
      ],
      exportFormat: 'PDF',
    },
  },
  {
    id: 'rep-002',
    name: 'Country Comparison Report',
    description: 'Compare performance across countries',
    type: 'COUNTRY_COMPARISON',
    category: 'COUNTRY',
    createdBy: 'usr-002',
    createdAt: new Date('2025-01-20'),
    config: {
      metrics: ['revenue', 'quota', 'deals', 'winRate'],
      countries: ['NG', 'KE', 'GH', 'ZA'],
      period: {
        start: new Date('2025-02-01'),
        end: new Date('2025-02-28'),
        type: 'monthly',
      },
      visualizations: [],
      exportFormat: 'EXCEL',
    },
  },
];

// Mock Partners Summary
export const mockPartnersSummary: GlobalPartnersSummary = {
  period: {
    start: new Date('2025-02-01'),
    end: new Date('2025-02-28'),
    type: 'monthly',
  },
  totalPartners: 1245,
  activePartners: 1180,
  pendingApplications: 18,
  byCountry: [
    {
      country: mockCountries[0],
      totalPartners: 342,
      activePartners: 325,
      pipelineValue: 8500000,
      commissionPaid: 2800000,
      tierBreakdown: { BRONZE: 150, SILVER: 120, GOLD: 60, PLATINUM: 12 },
    },
    {
      country: mockCountries[1],
      totalPartners: 198,
      activePartners: 190,
      pipelineValue: 5200000,
      commissionPaid: 1500000,
      tierBreakdown: { BRONZE: 90, SILVER: 70, GOLD: 35, PLATINUM: 3 },
    },
    {
      country: mockCountries[2],
      totalPartners: 145,
      activePartners: 138,
      pipelineValue: 3800000,
      commissionPaid: 980000,
      tierBreakdown: { BRONZE: 70, SILVER: 50, GOLD: 20, PLATINUM: 5 },
    },
    {
      country: mockCountries[3],
      totalPartners: 278,
      activePartners: 265,
      pipelineValue: 7200000,
      commissionPaid: 2100000,
      tierBreakdown: { BRONZE: 120, SILVER: 100, GOLD: 50, PLATINUM: 8 },
    },
  ],
  byPartnerType: [
    { partnerType: 'COURIER', count: 245, pipelineValue: 4500000, revenueGenerated: 1200000, avgCommission: 4500 },
    { partnerType: 'WAREHOUSE', count: 189, pipelineValue: 3200000, revenueGenerated: 980000, avgCommission: 5200 },
    { partnerType: 'ECOMMERCE', count: 312, pipelineValue: 5800000, revenueGenerated: 1800000, avgCommission: 5800 },
    { partnerType: 'HAULAGE', count: 156, pipelineValue: 2800000, revenueGenerated: 720000, avgCommission: 4600 },
  ],
  byTier: [
    { tier: 'BRONZE', count: 399, revenueThreshold: 0, partnersAtTier: 399 },
    { tier: 'SILVER', count: 567, revenueThreshold: 500000, partnersAtTier: 567 },
    { tier: 'GOLD', count: 234, revenueThreshold: 2000000, partnersAtTier: 234 },
    { tier: 'PLATINUM', count: 45, revenueThreshold: 5000000, partnersAtTier: 45 },
  ],
  topPerformers: [
    {
      partnerId: 'p-001',
      name: 'John Okafor',
      partnerType: 'ECOMMERCE',
      tier: 'PLATINUM',
      country: mockCountries[0],
      pipelineValue: 250000,
      commissionEarned: 45000,
      partnersRecruited: 12,
      customersAcquired: 35,
      rank: 1,
    },
    {
      partnerId: 'p-002',
      name: 'Sarah Wanjiku',
      partnerType: 'WAREHOUSE',
      tier: 'GOLD',
      country: mockCountries[1],
      pipelineValue: 180000,
      commissionEarned: 32000,
      partnersRecruited: 8,
      customersAcquired: 28,
      rank: 2,
    },
  ],
  recentApplications: [],
  commissionStats: {
    totalEarned: 8500000,
    totalPaid: 6200000,
    totalPending: 2300000,
    avgPayoutTime: 5,
  },
};

// Mock Partner Applications
export const mockPartnerApplications: PartnerApplication[] = [
  {
    id: 'app-001',
    applicationNumber: 'PA-2025-001',
    applicant: {
      firstName: 'Emeka',
      lastName: 'Okonkwo',
      email: 'emeka.okonkwo@email.com',
      phone: '+234 801 234 5678',
      address: {
        street: '123 Adetokunbo Ademola Street',
        city: 'Lagos',
        state: 'Lagos',
        postalCode: '101241',
        country: 'Nigeria',
      },
    },
    partnerType: 'COURIER',
    preferredCountry: mockCountries[0],
    preferredTerritory: 'Lagos Mainland',
    documents: [],
    backgroundCheck: {
      status: 'CLEARED',
      completedAt: new Date('2025-02-10'),
    },
    status: 'PENDING',
    createdAt: new Date('2025-02-08'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'app-002',
    applicationNumber: 'PA-2025-002',
    applicant: {
      firstName: 'Wanjiku',
      lastName: 'Kamau',
      email: 'wanjiku.k@email.com',
      phone: '+254 712 345 678',
      address: {
        street: '45 Ngong Road',
        city: 'Nairobi',
        state: 'Nairobi',
        postalCode: '00100',
        country: 'Kenya',
      },
    },
    partnerType: 'WAREHOUSE',
    preferredCountry: mockCountries[1],
    preferredTerritory: 'Nairobi West',
    documents: [],
    backgroundCheck: {
      status: 'CLEARED',
      completedAt: new Date('2025-02-09'),
    },
    status: 'PENDING',
    createdAt: new Date('2025-02-07'),
    updatedAt: new Date('2025-02-09'),
  },
  {
    id: 'app-003',
    applicationNumber: 'PA-2025-003',
    applicant: {
      firstName: 'Kwame',
      lastName: 'Mensah',
      email: 'kwame.mensah@email.com',
      phone: '+233 24 123 4567',
      address: {
        street: '78 Liberation Road',
        city: 'Accra',
        state: 'Greater Accra',
        postalCode: '00233',
        country: 'Ghana',
      },
    },
    partnerType: 'ECOMMERCE',
    preferredCountry: mockCountries[2],
    preferredTerritory: 'Accra Central',
    documents: [],
    backgroundCheck: {
      status: 'PENDING',
    },
    status: 'PENDING',
    createdAt: new Date('2025-02-18'),
    updatedAt: new Date('2025-02-18'),
  },
];

// Mock Sales Team Partners
export const mockPartners: SalesTeamPartner[] = [
  {
    id: 'p-001',
    partnerNumber: 'SP-2025-001',
    userId: 'usr-p001',
    user: {
      firstName: 'John',
      lastName: 'Okafor',
      email: 'john.okafor@email.com',
      phone: '+234 801 234 5678',
      avatar: 'https://i.pravatar.cc/150?img=10',
    },
    partnerType: 'ECOMMERCE',
    assignedCountry: mockCountries[0],
    territory: {
      id: 't-001',
      name: 'Lagos Mainland',
      code: 'LM',
      country: 'NG',
    },
    status: 'ACTIVE',
    tier: 'PLATINUM',
    partnersRecruited: 12,
    customersAcquired: 35,
    pipelineValue: 250000,
    revenueGenerated: 450000,
    commissionEarned: 45000,
    referralBonusEarned: 12000,
    tierProgression: {
      currentTier: 'PLATINUM',
      currentTierRevenue: 5800000,
      revenueToNextTier: 0,
    },
    leadConversionRate: 35,
    avgDealSize: 12857,
    activeDeals: 15,
    assignedLeads: [],
    approvedAt: new Date('2024-06-15'),
    approvedBy: 'usr-001',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2025-02-18'),
    lastActivityAt: new Date('2025-02-17'),
  },
  {
    id: 'p-002',
    partnerNumber: 'SP-2025-002',
    userId: 'usr-p002',
    user: {
      firstName: 'Sarah',
      lastName: 'Wanjiku',
      email: 'sarah.wanjiku@email.com',
      phone: '+254 712 345 678',
      avatar: 'https://i.pravatar.cc/150?img=11',
    },
    partnerType: 'WAREHOUSE',
    assignedCountry: mockCountries[1],
    territory: {
      id: 't-002',
      name: 'Nairobi West',
      code: 'NW',
      country: 'KE',
    },
    status: 'ACTIVE',
    tier: 'GOLD',
    partnersRecruited: 8,
    customersAcquired: 28,
    pipelineValue: 180000,
    revenueGenerated: 320000,
    commissionEarned: 32000,
    referralBonusEarned: 8000,
    tierProgression: {
      currentTier: 'GOLD',
      currentTierRevenue: 2800000,
      nextTier: 'PLATINUM',
      nextTierRevenue: 5000000,
      revenueToNextTier: 2200000,
      estimatedTimeToNextTier: 45,
    },
    leadConversionRate: 42,
    avgDealSize: 11429,
    activeDeals: 12,
    assignedLeads: [],
    approvedAt: new Date('2024-08-20'),
    approvedBy: 'usr-002',
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2025-02-16'),
    lastActivityAt: new Date('2025-02-16'),
  },
];

// Mock Forecast
export const mockForecast: GlobalSalesForecast = {
  id: 'fcast-001',
  name: 'Q1 2025 Forecast',
  period: {
    type: 'quarterly',
    start: new Date('2025-01-01'),
    end: new Date('2025-03-31'),
    label: 'Q1 2025',
  },
  scenario: 'likely',
  generatedAt: new Date('2025-02-01'),
  generatedBy: 'usr-001',
  global: {
    forecast: 10500000,
    bestCase: 12800000,
    worstCase: 8200000,
    currency: 'USD',
    confidence: 85,
  },
  byCountry: [
    {
      country: mockCountries[0],
      forecast: 1800000,
      bestCase: 2200000,
      worstCase: 1400000,
      pipeline: 3500000,
      contribution: 17,
      trend: 'up',
      riskLevel: 'low',
    },
    {
      country: mockCountries[1],
      forecast: 1200000,
      bestCase: 1500000,
      worstCase: 950000,
      pipeline: 2800000,
      contribution: 11,
      trend: 'up',
      riskLevel: 'medium',
    },
    {
      country: mockCountries[2],
      forecast: 950000,
      bestCase: 1200000,
      worstCase: 750000,
      pipeline: 2100000,
      contribution: 9,
      trend: 'neutral',
      riskLevel: 'medium',
    },
    {
      country: mockCountries[3],
      forecast: 3500000,
      bestCase: 4200000,
      worstCase: 2800000,
      pipeline: 4200000,
      contribution: 33,
      trend: 'up',
      riskLevel: 'low',
    },
  ],
  byStage: [
    { stage: 'Qualified', count: 287, value: 2800000, weightedValue: 560000, probability: 20, contribution: 17 },
    { stage: 'Proposal', count: 245, value: 4200000, weightedValue: 2100000, probability: 50, contribution: 40 },
    { stage: 'Negotiating', count: 198, value: 3500000, weightedValue: 2600000, probability: 75, contribution: 33 },
    { stage: 'Closing', count: 97, value: 1400000, weightedValue: 1300000, probability: 90, contribution: 10 },
  ],
  accuracyMetrics: [
    { period: 'Q4 2024', accuracy: 94.2, variance: -3.5, variancePercentage: -3.8, actualRevenue: 10150000, forecastedRevenue: 10500000 },
    { period: 'Q3 2024', accuracy: 91.5, variance: 5.2, variancePercentage: 5.7, actualRevenue: 9650000, forecastedRevenue: 9180000 },
  ],
  trends: [
    { period: 'Nov 2024', actual: 3200000, forecast: 3100000, scenario: 'likely' },
    { period: 'Dec 2024', actual: 3500000, forecast: 3400000, scenario: 'likely' },
    { period: 'Jan 2025', actual: 3400000, forecast: 3300000, scenario: 'likely' },
    { period: 'Feb 2025', forecast: 3500000, bestCase: 3800000, worstCase: 3200000, scenario: 'likely' },
    { period: 'Mar 2025', forecast: 3800000, bestCase: 4200000, worstCase: 3400000, scenario: 'likely' },
  ],
};
