apiVersion: v1
kind: Secret
metadata:
  name: universal-tracking-service-secrets
  namespace: universal-tracking-services
  labels:
    app: universal-tracking-service
    team: team-c-universal-tracking
type: Opaque
stringData:
  database-username: "universal_tracking_user"
  database-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
