apiVersion: v1
kind: Service
metadata:
  name: ai-churn-prediction-service
  namespace: ai-services
  labels:
    app: ai-churn-prediction-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-churn-prediction-service
  ports:
  - name: http
    port: 8210
    targetPort: 8210
    protocol: TCP
