apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-document-processing-service
  namespace: ai-services
  labels:
    app: ai-document-processing-service
    version: v1
    team: team-ai-content-processing
    domain: ai-services
    component: content-document-processing
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-document-processing-service
