apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-sales-forecastation-service
  namespace: ai-services
  labels:
    app: ai-sales-forecastation-service
    team: team-f-ai-services
spec:
  selector:
    matchLabels:
      app: ai-sales-forecastation-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
