apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-feature-extraction-service-pdb
  namespace: ai-services
  labels:
    app: ai-feature-extraction-service
    team: team-ai-mlops
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-feature-extraction-service
