apiVersion: v1
kind: Service
metadata:
  name: ai-feature-extraction-service
  namespace: ai-services
  labels:
    app: ai-feature-extraction-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-feature-extraction-service
  ports:
  - name: http
    port: 8250
    targetPort: 8250
    protocol: TCP
