apiVersion: v1
kind: Secret
metadata:
  name: time-series-forecasting-service-secrets
  namespace: ai-services
  labels:
    app: time-series-forecasting-service
    team: team-f-ai-services
type: Opaque
stringData:
  mongodb-user: "time-series-forecasting-service_user"
  mongodb-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
