package com.gogidix.shared.warehousing.expiration.domain.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * Expiry Report Entity - Multi-tenant with MongoDB
 *
 * Generated reports for expiration tracking and analysis
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "expiry_reports")
@CompoundIndex(def = "{'tenantId': 1, 'reportDate': 1}", name = "idx_tenant_report_date")
@Schema(description = "Expiry report for analyzing expiration trends and status")
public class ExpiryReport {

    @Id
    @Schema(description = "Unique identifier for the report")
    private String id;

    @Indexed
    @Schema(description = "Tenant identifier for multi-tenancy")
    private String tenantId;

    @Indexed
    @Schema(description = "Report type", required = true)
    private ReportType reportType;

    @Schema(description = "Report name")
    private String reportName;

    @Indexed
    @Schema(description = "Report date", required = true)
    private LocalDate reportDate;

    @Schema(description = "Report period start")
    private LocalDate periodStart;

    @Schema(description = "Report period end")
    private LocalDate periodEnd;

    @Schema(description = "Total items tracked")
    private Integer totalItemsTracked;

    @Schema(description = "Items expiring soon")
    private Integer itemsExpiringSoon;

    @Schema(description = "Items expired")
    private Integer itemsExpired;

    @Schema(description = "Items disposed")
    private Integer itemsDisposed;

    @Schema(description = "Items returned to supplier")
    private Integer itemsReturned;

    @Schema(description = "Total value of expiring items")
    private Double totalExpiringValue;

    @Schema(description = "Total value loss from disposal")
    private Double totalValueLoss;

    @Schema(description = "Report status", required = true)
    private ReportStatus status;

    @Schema(description = "Generated by")
    private String generatedBy;

    @Schema(description = "Report data (summary by SKU, location, etc.)")
    private Map<String, Object> reportData;

    @Schema(description = "Report file URL")
    private String reportFileUrl;

    @Schema(description = "Additional attributes")
    private Map<String, Object> attributes;

    @CreatedDate
    @Schema(description = "Timestamp when the report was created")
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Schema(description = "Timestamp when the report was last updated")
    private LocalDateTime updatedAt;

    /**
     * Report type enumeration
     */
    public enum ReportType {
        DAILY_SUMMARY,
        WEEKLY_SUMMARY,
        MONTHLY_SUMMARY,
        EXPIRING_SOON,
        EXPIRED_ITEMS,
        DISPOSITION_REPORT,
        VALUE_AT_RISK,
        COMPLIANCE_REPORT
    }

    /**
     * Report status enumeration
     */
    public enum ReportStatus {
        GENERATING,
        COMPLETED,
        FAILED,
        SCHEDULED
    }
}
