apiVersion: v1
kind: Secret
metadata:
  name: anomaly-detection-service-secrets
  namespace: ai-services
  labels:
    app: anomaly-detection-service
    team: team-f-ai-services
type: Opaque
stringData:
  mongodb-user: "anomaly-detection-service_user"
  mongodb-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
