spring:
  application:
    name: anomaly-detection-service

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gogidix.aiservices.anomalydetectionservice: DEBUG
