apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-search-service
  namespace: ai-services
  labels:
    app: ai-search-service
    team: team-ai-customer-experience
automountServiceAccountToken: false
