package com.gogidix.shared.warehousing.reorder.domain.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Purchase Order Entity - Multi-tenant with MongoDB
 *
 * Generated purchase orders for reordering stock
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "purchase_orders")
@CompoundIndex(def = "{'tenantId': 1, 'orderNumber': 1}", name = "idx_tenant_order")
@Schema(description = "Purchase order for reordering inventory")
public class PurchaseOrder {

    @Id
    @Schema(description = "Unique identifier for the purchase order")
    private String id;

    @Indexed
    @Schema(description = "Tenant identifier for multi-tenancy")
    private String tenantId;

    @Indexed
    @Schema(description = "Purchase order number", required = true)
    private String orderNumber;

    @Indexed
    @Schema(description = "Supplier ID", required = true)
    private String supplierId;

    @Schema(description = "Supplier name")
    private String supplierName;

    @Schema(description = "Order date", required = true)
    private LocalDate orderDate;

    @Schema(description = "Expected delivery date")
    private LocalDate expectedDeliveryDate;

    @Schema(description = "Actual delivery date")
    private LocalDate actualDeliveryDate;

    @Schema(description = "Purchase order status", required = true)
    private OrderStatus status;

    @Schema(description = "Order items")
    private List<OrderItem> items;

    @Schema(description = "Total order amount")
    private Double totalAmount;

    @Schema(description = "Currency code")
    private String currencyCode;

    @Schema(description = "Payment terms")
    private String paymentTerms;

    @Schema(description = "Shipping terms")
    private String shippingTerms;

    @Schema(description = "Shipping address")
    private String shippingAddress;

    @Schema(description = "Billing address")
    private String billingAddress;

    @Schema(description = "Notes")
    private String notes;

    @Schema(description = "Internal notes")
    private String internalNotes;

    @Schema(description = "Requested by")
    private String requestedBy;

    @Schema(description = "Approved by")
    private String approvedBy;

    @Schema(description = "Approval date")
    private LocalDateTime approvalDate;

    @Schema(description = "Sent to supplier date")
    private LocalDateTime sentToSupplierDate;

    @Schema(description = "Acknowledged by supplier date")
    private LocalDateTime acknowledgedDate;

    @Schema(description = "Auto-generated flag")
    private Boolean autoGenerated;

    @Schema(description = "Associated reorder point IDs")
    private List<String> reorderPointIds;

    @CreatedDate
    @Schema(description = "Timestamp when the record was created")
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Schema(description = "Timestamp when the record was last updated")
    private LocalDateTime updatedAt;

    /**
     * Order item nested class
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Purchase order line item")
    public static class OrderItem {
        @Schema(description = "Line item number")
        private Integer lineNumber;

        @Schema(description = "Product SKU", required = true)
        private String sku;

        @Schema(description = "Product name")
        private String productName;

        @Schema(description = "Ordered quantity", required = true)
        private Integer quantity;

        @Schema(description = "Unit of measure")
        private String unitOfMeasure;

        @Schema(description = "Unit price")
        private Double unitPrice;

        @Schema(description = "Line item total")
        private Double lineTotal;

        @Schema(description = "Expected delivery date for this item")
        private LocalDate expectedDeliveryDate;
    }

    /**
     * Order status enumeration
     */
    public enum OrderStatus {
        DRAFT,
        PENDING_APPROVAL,
        APPROVED,
        SENT_TO_SUPPLIER,
        ACKNOWLEDGED,
        PARTIALLY_RECEIVED,
        RECEIVED,
        CANCELLED,
        REJECTED
    }
}
