apiVersion: v1
kind: Service
metadata:
  name: ai-recommendation-service
  namespace: ai-services
  labels:
    app: ai-recommendation-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-recommendation-service
  ports:
  - name: http
    port: 8234
    targetPort: 8234
    protocol: TCP
