apiVersion: v1
kind: Secret
metadata:
  name: ai-business-automation-service
  namespace: ai-services
  labels:
    app: ai-business-automation-service
    version: v1
    team: team-ai-business-ops
    component: business-operations
    environment: production
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://ai-business-automation-service:password@mongodb.ai-services.svc.cluster.local:27017/ai_business_automation_service_db?authSource=admin"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.ai-services.svc.cluster.local:9092"
  EUREKA_URL: "http://eureka-server.ai-services.svc.cluster.local:8761/eureka/"
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: "PLAIN"
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-business-automation-service-registry
  namespace: ai-services
  labels:
    app: ai-business-automation-service
    version: v1
    team: team-ai-business-ops
    component: business-operations
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {"auths":{"gogidix.azurecr.io":{"username":"","password":"","email":""}}}
