apiVersion: v1
kind: ConfigMap
metadata:
  name: sla-management-service-config
  namespace: business-support
  labels:
    app: sla-management-service
    team: team-e-business-support
data:
  redis-host: "redis"
  redis-port: "6379"
  kafka-bootstrap-servers: "kafka:9092"
