// Mock Data for Country Sales Dashboard Development

import type {
  CountryInfo,
  CountrySalesUser,
  SalesTeam,
  TeamMember,
  TeamPerformance,
  CountryDashboardSummary,
  CountryMetric,
  PeriodInfo,
  TeamRanking,
  TopPerformer,
  Deal,
  CountryAlert,
  ForecastSummary,
  CountryPartner,
  PartnerApplication,
  Lead,
  Customer,
  Territory,
  CountryPipeline,
  PerformanceData,
  IndividualRanking,
  PerformanceTrend,
  ProductPerformance,
  CountryReport,
  Region,
} from '@domain/types';

// ============================================================
// Mock Country (Nigeria)
// ============================================================

export const mockNigeria: CountryInfo = {
  code: 'NG',
  name: 'Nigeria',
  flag: '\uD83C\uDDF3\uD83C\uDDEC',
  currency: 'NGN',
  region: 'West Africa',
  callingCode: '+234',
};

// ============================================================
// Mock Regions
// ============================================================

export const mockRegions: Region[] = [
  {
    id: 'reg-001',
    name: 'Lagos Region',
    code: 'LAG',
    country: 'NG',
    managerId: 'usr-003',
    managerName: 'Adebayo Okafor',
    territories: [],
  },
  {
    id: 'reg-002',
    name: 'Abuja Region',
    code: 'ABV',
    country: 'NG',
    managerId: 'usr-004',
    managerName: 'Fatima Abdullahi',
    territories: [],
  },
  {
    id: 'reg-003',
    name: 'Port Harcourt Region',
    code: 'PHC',
    country: 'NG',
    managerId: 'usr-005',
    managerName: 'Chinedu Eze',
    territories: [],
  },
];

// ============================================================
// Mock Territories
// ============================================================

export const mockTerritories: Territory[] = [
  {
    id: 'terr-001',
    name: 'Lagos Mainland',
    code: 'LM',
    country: 'NG',
    region: 'Lagos Region',
    quota: 5000000,
  },
  {
    id: 'terr-002',
    name: 'Lagos Island',
    code: 'LI',
    country: 'NG',
    region: 'Lagos Region',
    quota: 6000000,
  },
  {
    id: 'terr-003',
    name: 'Abuja Metro',
    code: 'AM',
    country: 'NG',
    region: 'Abuja Region',
    quota: 4000000,
  },
  {
    id: 'terr-004',
    name: 'Port Harcourt Metro',
    code: 'PHM',
    country: 'NG',
    region: 'Port Harcourt Region',
    quota: 3500000,
  },
  {
    id: 'terr-005',
    name: 'Ibadan',
    code: 'IB',
    country: 'NG',
    region: 'Lagos Region',
    quota: 2500000,
  },
];

// ============================================================
// Mock Users
// ============================================================

export const mockUsers: CountrySalesUser[] = [
  {
    id: 'usr-001',
    email: 'chinedu.amadi@gogidix.com',
    firstName: 'Chinedu',
    lastName: 'Amadi',
    avatar: 'https://i.pravatar.cc/150?img=11',
    role: 'COUNTRY_MANAGER',
    country: mockNigeria,
    permissions: [],
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-01-15'),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: 'usr-002',
    email: 'adebayo.okafor@gogidix.com',
    firstName: 'Adebayo',
    lastName: 'Okafor',
    avatar: 'https://i.pravatar.cc/150?img=12',
    role: 'REGIONAL_MANAGER',
    country: mockNigeria,
    assignedRegion: 'Lagos Region',
    permissions: [],
    managerId: 'usr-001',
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-03-20'),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: 'usr-003',
    email: 'fatima.abdullahi@gogidix.com',
    firstName: 'Fatima',
    lastName: 'Abdullahi',
    avatar: 'https://i.pravatar.cc/150?img=5',
    role: 'REGIONAL_MANAGER',
    country: mockNigeria,
    assignedRegion: 'Abuja Region',
    permissions: [],
    managerId: 'usr-001',
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-04-10'),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: 'usr-004',
    email: 'nkem.owusu@gogidix.com',
    firstName: 'Nkem',
    lastName: 'Owusu',
    avatar: 'https://i.pravatar.cc/150?img=9',
    role: 'TEAM_LEAD',
    country: mockNigeria,
    assignedRegion: 'Lagos Region',
    assignedTerritory: 'Lagos Mainland',
    permissions: [],
    managerId: 'usr-002',
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-06-15'),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: 'usr-005',
    email: 'emeka.nnamani@gogidix.com',
    firstName: 'Emeka',
    lastName: 'Nnamani',
    avatar: 'https://i.pravatar.cc/150?img=13',
    role: 'SALES_REPRESENTATIVE',
    country: mockNigeria,
    assignedRegion: 'Lagos Region',
    assignedTerritory: 'Lagos Mainland',
    permissions: [],
    managerId: 'usr-004',
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-08-20'),
    lastLoginAt: new Date(),
    isActive: true,
  },
  {
    id: 'usr-006',
    email: 'chioma.eze@gogidix.com',
    firstName: 'Chioma',
    lastName: 'Eze',
    avatar: 'https://i.pravatar.cc/150?img=16',
    role: 'SALES_REPRESENTATIVE',
    country: mockNigeria,
    assignedRegion: 'Lagos Region',
    assignedTerritory: 'Lagos Island',
    permissions: [],
    managerId: 'usr-004',
    timezone: 'Africa/Lagos',
    createdAt: new Date('2023-09-10'),
    lastLoginAt: new Date(),
    isActive: true,
  },
];

// ============================================================
// Mock Sales Teams
// ============================================================

export const mockSalesTeams: SalesTeam[] = [
  {
    id: 'team-001',
    name: 'Lagos Mainland Team',
    code: 'LGT-LM',
    description: 'Sales team covering Lagos Mainland territory',
    country: mockNigeria,
    region: mockRegions[0],
    teamLeadId: 'usr-004',
    teamLeadName: 'Nkem Owusu',
    members: [
      {
        userId: 'usr-005',
        name: 'Emeka Nnamani',
        email: 'emeka.nnamani@gogidix.com',
        role: 'SALES_REPRESENTATIVE',
        avatar: 'https://i.pravatar.cc/150?img=13',
        status: 'active',
        individualQuota: 1000000,
        revenueGenerated: 1250000,
        attainment: 125,
        joinedAt: new Date('2023-08-20'),
      },
      {
        userId: 'usr-007',
        name: 'Olufemi Adeyemi',
        email: 'olufemi.adeyemi@gogidix.com',
        role: 'SALES_REPRESENTATIVE',
        avatar: 'https://i.pravatar.cc/150?img=14',
        status: 'active',
        individualQuota: 1000000,
        revenueGenerated: 890000,
        attainment: 89,
        joinedAt: new Date('2023-10-15'),
      },
    ],
    status: 'active',
    quota: {
      monthly: 5000000,
      quarterly: 15000000,
      annual: 60000000,
    },
    metrics: {
      revenueThisMonth: 5450000,
      revenueThisQuarter: 16800000,
      quotaAttainment: 109,
      dealsClosed: 45,
      pipelineValue: 12500000,
      winRate: 35,
    },
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date(),
  },
  {
    id: 'team-002',
    name: 'Lagos Island Team',
    code: 'LGT-LI',
    description: 'Sales team covering Lagos Island territory',
    country: mockNigeria,
    region: mockRegions[0],
    teamLeadId: 'usr-008',
    teamLeadName: 'Grace Okon',
    members: [
      {
        userId: 'usr-006',
        name: 'Chioma Eze',
        email: 'chioma.eze@gogidix.com',
        role: 'SALES_REPRESENTATIVE',
        avatar: 'https://i.pravatar.cc/150?img=16',
        status: 'active',
        individualQuota: 1200000,
        revenueGenerated: 1450000,
        attainment: 121,
        joinedAt: new Date('2023-09-10'),
      },
      {
        userId: 'usr-009',
        name: 'Ifeanyi Okonkwo',
        email: 'ifeanyi.okonkwo@gogidix.com',
        role: 'SALES_REPRESENTATIVE',
        avatar: 'https://i.pravatar.cc/150?img=15',
        status: 'active',
        individualQuota: 1200000,
        revenueGenerated: 1180000,
        attainment: 98,
        joinedAt: new Date('2023-11-20'),
      },
    ],
    status: 'active',
    quota: {
      monthly: 6000000,
      quarterly: 18000000,
      annual: 72000000,
    },
    metrics: {
      revenueThisMonth: 6320000,
      revenueThisQuarter: 19200000,
      quotaAttainment: 105,
      dealsClosed: 52,
      pipelineValue: 15800000,
      winRate: 38,
    },
    createdAt: new Date('2023-07-20'),
    updatedAt: new Date(),
  },
  {
    id: 'team-003',
    name: 'Abuja Metro Team',
    code: 'ABV-AM',
    description: 'Sales team covering Abuja metropolitan area',
    country: mockNigeria,
    region: mockRegions[1],
    teamLeadId: 'usr-010',
    teamLeadName: 'Sani Bello',
    members: [
      {
        userId: 'usr-011',
        name: 'Aisha Mohammed',
        email: 'aisha.mohammed@gogidix.com',
        role: 'SALES_REPRESENTATIVE',
        avatar: 'https://i.pravatar.cc/150?img=20',
        status: 'active',
        individualQuota: 800000,
        revenueGenerated: 720000,
        attainment: 90,
        joinedAt: new Date('2023-12-01'),
      },
    ],
    status: 'active',
    quota: {
      monthly: 4000000,
      quarterly: 12000000,
      annual: 48000000,
    },
    metrics: {
      revenueThisMonth: 3780000,
      revenueThisQuarter: 11400000,
      quotaAttainment: 95,
      dealsClosed: 32,
      pipelineValue: 9500000,
      winRate: 32,
    },
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date(),
  },
];

// ============================================================
// Mock Deals
// ============================================================

export const mockDeals: Deal[] = [
  {
    id: 'deal-001',
    dealNumber: 'NG-2025-0001',
    name: 'Dangote Group Enterprise Contract',
    accountId: 'acc-001',
    accountName: 'Dangote Group',
    contactId: 'con-001',
    contactName: 'Ahmed Dangote',
    value: 2500000,
    currency: 'USD',
    stage: 'NEGOTIATION',
    probability: 75,
    expectedCloseDate: new Date('2025-03-15'),
    owner: {
      id: 'usr-004',
      name: 'Nkem Owusu',
      team: 'Lagos Mainland Team',
    },
    priority: 'high',
    source: 'REFERRAL',
    products: [
      {
        id: 'prod-001',
        name: 'Enterprise Logistics Suite',
        code: 'ELS-ENT',
        quantity: 5,
        unitPrice: 500000,
        discount: 0,
        totalPrice: 2500000,
      },
    ],
    competitors: ['FedEx Logistics', 'DHL Express'],
    nextStep: 'Final contract review meeting',
    lastActivityAt: new Date('2025-02-18'),
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-02-18'),
    tags: ['enterprise', 'high-value', 'manufacturing'],
  },
  {
    id: 'deal-002',
    dealNumber: 'NG-2025-0002',
    name: 'GTBank Digital Transformation',
    accountId: 'acc-002',
    accountName: 'Guaranty Trust Bank',
    contactId: 'con-002',
    contactName: 'Chioma Nwosu',
    value: 1800000,
    currency: 'USD',
    stage: 'PROPOSAL',
    probability: 50,
    expectedCloseDate: new Date('2025-03-30'),
    owner: {
      id: 'usr-008',
      name: 'Grace Okon',
      team: 'Lagos Island Team',
    },
    priority: 'high',
    source: 'PARTNER',
    products: [
      {
        id: 'prod-002',
        name: 'Digital Sales Platform',
        code: 'DSP-BANK',
        quantity: 10,
        unitPrice: 180000,
        discount: 0,
        totalPrice: 1800000,
      },
    ],
    nextStep: 'Technical demonstration',
    lastActivityAt: new Date('2025-02-17'),
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-02-17'),
    tags: ['banking', 'digital', 'enterprise'],
  },
  {
    id: 'deal-003',
    dealNumber: 'NG-2025-0003',
    name: 'Shoprite Nigeria Expansion',
    accountId: 'acc-003',
    accountName: 'Shoprite Nigeria',
    contactId: 'con-003',
    contactName: 'John Peters',
    value: 950000,
    currency: 'USD',
    stage: 'CLOSING',
    probability: 90,
    expectedCloseDate: new Date('2025-02-28'),
    owner: {
      id: 'usr-004',
      name: 'Nkem Owusu',
      team: 'Lagos Mainland Team',
    },
    priority: 'urgent',
    source: 'EVENT',
    products: [
      {
        id: 'prod-003',
        name: 'Retail Management Solution',
        code: 'RMS-RTL',
        quantity: 20,
        unitPrice: 47500,
        discount: 0,
        totalPrice: 950000,
      },
    ],
    nextStep: 'Final signature collection',
    lastActivityAt: new Date('2025-02-18'),
    createdAt: new Date('2024-12-10'),
    updatedAt: new Date('2025-02-18'),
    tags: ['retail', 'expansion', 'high-priority'],
  },
  {
    id: 'deal-004',
    dealNumber: 'NG-2025-0004',
    name: 'MTN Nigeria Partnership',
    accountId: 'acc-004',
    accountName: 'MTN Nigeria',
    contactId: 'con-004',
    contactName: 'Tunde Bakare',
    value: 3500000,
    currency: 'USD',
    stage: 'QUALIFICATION',
    probability: 25,
    expectedCloseDate: new Date('2025-05-15'),
    owner: {
      id: 'usr-002',
      name: 'Adebayo Okafor',
      team: 'Lagos Region',
    },
    priority: 'high',
    source: 'WEBSITE',
    products: [],
    nextStep: 'Stakeholder meeting',
    lastActivityAt: new Date('2025-02-15'),
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-02-15'),
    tags: ['telecom', 'partnership', 'enterprise'],
  },
  {
    id: 'deal-005',
    dealNumber: 'NG-2025-0005',
    name: 'Jumia Warehouse Solution',
    accountId: 'acc-005',
    accountName: 'Jumia Nigeria',
    contactId: 'con-005',
    contactName: 'Fatima Ibrahim',
    value: 1200000,
    currency: 'USD',
    stage: 'WON',
    probability: 100,
    expectedCloseDate: new Date('2025-02-01'),
    actualCloseDate: new Date('2025-02-01'),
    owner: {
      id: 'usr-005',
      name: 'Emeka Nnamani',
      team: 'Lagos Mainland Team',
    },
    priority: 'medium',
    source: 'REFERRAL',
    products: [
      {
        id: 'prod-004',
        name: 'Warehouse Management Pro',
        code: 'WMP-PRO',
        quantity: 3,
        unitPrice: 400000,
        discount: 0,
        totalPrice: 1200000,
      },
    ],
    nextStep: 'Onboarding',
    lastActivityAt: new Date('2025-02-01'),
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2025-02-01'),
    tags: ['ecommerce', 'warehouse', 'won'],
  },
  {
    id: 'deal-006',
    dealNumber: 'NG-2025-0006',
    name: 'Nestle Nigeria Supply Chain',
    accountId: 'acc-006',
    accountName: 'Nestle Nigeria',
    contactId: 'con-006',
    contactName: 'Grace Akinwale',
    value: 850000,
    currency: 'USD',
    stage: 'PROPOSAL',
    probability: 60,
    expectedCloseDate: new Date('2025-04-10'),
    owner: {
      id: 'usr-010',
      name: 'Sani Bello',
      team: 'Abuja Metro Team',
    },
    priority: 'medium',
    source: 'COLD_CALL',
    products: [],
    nextStep: 'Submit detailed proposal',
    lastActivityAt: new Date('2025-02-16'),
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-02-16'),
    tags: ['fmcg', 'supply-chain'],
  },
];

// ============================================================
// Mock Leads
// ============================================================

export const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    leadNumber: 'NG-L-2025-0001',
    firstName: 'Rotimi',
    lastName: 'Adeleke',
    email: 'rotimi.adeleke@innovatenigeria.com',
    phone: '+234 802 345 6789',
    company: 'Innovate Nigeria Ltd',
    title: 'Chief Technology Officer',
    industry: 'Technology',
    status: 'QUALIFIED',
    source: 'WEBSITE',
    rating: 'hot',
    estimatedValue: 450000,
    currency: 'USD',
    assignedTo: 'usr-005',
    assignedToName: 'Emeka Nnamani',
    assignedTeam: 'Lagos Mainland Team',
    territory: 'Lagos Mainland',
    tags: ['technology', 'startup', 'hot'],
    notes: 'Interested in enterprise solution, decision maker',
    lastContactedAt: new Date('2025-02-17'),
    nextFollowUp: new Date('2025-02-20'),
    activities: [
      {
        id: 'act-001',
        type: 'call',
        subject: 'Initial discovery call',
        description: 'Discussed requirements and budget',
        createdBy: 'usr-005',
        createdByName: 'Emeka Nnamani',
        createdAt: new Date('2025-02-17'),
      },
    ],
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-02-17'),
  },
  {
    id: 'lead-002',
    leadNumber: 'NG-L-2025-0002',
    firstName: 'Amara',
    lastName: 'Okafor',
    email: 'amara.okafor@fashionhub.ng',
    phone: '+234 803 456 7890',
    company: 'Fashion Hub Nigeria',
    title: 'Managing Director',
    industry: 'Fashion',
    status: 'CONTACTED',
    source: 'REFERRAL',
    rating: 'warm',
    estimatedValue: 120000,
    currency: 'USD',
    assignedTo: 'usr-006',
    assignedToName: 'Chioma Eze',
    assignedTeam: 'Lagos Island Team',
    territory: 'Lagos Island',
    tags: ['fashion', 'retail', 'warm'],
    notes: 'Referred by existing customer, interested in POS',
    lastContactedAt: new Date('2025-02-16'),
    nextFollowUp: new Date('2025-02-21'),
    activities: [],
    createdAt: new Date('2025-02-12'),
    updatedAt: new Date('2025-02-16'),
  },
  {
    id: 'lead-003',
    leadNumber: 'NG-L-2025-0003',
    firstName: 'Ibrahim',
    lastName: 'Suleiman',
    email: 'ibrahim.s@northernagric.com',
    phone: '+234 804 567 8901',
    company: 'Northern Agriculture Co.',
    title: 'Operations Manager',
    industry: 'Agriculture',
    status: 'NEW',
    source: 'EVENT',
    rating: 'cold',
    estimatedValue: 75000,
    currency: 'USD',
    tags: ['agriculture', 'event-lead'],
    notes: 'Met at Abuja Trade Fair 2025',
    createdAt: new Date('2025-02-18'),
    updatedAt: new Date('2025-02-18'),
    activities: [],
  },
  {
    id: 'lead-004',
    leadNumber: 'NG-L-2025-0004',
    firstName: 'Ngozi',
    lastName: 'Eze',
    email: 'ngozi.eze@logisticsplus.com',
    phone: '+234 805 678 9012',
    company: 'Logistics Plus',
    title: 'CEO',
    industry: 'Logistics',
    status: 'CONVERTED',
    source: 'PARTNER',
    rating: 'hot',
    estimatedValue: 280000,
    currency: 'USD',
    assignedTo: 'usr-004',
    assignedToName: 'Nkem Owusu',
    assignedTeam: 'Lagos Mainland Team',
    territory: 'Lagos Mainland',
    tags: ['logistics', 'converted'],
    notes: 'Converted to deal NG-2025-0007',
    lastContactedAt: new Date('2025-02-15'),
    convertedToDeal: true,
    dealId: 'deal-007',
    activities: [],
    createdAt: new Date('2025-01-28'),
    updatedAt: new Date('2025-02-15'),
  },
  {
    id: 'lead-005',
    leadNumber: 'NG-L-2025-0005',
    firstName: 'Chukwuemeka',
    lastName: 'Nwokeji',
    email: 'c.nwokeji@buildright.com',
    phone: '+234 806 789 0123',
    company: 'Build Right Construction',
    title: 'Project Manager',
    industry: 'Construction',
    status: 'UNQUALIFIED',
    source: 'COLD_CALL',
    rating: 'cold',
    estimatedValue: 0,
    currency: 'USD',
    assignedTo: 'usr-007',
    assignedToName: 'Olufemi Adeyemi',
    assignedTeam: 'Lagos Mainland Team',
    tags: ['construction', 'unqualified'],
    notes: 'Budget too low, timeline not aligned',
    lastContactedAt: new Date('2025-02-14'),
    activities: [],
    createdAt: new Date('2025-02-05'),
    updatedAt: new Date('2025-02-14'),
  },
];

// ============================================================
// Mock Customers
// ============================================================

export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    customerNumber: 'NG-C-2025-0001',
    name: 'Dangote Group',
    logo: '',
    industry: 'Manufacturing',
    tier: 'enterprise',
    status: 'active',
    address: {
      street: '1 Dangote Road',
      city: 'Lagos',
      state: 'Lagos',
      postalCode: '101241',
      country: 'Nigeria',
    },
    contacts: [
      {
        id: 'con-001',
        firstName: 'Ahmed',
        lastName: 'Dangote',
        title: 'Chief Procurement Officer',
        email: 'ahmed.dangote@dangotegroup.com',
        phone: '+234 801 111 1111',
        isPrimary: true,
      },
    ],
    accountOwner: {
      id: 'usr-004',
      name: 'Nkem Owusu',
      email: 'nkem.owusu@gogidix.com',
    },
    teamOwner: {
      id: 'team-001',
      name: 'Lagos Mainland Team',
    },
    metrics: {
      totalRevenue: 12500000,
      dealsCount: 15,
      avgDealSize: 833333,
      ltv: 15000000,
      firstPurchaseDate: new Date('2024-01-15'),
      lastPurchaseDate: new Date('2025-01-20'),
      nextRenewalDate: new Date('2025-07-15'),
    },
    territory: 'Lagos Mainland',
    tags: ['enterprise', 'manufacturing', 'key-account'],
    notes: 'Strategic enterprise customer, annual contract',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-002',
    customerNumber: 'NG-C-2025-0002',
    name: 'Jumia Nigeria',
    logo: '',
    industry: 'E-commerce',
    tier: 'enterprise',
    status: 'active',
    address: {
      street: '42 Ikorodu Road',
      city: 'Lagos',
      state: 'Lagos',
      postalCode: '100221',
      country: 'Nigeria',
    },
    contacts: [
      {
        id: 'con-002',
        firstName: 'Fatima',
        lastName: 'Ibrahim',
        title: 'Head of Operations',
        email: 'fatima.ibrahim@jumia.com',
        phone: '+234 802 222 2222',
        isPrimary: true,
      },
    ],
    accountOwner: {
      id: 'usr-005',
      name: 'Emeka Nnamani',
      email: 'emeka.nnamani@gogidix.com',
    },
    teamOwner: {
      id: 'team-001',
      name: 'Lagos Mainland Team',
    },
    metrics: {
      totalRevenue: 4800000,
      dealsCount: 8,
      avgDealSize: 600000,
      ltv: 5500000,
      firstPurchaseDate: new Date('2024-06-01'),
      lastPurchaseDate: new Date('2025-02-01'),
      nextRenewalDate: new Date('2025-08-01'),
    },
    territory: 'Lagos Mainland',
    tags: ['ecommerce', 'warehouse', 'growing'],
    notes: 'Growing account, potential for expansion',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-003',
    customerNumber: 'NG-C-2025-0003',
    name: 'Fashion Hub Nigeria',
    logo: '',
    industry: 'Fashion',
    tier: 'mid_market',
    status: 'active',
    address: {
      street: '15 Adeniran Ogunsanya',
      city: 'Surulere',
      state: 'Lagos',
      postalCode: '101281',
      country: 'Nigeria',
    },
    contacts: [
      {
        id: 'con-003',
        firstName: 'Amara',
        lastName: 'Okafor',
        title: 'Managing Director',
        email: 'amara.okafor@fashionhub.ng',
        phone: '+234 803 333 3333',
        isPrimary: true,
      },
    ],
    accountOwner: {
      id: 'usr-006',
      name: 'Chioma Eze',
      email: 'chioma.eze@gogidix.com',
    },
    teamOwner: {
      id: 'team-002',
      name: 'Lagos Island Team',
    },
    metrics: {
      totalRevenue: 350000,
      dealsCount: 2,
      avgDealSize: 175000,
      ltv: 420000,
      firstPurchaseDate: new Date('2024-09-10'),
      lastPurchaseDate: new Date('2025-01-15'),
      nextRenewalDate: new Date('2025-07-10'),
    },
    territory: 'Lagos Island',
    tags: ['fashion', 'retail', 'mid-market'],
    notes: 'New customer, potential upsell',
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-004',
    customerNumber: 'NG-C-2025-0004',
    name: 'Build Right Construction',
    logo: '',
    industry: 'Construction',
    tier: 'small_business',
    status: 'at_risk',
    address: {
      street: '8 Wuse 2',
      city: 'Abuja',
      state: 'FCT',
      postalCode: '900108',
      country: 'Nigeria',
    },
    contacts: [
      {
        id: 'con-004',
        firstName: 'Chukwuemeka',
        lastName: 'Nwokeji',
        title: 'Project Manager',
        email: 'c.nwokeji@buildright.com',
        phone: '+234 804 444 4444',
        isPrimary: true,
      },
    ],
    accountOwner: {
      id: 'usr-011',
      name: 'Aisha Mohammed',
      email: 'aisha.mohammed@gogidix.com',
    },
    teamOwner: {
      id: 'team-003',
      name: 'Abuja Metro Team',
    },
    metrics: {
      totalRevenue: 120000,
      dealsCount: 1,
      avgDealSize: 120000,
      ltv: 150000,
      firstPurchaseDate: new Date('2024-03-20'),
      lastPurchaseDate: new Date('2024-10-15'),
    },
    territory: 'Abuja Metro',
    tags: ['construction', 'at-risk'],
    notes: 'Last deal 4 months ago, need re-engagement',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date(),
  },
];

// ============================================================
// Mock Partners
// ============================================================

export const mockPartners: CountryPartner[] = [
  {
    id: 'p-001',
    partnerNumber: 'NG-P-2025-0001',
    userId: 'usr-p001',
    user: {
      firstName: 'Tunde',
      lastName: 'Bakare',
      email: 'tunde.bakare@partnerlogistics.ng',
      phone: '+234 801 555 5555',
      avatar: 'https://i.pravatar.cc/150?img=21',
    },
    partnerType: 'COURIER',
    assignedCountry: mockNigeria,
    assignedTerritory: mockTerritories[0],
    status: 'ACTIVE',
    tier: 'GOLD',
    partnersRecruited: 8,
    customersAcquired: 24,
    pipelineValue: 850000,
    revenueGenerated: 2100000,
    commissionEarned: 210000,
    referralBonusEarned: 45000,
    tierProgression: {
      currentTier: 'GOLD',
      currentTierRevenue: 2100000,
      nextTier: 'PLATINUM',
      nextTierRevenue: 5000000,
      revenueToNextTier: 2900000,
      estimatedTimeToNextTier: 60,
    },
    leadConversionRate: 38,
    avgDealSize: 87500,
    activeDeals: 12,
    assignedLeads: [],
    approvedAt: new Date('2024-03-15'),
    approvedBy: 'usr-001',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date(),
    lastActivityAt: new Date('2025-02-17'),
  },
  {
    id: 'p-002',
    partnerNumber: 'NG-P-2025-0002',
    userId: 'usr-p002',
    user: {
      firstName: 'Ngozi',
      lastName: 'Adichie',
      email: 'ngozi.adichie@ecomconnect.ng',
      phone: '+234 802 666 6666',
      avatar: 'https://i.pravatar.cc/150?img=25',
    },
    partnerType: 'ECOMMERCE',
    assignedCountry: mockNigeria,
    assignedTerritory: mockTerritories[1],
    status: 'ACTIVE',
    tier: 'PLATINUM',
    partnersRecruited: 15,
    customersAcquired: 42,
    pipelineValue: 1200000,
    revenueGenerated: 5800000,
    commissionEarned: 725000,
    referralBonusEarned: 85000,
    tierProgression: {
      currentTier: 'PLATINUM',
      currentTierRevenue: 5800000,
      revenueToNextTier: 0,
    },
    leadConversionRate: 45,
    avgDealSize: 138095,
    activeDeals: 18,
    assignedLeads: [],
    approvedAt: new Date('2023-08-20'),
    approvedBy: 'usr-001',
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date(),
    lastActivityAt: new Date('2025-02-18'),
  },
  {
    id: 'p-003',
    partnerNumber: 'NG-P-2025-0003',
    userId: 'usr-p003',
    user: {
      firstName: 'Olumide',
      lastName: 'Ogunleye',
      email: 'olumide.ogunleye@warehousetech.ng',
      phone: '+234 803 777 7777',
      avatar: 'https://i.pravatar.cc/150?img=22',
    },
    partnerType: 'WAREHOUSE',
    assignedCountry: mockNigeria,
    assignedTerritory: mockTerritories[0],
    status: 'ACTIVE',
    tier: 'SILVER',
    partnersRecruited: 4,
    customersAcquired: 12,
    pipelineValue: 420000,
    revenueGenerated: 480000,
    commissionEarned: 36000,
    referralBonusEarned: 12000,
    tierProgression: {
      currentTier: 'SILVER',
      currentTierRevenue: 480000,
      nextTier: 'GOLD',
      nextTierRevenue: 500000,
      revenueToNextTier: 20000,
      estimatedTimeToNextTier: 5,
    },
    leadConversionRate: 32,
    avgDealSize: 40000,
    activeDeals: 8,
    assignedLeads: [],
    approvedAt: new Date('2024-10-01'),
    approvedBy: 'usr-002',
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date(),
    lastActivityAt: new Date('2025-02-16'),
  },
];

// ============================================================
// Mock Partner Applications
// ============================================================

export const mockPartnerApplications: PartnerApplication[] = [
  {
    id: 'app-001',
    applicationNumber: 'NG-PA-2025-0001',
    applicant: {
      firstName: 'Chioma',
      lastName: 'Nwosu',
      email: 'chioma.nwosu@email.com',
      phone: '+234 808 888 8888',
      address: {
        street: '45 Opebi Road',
        city: 'Ikeja',
        state: 'Lagos',
        postalCode: '100271',
        country: 'Nigeria',
      },
    },
    partnerType: 'HAULAGE',
    preferredCountry: mockNigeria,
    preferredTerritory: 'Lagos Mainland',
    documents: [],
    backgroundCheck: {
      status: 'CLEARED',
      completedAt: new Date('2025-02-10'),
    },
    status: 'PENDING',
    createdAt: new Date('2025-02-08'),
    updatedAt: new Date('2025-02-10'),
  },
  {
    id: 'app-002',
    applicationNumber: 'NG-PA-2025-0002',
    applicant: {
      firstName: 'Abubakar',
      lastName: 'Mohammed',
      email: 'abubakar.m@email.com',
      phone: '+234 809 999 9999',
      address: {
        street: '12 Ahmadu Bello Way',
        city: 'Kaduna',
        state: 'Kaduna',
        postalCode: '800242',
        country: 'Nigeria',
      },
    },
    partnerType: 'WAREHOUSE',
    preferredCountry: mockNigeria,
    preferredTerritory: 'Abuja Metro',
    documents: [],
    backgroundCheck: {
      status: 'PENDING',
    },
    status: 'UNDER_REVIEW',
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-02-18'),
  },
];

// ============================================================
// Mock Pipeline Data
// ============================================================

export const mockPipelineData: CountryPipeline = {
  totalValue: 18500000,
  totalDeals: 156,
  weightedValue: 8750000,
  avgDealSize: 118589,
  byStage: [
    { stage: 'PROSPECTING', count: 24, totalValue: 1800000, weightedValue: 180000, percentage: 15, avgDaysInStage: 5 },
    { stage: 'QUALIFICATION', count: 38, totalValue: 3200000, weightedValue: 800000, percentage: 24, avgDaysInStage: 12 },
    { stage: 'PROPOSAL', count: 42, totalValue: 5800000, weightedValue: 2900000, percentage: 27, avgDaysInStage: 28 },
    { stage: 'NEGOTIATION', count: 35, totalValue: 5200000, weightedValue: 3900000, percentage: 23, avgDaysInStage: 18 },
    { stage: 'CLOSING', count: 17, totalValue: 2500000, weightedValue: 2250000, percentage: 11, avgDaysInStage: 7 },
  ],
  byOwner: [
    {
      ownerId: 'usr-004',
      ownerName: 'Nkem Owusu',
      team: 'Lagos Mainland Team',
      dealCount: 28,
      totalValue: 4200000,
      weightedValue: 2100000,
      quotaAttainment: 145,
    },
    {
      ownerId: 'usr-008',
      ownerName: 'Grace Okon',
      team: 'Lagos Island Team',
      dealCount: 32,
      totalValue: 5100000,
      weightedValue: 2550000,
      quotaAttainment: 138,
    },
    {
      ownerId: 'usr-005',
      ownerName: 'Emeka Nnamani',
      team: 'Lagos Mainland Team',
      dealCount: 22,
      totalValue: 2800000,
      weightedValue: 1400000,
      quotaAttainment: 125,
    },
  ],
  byTeam: [
    {
      teamId: 'team-001',
      teamName: 'Lagos Mainland Team',
      dealCount: 58,
      totalValue: 7800000,
      weightedValue: 3900000,
      memberCount: 3,
      avgPerMember: 2600000,
    },
    {
      teamId: 'team-002',
      teamName: 'Lagos Island Team',
      dealCount: 62,
      totalValue: 8500000,
      weightedValue: 4250000,
      memberCount: 3,
      avgPerMember: 2833333,
    },
  ],
  velocity: {
    avgDaysInStage: {
      PROSPECTING: 5,
      QUALIFICATION: 12,
      PROPOSAL: 28,
      NEGOTIATION: 18,
      CLOSING: 7,
    },
    overallCycle: 70,
    cycleTarget: 60,
    cycleVariance: 10,
  },
  trending: {
    up: 68,
    down: 12,
    neutral: 76,
  },
};

// ============================================================
// Mock Dashboard Summary
// ============================================================

export const mockDashboardSummary: CountryDashboardSummary = {
  period: {
    start: new Date('2025-02-01'),
    end: new Date('2025-02-28'),
    type: 'monthly',
    label: 'February 2025',
  },
  country: mockNigeria,
  metrics: {
    revenue: {
      value: 28500000,
      label: '\u20A628.5M',
      change: 15,
      changeType: 'increase',
      target: 25000000,
      attainment: 114,
      currency: 'NGN',
    },
    pipelineValue: {
      value: 18500000,
      label: '$18.5M',
      change: 8,
      changeType: 'increase',
      currency: 'USD',
    },
    dealsClosed: {
      value: 89,
      label: '89',
      change: 12,
      changeType: 'increase',
    },
    activeDeals: {
      value: 156,
      label: '156',
      change: 5,
      changeType: 'increase',
    },
    winRate: {
      value: 36,
      label: '36%',
      change: 3,
      changeType: 'increase',
    },
    avgDealSize: {
      value: 320000,
      label: '$320K',
      change: -5,
      changeType: 'decrease',
      currency: 'USD',
    },
    newLeads: {
      value: 245,
      label: '245',
      change: 18,
      changeType: 'increase',
    },
    partners: {
      value: 156,
      label: '156',
      change: 8,
      changeType: 'increase',
    },
  },
  teamRankings: [
    { rank: 1, teamId: 'team-001', teamName: 'Lagos Mainland Team', teamLead: 'Nkem Owusu', revenue: 5450000, attainment: 109, dealsClosed: 45, trend: 'up' },
    { rank: 2, teamId: 'team-002', teamName: 'Lagos Island Team', teamLead: 'Grace Okon', revenue: 6320000, attainment: 105, dealsClosed: 52, trend: 'up' },
    { rank: 3, teamId: 'team-003', teamName: 'Abuja Metro Team', teamLead: 'Sani Bello', revenue: 3780000, attainment: 95, dealsClosed: 32, trend: 'neutral' },
  ],
  topPerformers: [
    {
      userId: 'usr-005',
      name: 'Emeka Nnamani',
      avatar: 'https://i.pravatar.cc/150?img=13',
      role: 'SALES_REPRESENTATIVE',
      team: 'Lagos Mainland Team',
      revenue: 1250000,
      quota: 1000000,
      attainment: 125,
      dealsClosed: 15,
      rank: 1,
      activities: { calls: 245, emails: 380, meetings: 42 },
    },
    {
      userId: 'usr-006',
      name: 'Chioma Eze',
      avatar: 'https://i.pravatar.cc/150?img=16',
      role: 'SALES_REPRESENTATIVE',
      team: 'Lagos Island Team',
      revenue: 1450000,
      quota: 1200000,
      attainment: 121,
      dealsClosed: 18,
      rank: 2,
      activities: { calls: 289, emails: 420, meetings: 48 },
    },
    {
      userId: 'usr-004',
      name: 'Nkem Owusu',
      avatar: 'https://i.pravatar.cc/150?img=9',
      role: 'TEAM_LEAD',
      team: 'Lagos Mainland Team',
      revenue: 980000,
      quota: 800000,
      attainment: 123,
      dealsClosed: 12,
      rank: 3,
      activities: { calls: 198, emails: 320, meetings: 35 },
    },
  ],
  majorDeals: [mockDeals[0], mockDeals[3], mockDeals[4]],
  alerts: [
    {
      id: 'alert-001',
      type: 'warning',
      category: 'quota',
      title: 'Team Below Quota',
      message: 'Abuja Metro Team is at 95% of monthly quota',
      severity: 'medium',
      actionUrl: '/performance?team=team-003',
      createdAt: new Date(),
      isRead: false,
    },
    {
      id: 'alert-002',
      type: 'success',
      category: 'deal',
      title: 'Major Deal Won',
      message: 'Jumia Nigeria deal worth $1.2M has been closed',
      severity: 'low',
      actionUrl: '/deals/deal-005',
      createdAt: new Date('2025-02-01'),
      isRead: true,
    },
    {
      id: 'alert-003',
      type: 'info',
      category: 'partner',
      title: 'New Partner Applications',
      message: '5 new partner applications awaiting review',
      severity: 'low',
      actionUrl: '/partners?tab=applications',
      createdAt: new Date(),
      isRead: false,
    },
  ],
  forecastSummary: {
    period: 'February 2025',
    forecast: 32000000,
    bestCase: 38000000,
    worstCase: 28000000,
    weightedPipeline: 8750000,
    currency: 'NGN',
    accuracy: 92,
  },
};

// ============================================================
// Mock Performance Data
// ============================================================

export const mockPerformanceData: PerformanceData = {
  period: {
    start: new Date('2025-02-01'),
    end: new Date('2025-02-28'),
    type: 'monthly',
    label: 'February 2025',
  },
  country: mockNigeria,
  summary: {
    revenue: {
      actual: 28500000,
      target: 25000000,
      attainment: 114,
      change: 15,
    },
    quota: {
      assigned: 25000000,
      achieved: 28500000,
      attainment: 114,
      change: 12,
    },
    deals: {
      closed: 89,
      inPipeline: 156,
      won: 89,
      lost: 34,
      change: 12,
    },
    winRate: {
      value: 36,
      change: 3,
    },
  },
  teamComparison: mockSalesTeams.map(team => ({
    teamId: team.id,
    teamName: team.name,
    period: {
      start: new Date('2025-02-01'),
      end: new Date('2025-02-28'),
      type: 'monthly',
      label: 'February 2025',
    },
    metrics: {
      revenue: team.metrics.revenueThisMonth,
      quota: team.quota.monthly,
      attainment: team.metrics.quotaAttainment,
      dealsClosed: team.metrics.dealsClosed,
      avgDealSize: team.metrics.revenueThisMonth / team.metrics.dealsClosed,
      pipelineValue: team.metrics.pipelineValue,
      activities: {
        calls: Math.floor(Math.random() * 500) + 200,
        emails: Math.floor(Math.random() * 800) + 400,
        meetings: Math.floor(Math.random() * 80) + 30,
        demos: Math.floor(Math.random() * 40) + 10,
      },
    },
    members: team.members.map(member => ({
      userId: member.userId,
      name: member.name,
      avatar: member.avatar,
      role: member.role,
      metrics: {
        revenue: member.revenueGenerated,
        quota: member.individualQuota,
        attainment: member.attainment,
        dealsClosed: Math.floor(member.revenueGenerated / 80000),
        activities: {
          calls: Math.floor(Math.random() * 200) + 50,
          emails: Math.floor(Math.random() * 300) + 100,
          meetings: Math.floor(Math.random() * 30) + 10,
        },
      },
    })),
    trend: team.metrics.quotaAttainment >= 100 ? 'up' : team.metrics.quotaAttainment >= 90 ? 'neutral' : 'down',
  })),
  individualRankings: [
    {
      rank: 1,
      userId: 'usr-006',
      name: 'Chioma Eze',
      avatar: 'https://i.pravatar.cc/150?img=16',
      role: 'SALES_REPRESENTATIVE',
      team: 'Lagos Island Team',
      revenue: 1450000,
      attainment: 121,
      dealsClosed: 18,
      activities: { calls: 289, emails: 420, meetings: 48 },
    },
    {
      rank: 2,
      userId: 'usr-005',
      name: 'Emeka Nnamani',
      avatar: 'https://i.pravatar.cc/150?img=13',
      role: 'SALES_REPRESENTATIVE',
      team: 'Lagos Mainland Team',
      revenue: 1250000,
      attainment: 125,
      dealsClosed: 15,
      activities: { calls: 245, emails: 380, meetings: 42 },
    },
    {
      rank: 3,
      userId: 'usr-004',
      name: 'Nkem Owusu',
      avatar: 'https://i.pravatar.cc/150?img=9',
      role: 'TEAM_LEAD',
      team: 'Lagos Mainland Team',
      revenue: 980000,
      attainment: 123,
      dealsClosed: 12,
      activities: { calls: 198, emails: 320, meetings: 35 },
    },
  ],
  trendAnalysis: [
    { period: 'Oct 2024', revenue: 22000000, target: 23000000, attainment: 96, dealsClosed: 72, winRate: 32 },
    { period: 'Nov 2024', revenue: 24500000, target: 24000000, attainment: 102, dealsClosed: 78, winRate: 34 },
    { period: 'Dec 2024', revenue: 26000000, target: 25000000, attainment: 104, dealsClosed: 82, winRate: 35 },
    { period: 'Jan 2025', revenue: 24800000, target: 24500000, attainment: 101, dealsClosed: 76, winRate: 33 },
    { period: 'Feb 2025', revenue: 28500000, target: 25000000, attainment: 114, dealsClosed: 89, winRate: 36 },
  ],
  productBreakdown: [
    { productCode: 'ELS-ENT', productName: 'Enterprise Logistics Suite', category: 'Logistics', revenue: 8500000, percentage: 30, growth: 18, targetAttainment: 115, unitsSold: 45 },
    { productCode: 'DSP-BANK', productName: 'Digital Sales Platform', category: 'Software', revenue: 6200000, percentage: 22, growth: 25, targetAttainment: 128, unitsSold: 82 },
    { productCode: 'RMS-RTL', productName: 'Retail Management Solution', category: 'Retail', revenue: 5100000, percentage: 18, growth: 12, targetAttainment: 105, unitsSold: 120 },
    { productCode: 'WMP-PRO', productName: 'Warehouse Management Pro', category: 'Warehouse', revenue: 4800000, percentage: 17, growth: 8, targetAttainment: 98, unitsSold: 35 },
    { productCode: 'TCM-STD', productName: 'Transport Coordination Module', category: 'Logistics', revenue: 3900000, percentage: 13, growth: -5, targetAttainment: 88, unitsSold: 95 },
  ],
};

// ============================================================
// Mock Reports
// ============================================================

export const mockReports: CountryReport[] = [
  {
    id: 'rep-001',
    name: 'Monthly Sales Performance',
    description: 'Comprehensive monthly sales performance report',
    type: 'SALES_PERFORMANCE',
    category: 'SALES',
    createdBy: 'usr-001',
    createdAt: new Date('2025-01-15'),
    lastRunAt: new Date('2025-02-01'),
    schedule: {
      frequency: 'monthly',
      dayOfMonth: 1,
      time: '09:00',
      recipients: ['manager@gogidix.com'],
      active: true,
      nextRunAt: new Date('2025-03-01'),
    },
    config: {
      metrics: ['revenue', 'quota', 'deals', 'winRate'],
      period: {
        start: new Date('2025-02-01'),
        end: new Date('2025-02-28'),
        type: 'monthly',
        label: 'February 2025',
      },
      exportFormat: 'PDF',
    },
  },
  {
    id: 'rep-002',
    name: 'Team Performance Analysis',
    description: 'Detailed team performance comparison',
    type: 'TEAM_PERFORMANCE',
    category: 'TEAM',
    createdBy: 'usr-002',
    createdAt: new Date('2025-01-20'),
    config: {
      metrics: ['revenue', 'quota', 'activities'],
      teams: ['team-001', 'team-002', 'team-003'],
      period: {
        start: new Date('2025-02-01'),
        end: new Date('2025-02-28'),
        type: 'monthly',
        label: 'February 2025',
      },
      exportFormat: 'EXCEL',
    },
  },
  {
    id: 'rep-003',
    name: 'Partner Commission Report',
    description: 'Monthly partner commission and payout report',
    type: 'PARTNER_PERFORMANCE',
    category: 'PARTNER',
    createdBy: 'usr-001',
    createdAt: new Date('2025-01-25'),
    lastRunAt: new Date('2025-02-01'),
    config: {
      metrics: ['commission', 'referrals', 'sales'],
      period: {
        start: new Date('2025-02-01'),
        end: new Date('2025-02-28'),
        type: 'monthly',
        label: 'February 2025',
      },
      exportFormat: 'PDF',
    },
  },
];

export {
  type CountryInfo,
  type CountrySalesUser,
  type SalesTeam,
  type TeamMember,
  type Deal,
  type Lead,
  type Customer,
  type CountryPartner,
  type PartnerApplication,
  type Territory,
  type Region,
  type CountryDashboardSummary,
  type CountryPipeline,
  type PerformanceData,
  type CountryReport,
};
