apiVersion: v1
kind: Secret
metadata:
  name: ai-product-recommendationation-service-secrets
  namespace: ai-services
  labels:
    app: ai-product-recommendationation-service
    team: team-f-ai-services
type: Opaque
stringData:
  mongodb-user: "ai-product-recommendationation-service_user"
  mongodb-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
