apiVersion: v1
kind: Service
metadata:
  name: ai-product-recommendationation-service
  namespace: ai-services
  labels:
    app: ai-product-recommendationation-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-product-recommendationation-service
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    protocol: TCP
