apiVersion: v1
kind: Service
metadata:
  name: ai-feature-store-service
  namespace: ai-services
  labels:
    app: ai-feature-store-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-feature-store-service
  ports:
  - name: http
    port: 8251
    targetPort: 8251
    protocol: TCP
