apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-feature-store-service
  namespace: ai-services
  labels:
    app: ai-feature-store-service
    team: team-ai-mlops
automountServiceAccountToken: false
