spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_category
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        categoryEvents-out-0:
          destination: category-events
          content-type: application/json

server:
  port: 8304

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gogidix.ecommerce.category: DEBUG
