// Mock Data: Brands
// Comprehensive mock data for brand management

import { Brand, BrandAsset, BrandGuideline, BrandTemplate } from '../../domain/entities/Brand.entity';

const mockBrandAssets: BrandAsset[] = [
  {
    id: 'asset-001',
    name: 'Gogidix Primary Logo',
    type: 'logo',
    url: '/assets/brand/logo-primary.svg',
    thumbnailUrl: '/assets/brand/logo-primary-thumb.png',
    fileSize: 24576,
    format: 'SVG',
    dimensions: { width: 500, height: 150 },
    tags: ['logo', 'primary', 'brand'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-15'),
    usageCount: 2847,
    versions: [
      { id: 'v1', version: 1, url: '/assets/brand/logo-primary-v1.svg', createdAt: new Date('2025-01-15'), createdBy: 'user-301' },
    ],
  },
  {
    id: 'asset-002',
    name: 'Gogidix Logo Dark',
    type: 'logo',
    url: '/assets/brand/logo-dark.svg',
    thumbnailUrl: '/assets/brand/logo-dark-thumb.png',
    fileSize: 23456,
    format: 'SVG',
    dimensions: { width: 500, height: 150 },
    tags: ['logo', 'dark', 'brand'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-15'),
    usageCount: 1523,
    versions: [],
  },
  {
    id: 'asset-003',
    name: 'Gogidix Icon Mark',
    type: 'logo',
    url: '/assets/brand/icon-mark.svg',
    thumbnailUrl: '/assets/brand/icon-mark-thumb.png',
    fileSize: 8192,
    format: 'SVG',
    dimensions: { width: 150, height: 150 },
    tags: ['logo', 'icon', 'brand'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-15'),
    usageCount: 3547,
    versions: [],
  },
  {
    id: 'asset-004',
    name: 'Primary Color Palette',
    type: 'color_palette',
    url: '/assets/brand/colors-primary.png',
    thumbnailUrl: '/assets/brand/colors-primary-thumb.png',
    fileSize: 45678,
    format: 'PNG',
    dimensions: { width: 1200, height: 400 },
    tags: ['colors', 'primary', 'brand'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-16'),
    usageCount: 847,
    versions: [],
  },
  {
    id: 'asset-005',
    name: 'Brand Typography Guide',
    type: 'typography',
    url: '/assets/brand/typography.pdf',
    thumbnailUrl: '/assets/brand/typography-thumb.png',
    fileSize: 128456,
    format: 'PDF',
    tags: ['typography', 'fonts', 'brand'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-17'),
    usageCount: 523,
    versions: [],
  },
  {
    id: 'asset-006',
    name: 'Email Template - Newsletter',
    type: 'template',
    url: '/assets/templates/email-newsletter.html',
    thumbnailUrl: '/assets/templates/email-newsletter-thumb.png',
    fileSize: 52428,
    format: 'HTML',
    tags: ['email', 'newsletter', 'template'],
    uploadedBy: { id: 'user-302', name: 'Sarah Kim' },
    uploadedAt: new Date('2025-03-10'),
    usageCount: 1247,
    versions: [],
  },
  {
    id: 'asset-007',
    name: 'Social Media Kit',
    type: 'template',
    url: '/assets/templates/social-kit.zip',
    thumbnailUrl: '/assets/templates/social-kit-thumb.png',
    fileSize: 5242880,
    format: 'ZIP',
    tags: ['social', 'templates', 'kit'],
    uploadedBy: { id: 'user-302', name: 'Sarah Kim' },
    uploadedAt: new Date('2025-04-20'),
    usageCount: 1847,
    versions: [
      { id: 'v1', version: 1, url: '/assets/templates/social-kit-v1.zip', createdAt: new Date('2025-04-20'), createdBy: 'user-302' },
      { id: 'v2', version: 2, url: '/assets/templates/social-kit-v2.zip', createdAt: new Date('2025-10-15'), createdBy: 'user-302' },
    ],
  },
  {
    id: 'asset-008',
    name: 'Product Brochure Template',
    type: 'template',
    url: '/assets/templates/brochure.indd',
    thumbnailUrl: '/assets/templates/brochure-thumb.png',
    fileSize: 15728640,
    format: 'INDD',
    tags: ['brochure', 'product', 'template'],
    uploadedBy: { id: 'user-303', name: 'Marcus Johnson' },
    uploadedAt: new Date('2025-02-28'),
    usageCount: 324,
    versions: [],
  },
  {
    id: 'asset-009',
    name: 'Brand Presentation Template',
    type: 'template',
    url: '/assets/templates/presentation.pptx',
    thumbnailUrl: '/assets/templates/presentation-thumb.png',
    fileSize: 20971520,
    format: 'PPTX',
    tags: ['presentation', 'brand', 'template'],
    uploadedBy: { id: 'user-303', name: 'Marcus Johnson' },
    uploadedAt: new Date('2025-03-05'),
    usageCount: 854,
    versions: [],
  },
  {
    id: 'asset-010',
    name: 'Brand Guidelines Document',
    type: 'guidelines',
    url: '/assets/brand/guidelines.pdf',
    thumbnailUrl: '/assets/brand/guidelines-thumb.png',
    fileSize: 15728640,
    format: 'PDF',
    tags: ['guidelines', 'brand', 'rules'],
    uploadedBy: { id: 'user-301', name: 'Alex Rivera' },
    uploadedAt: new Date('2025-01-20'),
    usageCount: 1247,
    versions: [
      { id: 'v1', version: 1, url: '/assets/brand/guidelines-v1.pdf', createdAt: new Date('2025-01-20'), createdBy: 'user-301' },
      { id: 'v2', version: 2, url: '/assets/brand/guidelines-v2.pdf', createdAt: new Date('2025-07-15'), createdBy: 'user-301' },
    ],
  },
  {
    id: 'asset-011',
    name: 'Hero Image Collection',
    type: 'image',
    url: '/assets/images/hero-collection.zip',
    thumbnailUrl: '/assets/images/hero-collection-thumb.png',
    fileSize: 104857600,
    format: 'ZIP',
    dimensions: { width: 1920, height: 1080 },
    tags: ['hero', 'images', 'marketing'],
    uploadedBy: { id: 'user-304', name: 'Emily Chen' },
    uploadedAt: new Date('2025-06-10'),
    usageCount: 2147,
    versions: [],
  },
  {
    id: 'asset-012',
    name: 'Brand Video - Introduction',
    type: 'video',
    url: '/assets/videos/brand-intro.mp4',
    thumbnailUrl: '/assets/videos/brand-intro-thumb.png',
    fileSize: 52428800,
    format: 'MP4',
    tags: ['video', 'brand', 'intro'],
    uploadedBy: { id: 'user-305', name: 'Tom Anderson' },
    uploadedAt: new Date('2025-05-20'),
    usageCount: 547,
    versions: [],
  },
];

const mockBrandGuidelines: BrandGuideline[] = [
  {
    id: 'guide-001',
    category: 'Logo Usage',
    title: 'Logo Clear Space and Sizing',
    content: 'The logo must always maintain clear space equal to the height of the "G" icon...',
    assets: ['asset-001', 'asset-002', 'asset-003'],
    order: 1,
  },
  {
    id: 'guide-002',
    category: 'Logo Usage',
    title: 'Logo Color Variations',
    content: 'The primary logo should be used on light backgrounds. Use the dark logo on dark backgrounds...',
    assets: ['asset-001', 'asset-002'],
    order: 2,
  },
  {
    id: 'guide-003',
    category: 'Colors',
    title: 'Primary Color Palette',
    content: 'Our primary palette consists of three colors: Navy Blue (#1E3A8A), Electric Blue (#3B82F6), and White...',
    assets: ['asset-004'],
    order: 3,
  },
  {
    id: 'guide-004',
    category: 'Typography',
    title: 'Typefaces and Weights',
    content: 'Inter is our primary typeface. Use weights from 400 (Regular) to 700 (Bold)...',
    assets: ['asset-005'],
    order: 4,
  },
  {
    id: 'guide-005',
    category: 'Voice and Tone',
    title: 'Brand Voice Guidelines',
    content: 'Our brand voice is professional, confident, and approachable. We communicate with clarity...',
    assets: [],
    order: 5,
  },
];

const mockBrandTemplates: BrandTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Email Newsletter Template',
    type: 'email',
    description: 'Standard email newsletter template with customizable sections',
    thumbnail: '/assets/templates/email-newsletter-thumb.png',
    brandId: 'brand-001',
    category: 'Email Marketing',
    file: {
      url: '/assets/templates/email-newsletter.html',
      format: 'HTML',
      size: 52428,
    },
    variables: [
      { name: 'headline', type: 'text', defaultValue: 'Update from Gogidix', required: true },
      { name: 'primary_color', type: 'color', defaultValue: '#3B82F6', required: false },
      { name: 'cta_text', type: 'text', defaultValue: 'Learn More', required: true },
      { name: 'footer_text', type: 'text', defaultValue: '', required: false },
    ],
    usageCount: 1247,
    lastUsed: new Date('2026-02-15'),
    createdAt: new Date('2025-03-10'),
  },
  {
    id: 'tpl-002',
    name: 'Social Media Post - Square',
    type: 'social',
    description: 'Square format social media post template',
    thumbnail: '/assets/templates/social-square-thumb.png',
    brandId: 'brand-001',
    category: 'Social Media',
    file: {
      url: '/assets/templates/social-square.psd',
      format: 'PSD',
      size: 15728640,
    },
    variables: [
      { name: 'headline', type: 'text', defaultValue: '', required: true },
      { name: 'body_text', type: 'text', defaultValue: '', required: true },
      { name: 'accent_color', type: 'color', defaultValue: '#3B82F6', required: false },
    ],
    usageCount: 3547,
    lastUsed: new Date('2026-02-18'),
    createdAt: new Date('2025-04-20'),
  },
  {
    id: 'tpl-003',
    name: 'Presentation Template',
    type: 'presentation',
    description: 'Company presentation template with master slides',
    thumbnail: '/assets/templates/presentation-thumb.png',
    brandId: 'brand-001',
    category: 'Presentations',
    file: {
      url: '/assets/templates/presentation.pptx',
      format: 'PPTX',
      size: 20971520,
    },
    variables: [
      { name: 'title', type: 'text', defaultValue: 'Presentation Title', required: true },
      { name: 'subtitle', type: 'text', defaultValue: '', required: false },
      { name: 'presenter_name', type: 'text', defaultValue: '', required: true },
    ],
    usageCount: 854,
    lastUsed: new Date('2026-02-10'),
    createdAt: new Date('2025-03-05'),
  },
  {
    id: 'tpl-004',
    name: 'Product Brochure',
    type: 'document',
    description: 'Product brochure template for print and digital',
    thumbnail: '/assets/templates/brochure-thumb.png',
    brandId: 'brand-001',
    category: 'Marketing Collateral',
    file: {
      url: '/assets/templates/brochure.indd',
      format: 'INDD',
      size: 15728640,
    },
    variables: [
      { name: 'product_name', type: 'text', defaultValue: '', required: true },
      { name: 'tagline', type: 'text', defaultValue: '', required: false },
      { name: 'features', type: 'list', defaultValue: '', required: true },
    ],
    usageCount: 324,
    lastUsed: new Date('2026-02-01'),
    createdAt: new Date('2025-02-28'),
  },
  {
    id: 'tpl-005',
    name: 'Landing Page Template',
    type: 'web',
    description: 'Conversion-focused landing page template',
    thumbnail: '/assets/templates/landing-page-thumb.png',
    brandId: 'brand-001',
    category: 'Web',
    file: {
      url: '/assets/templates/landing-page.html',
      format: 'HTML',
      size: 104857,
    },
    variables: [
      { name: 'hero_headline', type: 'text', defaultValue: '', required: true },
      { name: 'hero_subtext', type: 'text', defaultValue: '', required: true },
      { name: 'cta_text', type: 'text', defaultValue: 'Get Started', required: true },
      { name: 'primary_color', type: 'color', defaultValue: '#3B82F6', required: false },
    ],
    usageCount: 647,
    lastUsed: new Date('2026-02-16'),
    createdAt: new Date('2025-05-15'),
  },
];

const mockBrands: Brand[] = [
  {
    id: 'brand-001',
    name: 'Gogidix Global',
    description: 'Master brand for all Gogidix products and services worldwide',
    logo: '/assets/brand/logo-primary.svg',
    website: 'https://www.gogidix.com',
    industry: 'Technology',
    colors: {
      primary: ['#1E3A8A', '#3B82F6', '#60A5FA'],
      secondary: ['#10B981', '#8B5CF6', '#F59E0B'],
      accent: ['#EF4444', '#EC4899', '#06B6D4'],
    },
    typography: {
      primaryFont: 'Inter',
      secondaryFont: 'Roboto',
      headingFont: 'Inter',
    },
    tone: ['Professional', 'Confident', 'Innovative', 'Approachable', 'Clear'],
    values: ['Excellence', 'Innovation', 'Integrity', 'Collaboration', 'Customer Success'],
    assets: mockBrandAssets,
    guidelines: mockBrandGuidelines,
    countries: ['US', 'GB', 'DE', 'FR', 'CA', 'AU', 'JP', 'SG', 'BR', 'IN'],
    status: 'active',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2026-01-20'),
    createdBy: { id: 'user-301', name: 'Alex Rivera' },
  },
  {
    id: 'brand-002',
    name: 'Gogidix Enterprise',
    description: 'Enterprise-focused sub-brand for B2B solutions',
    logo: '/assets/brand/enterprise-logo.svg',
    website: 'https://enterprise.gogidix.com',
    industry: 'Enterprise Software',
    colors: {
      primary: ['#0F172A', '#1E293B', '#334155'],
      secondary: ['#3B82F6', '#6366F1', '#8B5CF6'],
      accent: ['#10B981', '#06B6D4'],
    },
    typography: {
      primaryFont: 'Inter',
      secondaryFont: 'Source Sans Pro',
      headingFont: 'Inter',
    },
    tone: ['Enterprise-grade', 'Reliable', 'Scalable', 'Secure', 'Professional'],
    values: ['Security', 'Scalability', 'Reliability', 'Support'],
    assets: mockBrandAssets.slice(0, 6),
    guidelines: mockBrandGuidelines.slice(0, 3),
    countries: ['US', 'GB', 'DE', 'FR', 'CA', 'AU'],
    status: 'active',
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2026-01-15'),
    createdBy: { id: 'user-301', name: 'Alex Rivera' },
  },
];

export const mockGetBrandById = (id: string): Brand | undefined =>
  mockBrands.find(b => b.id === id);

export const mockGetBrandAssets = (brandId: string): BrandAsset[] =>
  mockBrands.find(b => b.id === brandId)?.assets || [];

export default mockBrands;
