// Mock Data: Campaigns
// Comprehensive mock data for campaigns

import { Campaign, CampaignStatus, CampaignType, ChannelType } from '../../domain/entities/Campaign.entity';
import { COUNTRIES } from '../constants/countries';

const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Q1 Global Brand Awareness',
    description: 'Multi-channel brand awareness campaign targeting key markets',
    status: CampaignStatus.ACTIVE,
    type: CampaignType.AWARENESS,
    channels: [ChannelType.SOCIAL, ChannelType.DISPLAY, ChannelType.VIDEO],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 150000, targetAudience: 'Professionals 25-45' },
      { countryCode: 'GB', countryName: 'United Kingdom', budget: 80000, targetAudience: 'Professionals 25-45' },
      { countryCode: 'DE', countryName: 'Germany', budget: 70000, targetAudience: 'Business decision makers' },
      { countryCode: 'FR', countryName: 'France', budget: 60000, targetAudience: 'Business decision makers' },
    ],
    budget: {
      total: 360000,
      spent: 248500,
      remaining: 111500,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-01-01'),
      end: new Date('2026-03-31'),
      createdAt: new Date('2025-12-15'),
      updatedAt: new Date('2026-02-15'),
    },
    metrics: {
      impressions: 45200000,
      clicks: 1250000,
      conversions: 45000,
      cost: 248500,
      revenue: 892000,
      leads: 12500,
      ctr: 2.76,
      cpc: 0.199,
      cpa: 5.52,
      roas: 3.59,
    },
    owner: {
      id: 'user-001',
      name: 'Sarah Mitchell',
      email: 'sarah.mitchell@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['brand-awareness', 'multi-country', 'q1-2026'],
    objectives: ['Increase brand awareness by 25%', 'Generate 10,000 qualified leads'],
    kpis: [
      { name: 'Impressions', target: 50000000, current: 45200000, unit: '' },
      { name: 'Click-through Rate', target: 3.0, current: 2.76, unit: '%' },
      { name: 'Cost per Lead', target: 20, current: 19.88, unit: '$' },
    ],
  },
  {
    id: 'camp-002',
    name: 'EMEA Product Launch - Enterprise Edition',
    description: 'Product launch campaign for enterprise edition in EMEA markets',
    status: CampaignStatus.ACTIVE,
    type: CampaignType.CONVERSION,
    channels: [ChannelType.EMAIL, ChannelType.SEARCH, ChannelType.LINKEDIN],
    countries: [
      { countryCode: 'GB', countryName: 'United Kingdom', budget: 120000, targetAudience: 'Enterprise IT decision makers' },
      { countryCode: 'DE', countryName: 'Germany', budget: 100000, targetAudience: 'Enterprise IT decision makers' },
      { countryCode: 'FR', countryName: 'France', budget: 80000, targetAudience: 'Enterprise IT decision makers' },
      { countryCode: 'NL', countryName: 'Netherlands', budget: 50000, targetAudience: 'Enterprise IT decision makers' },
    ],
    budget: {
      total: 350000,
      spent: 175000,
      remaining: 175000,
      currency: 'EUR',
    },
    dates: {
      start: new Date('2026-02-01'),
      end: new Date('2026-04-30'),
      createdAt: new Date('2026-01-20'),
      updatedAt: new Date('2026-02-18'),
    },
    metrics: {
      impressions: 8500000,
      clicks: 425000,
      conversions: 8500,
      cost: 175000,
      revenue: 1275000,
      leads: 4200,
      ctr: 5.0,
      cpc: 0.412,
      cpa: 20.59,
      roas: 7.29,
    },
    owner: {
      id: 'user-002',
      name: 'James Wilson',
      email: 'james.wilson@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['product-launch', 'emea', 'enterprise', '2026'],
    objectives: ['Generate 5,000 enterprise leads', 'Achieve $1M pipeline'],
    kpis: [
      { name: 'Enterprise Leads', target: 5000, current: 4200, unit: '' },
      { name: 'Pipeline Value', target: 1000000, current: 1275000, unit: '$' },
      { name: 'Conversion Rate', target: 2.5, current: 2.0, unit: '%' },
    ],
  },
  {
    id: 'camp-003',
    name: 'APAC Expansion - Phase 1',
    description: 'Initial expansion campaign for APAC markets',
    status: CampaignStatus.SCHEDULED,
    type: CampaignType.AWARENESS,
    channels: [ChannelType.SOCIAL, ChannelType.SEARCH, ChannelType.DISPLAY],
    countries: [
      { countryCode: 'JP', countryName: 'Japan', budget: 100000, targetAudience: 'Business professionals' },
      { countryCode: 'SG', countryName: 'Singapore', budget: 60000, targetAudience: 'Business professionals' },
      { countryCode: 'AU', countryName: 'Australia', budget: 70000, targetAudience: 'Business professionals' },
    ],
    budget: {
      total: 230000,
      spent: 0,
      remaining: 230000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-03-01'),
      end: new Date('2026-06-30'),
      createdAt: new Date('2026-02-01'),
      updatedAt: new Date('2026-02-10'),
    },
    metrics: {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      cost: 0,
      revenue: 0,
      leads: 0,
      ctr: 0,
      cpc: 0,
      cpa: 0,
      roas: 0,
    },
    owner: {
      id: 'user-003',
      name: 'Yuki Tanaka',
      email: 'yuki.tanaka@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['expansion', 'apac', 'phase-1'],
    objectives: ['Establish brand presence in APAC', 'Generate 2,000 leads'],
    kpis: [
      { name: 'Brand Awareness', target: 30, current: 0, unit: '%' },
      { name: 'Lead Generation', target: 2000, current: 0, unit: '' },
    ],
  },
  {
    id: 'camp-004',
    name: 'North America Retention Campaign',
    description: 'Customer retention and upsell campaign for existing customers',
    status: CampaignStatus.ACTIVE,
    type: CampaignType.RETENTION,
    channels: [ChannelType.EMAIL, ChannelType.SOCIAL],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 75000, targetAudience: 'Existing customers' },
      { countryCode: 'CA', countryName: 'Canada', budget: 25000, targetAudience: 'Existing customers' },
    ],
    budget: {
      total: 100000,
      spent: 58000,
      remaining: 42000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-01-15'),
      end: new Date('2026-04-15'),
      createdAt: new Date('2026-01-05'),
      updatedAt: new Date('2026-02-18'),
    },
    metrics: {
      impressions: 2500000,
      clicks: 375000,
      conversions: 12500,
      cost: 58000,
      revenue: 725000,
      leads: 8000,
      ctr: 15.0,
      cpc: 0.155,
      cpa: 4.64,
      roas: 12.5,
    },
    owner: {
      id: 'user-004',
      name: 'Michael Chen',
      email: 'michael.chen@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['retention', 'upsell', 'north-america'],
    objectives: ['Retain 85% of at-risk customers', 'Generate $500K upsell revenue'],
    kpis: [
      { name: 'Retention Rate', target: 85, current: 82, unit: '%' },
      { name: 'Upsell Revenue', target: 500000, current: 425000, unit: '$' },
    ],
  },
  {
    id: 'camp-005',
    name: 'Holiday Season Promotion 2025',
    description: 'Holiday season promotional campaign',
    status: CampaignStatus.COMPLETED,
    type: CampaignType.CONVERSION,
    channels: [ChannelType.EMAIL, ChannelType.SOCIAL, ChannelType.SEARCH, ChannelType.DISPLAY],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 200000, targetAudience: 'General consumers' },
      { countryCode: 'GB', countryName: 'United Kingdom', budget: 100000, targetAudience: 'General consumers' },
      { countryCode: 'DE', countryName: 'Germany', budget: 80000, targetAudience: 'General consumers' },
      { countryCode: 'FR', countryName: 'France', budget: 70000, targetAudience: 'General consumers' },
      { countryCode: 'CA', countryName: 'Canada', budget: 50000, targetAudience: 'General consumers' },
    ],
    budget: {
      total: 500000,
      spent: 498500,
      remaining: 1500,
      currency: 'USD',
    },
    dates: {
      start: new Date('2025-11-15'),
      end: new Date('2025-12-31'),
      createdAt: new Date('2025-10-20'),
      updatedAt: new Date('2026-01-05'),
    },
    metrics: {
      impressions: 125000000,
      clicks: 8750000,
      conversions: 250000,
      cost: 498500,
      revenue: 7475000,
      leads: 75000,
      ctr: 7.0,
      cpc: 0.057,
      cpa: 1.99,
      roas: 15.0,
    },
    owner: {
      id: 'user-001',
      name: 'Sarah Mitchell',
      email: 'sarah.mitchell@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['holiday', 'promotion', '2025', 'completed'],
    objectives: ['Achieve $5M holiday revenue', 'Acquire 50,000 new customers'],
    kpis: [
      { name: 'Holiday Revenue', target: 5000000, current: 7475000, unit: '$' },
      { name: 'New Customers', target: 50000, current: 68000, unit: '' },
    ],
  },
  {
    id: 'camp-006',
    name: 'Industry Events - Q1 2026',
    description: 'Series of industry event sponsorships and participation',
    status: CampaignStatus.ACTIVE,
    type: CampaignType.AWARENESS,
    channels: [ChannelType.EVENTS, ChannelType.EMAIL, ChannelType.SOCIAL],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 150000, targetAudience: 'Event attendees' },
      { countryCode: 'GB', countryName: 'United Kingdom', budget: 75000, targetAudience: 'Event attendees' },
      { countryCode: 'DE', countryName: 'Germany', budget: 50000, targetAudience: 'Event attendees' },
    ],
    budget: {
      total: 275000,
      spent: 125000,
      remaining: 150000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-01-10'),
      end: new Date('2026-03-25'),
      createdAt: new Date('2025-12-01'),
      updatedAt: new Date('2026-02-18'),
    },
    metrics: {
      impressions: 3500000,
      clicks: 175000,
      conversions: 3500,
      cost: 125000,
      revenue: 525000,
      leads: 2800,
      ctr: 5.0,
      cpc: 0.714,
      cpa: 35.71,
      roas: 4.2,
    },
    owner: {
      id: 'user-005',
      name: 'Emma Rodriguez',
      email: 'emma.rodriguez@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['events', 'sponsorships', 'q1-2026'],
    objectives: ['Generate 3,000 event leads', 'Increase brand visibility'],
    kpis: [
      { name: 'Event Leads', target: 3000, current: 2800, unit: '' },
      { name: 'Brand Mentions', target: 500, current: 425, unit: '' },
    ],
  },
  {
    id: 'camp-007',
    name: 'LATAM Market Entry - Phase 1',
    description: 'Initial market entry campaign for LATAM region',
    status: CampaignStatus.DRAFT,
    type: CampaignType.AWARENESS,
    channels: [ChannelType.SOCIAL, ChannelType.SEARCH],
    countries: [
      { countryCode: 'BR', countryName: 'Brazil', budget: 80000, targetAudience: 'Business professionals' },
      { countryCode: 'MX', countryName: 'Mexico', budget: 45000, targetAudience: 'Business professionals' },
    ],
    budget: {
      total: 125000,
      spent: 0,
      remaining: 125000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-04-01'),
      end: new Date('2026-06-30'),
      createdAt: new Date('2026-02-10'),
      updatedAt: new Date('2026-02-18'),
    },
    metrics: {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      cost: 0,
      revenue: 0,
      leads: 0,
      ctr: 0,
      cpc: 0,
      cpa: 0,
      roas: 0,
    },
    owner: {
      id: 'user-006',
      name: 'Carlos Silva',
      email: 'carlos.silva@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['latam', 'expansion', 'draft'],
    objectives: ['Establish brand presence', 'Generate 1,500 leads'],
    kpis: [],
  },
  {
    id: 'camp-008',
    name: 'Partner Co-Marketing Program',
    description: 'Co-marketing campaigns with strategic partners',
    status: CampaignStatus.ACTIVE,
    type: CampaignType.CONVERSION,
    channels: [ChannelType.EMAIL, ChannelType.WEBINARS, ChannelType.CONTENT],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 100000, targetAudience: 'Partner audiences' },
      { countryCode: 'GB', countryName: 'United Kingdom', budget: 50000, targetAudience: 'Partner audiences' },
    ],
    budget: {
      total: 150000,
      spent: 87500,
      remaining: 62500,
      currency: 'USD',
    },
    dates: {
      start: new Date('2026-01-01'),
      end: new Date('2026-03-31'),
      createdAt: new Date('2025-12-10'),
      updatedAt: new Date('2026-02-18'),
    },
    metrics: {
      impressions: 4200000,
      clicks: 315000,
      conversions: 6300,
      cost: 87500,
      revenue: 693750,
      leads: 4200,
      ctr: 7.5,
      cpc: 0.278,
      cpa: 13.89,
      roas: 7.93,
    },
    owner: {
      id: 'user-007',
      name: 'David Park',
      email: 'david.park@gogidix.com',
    },
    brand: {
      id: 'brand-001',
      name: 'Gogidix Global',
    },
    tags: ['partners', 'co-marketing'],
    objectives: ['Generate 5,000 partner leads', 'Create 10 co-branded assets'],
    kpis: [
      { name: 'Partner Leads', target: 5000, current: 4200, unit: '' },
      { name: 'Co-branded Assets', target: 10, current: 8, unit: '' },
    ],
  },
];

export const mockCampaignsByStatus = (status: CampaignStatus): Campaign[] =>
  mockCampaigns.filter(c => c.status === status);

export const mockCampaignsByCountry = (countryCode: string): Campaign[] =>
  mockCampaigns.filter(c => c.countries.some(country => country.countryCode === countryCode));

export const mockGetCampaignById = (id: string): Campaign | undefined =>
  mockCampaigns.find(c => c.id === id);

export default mockCampaigns;
