// Mock Data: Content
// Comprehensive mock data for content items

import { Content, ContentStatus, ContentType } from '../../domain/types';

export const mockContent: Content[] = [
  {
    id: 'content-001',
    title: '2026 Marketing Trends: What to Expect',
    type: 'blog_post',
    status: 'published',
    excerpt: 'Explore the top marketing trends that will shape 2026, from AI-driven personalization to immersive experiences.',
    content: 'Full content here...',
    author: {
      id: 'user-001',
      name: 'Sarah Mitchell',
      avatar: undefined,
    },
    brandId: 'brand-001',
    campaignIds: ['camp-001'],
    tags: ['marketing', 'trends', '2026', 'strategy'],
    categories: ['Marketing Strategy', 'Industry Insights'],
    seo: {
      title: '2026 Marketing Trends: What to Expect | Gogidix',
      description: 'Explore the top marketing trends that will shape 2026.',
      keywords: ['marketing trends', '2026', 'digital marketing', 'AI'],
      slug: '2026-marketing-trends',
    },
    publishing: {
      publishedAt: new Date('2026-01-15T10:00:00'),
      channels: ['blog', 'linkedin'],
      countries: ['US', 'GB', 'DE', 'FR'],
    },
    metrics: {
      views: 15240,
      clicks: 3240,
      shares: 485,
      comments: 127,
      downloads: 0,
      leads: 847,
      engagementRate: 3.8,
    },
    approval: {
      status: 'none',
    },
    createdAt: new Date('2026-01-10T09:00:00'),
    updatedAt: new Date('2026-01-15T10:00:00'),
  },
  {
    id: 'content-002',
    title: 'Product Launch Email Sequence',
    type: 'email',
    status: 'published',
    excerpt: '3-part email sequence for EMEA product launch campaign.',
    content: 'Email templates here...',
    author: {
      id: 'user-002',
      name: 'James Wilson',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-002'],
    tags: ['email', 'product-launch', 'EMEA'],
    categories: ['Email Marketing'],
    seo: {
      title: 'Product Launch Email Sequence',
      description: '3-part email sequence for EMEA product launch.',
      keywords: ['email', 'product launch'],
      slug: 'product-launch-email-sequence',
    },
    publishing: {
      publishedAt: new Date('2026-02-01T08:00:00'),
      channels: ['email'],
      countries: ['GB', 'DE', 'FR', 'NL'],
    },
    metrics: {
      views: 0,
      clicks: 8540,
      shares: 0,
      comments: 0,
      downloads: 0,
      leads: 2140,
      engagementRate: 25.1,
    },
    approval: {
      status: 'approved',
      approvedBy: 'manager-001',
      approvedAt: new Date('2026-01-28T14:00:00'),
    },
    createdAt: new Date('2026-01-25T11:00:00'),
    updatedAt: new Date('2026-02-01T08:00:00'),
  },
  {
    id: 'content-003',
    title: 'LinkedIn Carousel - ROI Calculator',
    type: 'social_post',
    status: 'published',
    excerpt: 'Interactive carousel showcasing marketing ROI calculator.',
    content: 'Carousel content...',
    author: {
      id: 'user-003',
      name: 'Emma Rodriguez',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-001'],
    tags: ['social', 'linkedin', 'roi', 'carousel'],
    categories: ['Social Media'],
    seo: {
      title: 'Marketing ROI Calculator',
      description: 'Calculate your marketing ROI with our interactive tool.',
      keywords: ['ROI', 'calculator', 'marketing'],
      slug: 'marketing-roi-calculator',
    },
    publishing: {
      publishedAt: new Date('2026-02-10T14:30:00'),
      channels: ['linkedin'],
      countries: ['US'],
    },
    metrics: {
      views: 45230,
      clicks: 6780,
      shares: 1234,
      comments: 387,
      downloads: 0,
      leads: 1123,
      engagementRate: 8.2,
    },
    approval: {
      status: 'approved',
      approvedBy: 'manager-001',
      approvedAt: new Date('2026-02-08T10:00:00'),
    },
    createdAt: new Date('2026-02-05T09:00:00'),
    updatedAt: new Date('2026-02-10T14:30:00'),
  },
  {
    id: 'content-004',
    title: 'Customer Success Story - TechCorp',
    type: 'case_study',
    status: 'approved',
    excerpt: 'How TechCorp increased lead generation by 300% with our platform.',
    content: 'Case study content...',
    author: {
      id: 'user-004',
      name: 'Michael Chen',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-004'],
    tags: ['case-study', 'success-story', 'lead-gen'],
    categories: ['Case Studies'],
    seo: {
      title: 'Customer Success Story: TechCorp',
      description: 'How TechCorp increased lead generation by 300%.',
      keywords: ['case study', 'success story', 'TechCorp'],
      slug: 'customer-success-techcorp',
    },
    publishing: {
      publishAt: new Date('2026-02-25T09:00:00'),
      channels: ['blog', 'email', 'linkedin'],
      countries: ['US', 'CA'],
    },
    metrics: {
      views: 0,
      clicks: 0,
      shares: 0,
      comments: 0,
      downloads: 0,
      leads: 0,
      engagementRate: 0,
    },
    approval: {
      status: 'approved',
      approvedBy: 'cmo-001',
      approvedAt: new Date('2026-02-18T16:00:00'),
    },
    createdAt: new Date('2026-02-10T09:00:00'),
    updatedAt: new Date('2026-02-18T16:00:00'),
  },
  {
    id: 'content-005',
    title: 'Q1 Performance Infographic',
    type: 'infographic',
    status: 'published',
    excerpt: 'Visual summary of Q1 marketing performance across all channels.',
    content: 'Infographic design...',
    author: {
      id: 'user-005',
      name: 'Lisa Park',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-001'],
    tags: ['infographic', 'q1', 'performance'],
    categories: ['Visual Content'],
    seo: {
      title: 'Q1 2026 Marketing Performance Infographic',
      description: 'Visual summary of Q1 marketing performance.',
      keywords: ['infographic', 'Q1', 'performance'],
      slug: 'q1-2026-performance-infographic',
    },
    publishing: {
      publishedAt: new Date('2026-02-18T10:00:00'),
      channels: ['social', 'blog'],
      countries: ['US', 'GB', 'DE'],
    },
    metrics: {
      views: 28750,
      clicks: 5420,
      shares: 987,
      comments: 156,
      downloads: 2340,
      leads: 1456,
      engagementRate: 6.4,
    },
    approval: {
      status: 'approved',
      approvedBy: 'manager-001',
      approvedAt: new Date('2026-02-15T11:00:00'),
    },
    createdAt: new Date('2026-02-10T09:00:00'),
    updatedAt: new Date('2026-02-18T10:00:00'),
  },
  {
    id: 'content-006',
    title: 'Webinar: Mastering B2B Marketing in 2026',
    type: 'webinar',
    status: 'scheduled',
    excerpt: 'Join our experts as they share B2B marketing strategies for 2026.',
    content: 'Webinar outline...',
    author: {
      id: 'user-001',
      name: 'Sarah Mitchell',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-002'],
    tags: ['webinar', 'b2b', '2026'],
    categories: ['Webinars', 'Events'],
    seo: {
      title: 'Webinar: Mastering B2B Marketing in 2026',
      description: 'Join our experts for B2B marketing strategies.',
      keywords: ['webinar', 'B2B', 'marketing'],
      slug: 'webinar-b2b-marketing-2026',
    },
    publishing: {
      publishAt: new Date('2026-03-15T14:00:00'),
      channels: ['webinar', 'email'],
      countries: ['US', 'GB'],
    },
    metrics: {
      views: 0,
      clicks: 0,
      shares: 0,
      comments: 0,
      downloads: 0,
      leads: 0,
      engagementRate: 0,
    },
    approval: {
      status: 'approved',
      approvedBy: 'manager-001',
      approvedAt: new Date('2026-02-10T14:00:00'),
    },
    createdAt: new Date('2026-02-05T09:00:00'),
    updatedAt: new Date('2026-02-10T14:00:00'),
  },
  {
    id: 'content-007',
    title: 'Social Media Content Calendar Template',
    type: 'whitepaper',
    status: 'published',
    excerpt: 'Download our free social media content calendar template.',
    content: 'Whitepaper content...',
    author: {
      id: 'user-003',
      name: 'Emma Rodriguez',
    },
    brandId: 'brand-001',
    campaignIds: ['camp-001'],
    tags: ['whitepaper', 'template', 'social-media'],
    categories: ['Resources', 'Templates'],
    seo: {
      title: 'Social Media Content Calendar Template',
      description: 'Free downloadable template for social media planning.',
      keywords: ['template', 'social media', 'content calendar'],
      slug: 'social-media-content-calendar-template',
    },
    publishing: {
      publishedAt: new Date('2026-01-20T10:00:00'),
      channels: ['blog', 'linkedin'],
      countries: ['US', 'GB', 'DE', 'FR', 'CA'],
    },
    metrics: {
      views: 18560,
      clicks: 6780,
      shares: 456,
      comments: 89,
      downloads: 4523,
      leads: 3245,
      engagementRate: 12.3,
    },
    approval: {
      status: 'approved',
      approvedBy: 'manager-001',
      approvedAt: new Date('2026-01-18T11:00:00'),
    },
    createdAt: new Date('2026-01-15T09:00:00'),
    updatedAt: new Date('2026-01-20T10:00:00'),
  },
  {
    id: 'content-008',
    title: 'Instagram Reel - Behind the Scenes',
    type: 'video',
    status: 'draft',
    excerpt: 'Behind the scenes look at our marketing team.',
    content: 'Video script...',
    author: {
      id: 'user-006',
      name: 'Carlos Silva',
    },
    brandId: 'brand-001',
    campaignIds: [],
    tags: ['video', 'instagram', 'behind-scenes'],
    categories: ['Social Media', 'Video'],
    seo: {
      title: 'Behind the Scenes at Gogidix Marketing',
      description: 'See how our marketing team works.',
      keywords: ['behind scenes', 'marketing team', 'Instagram'],
      slug: 'behind-scenes-marketing-team',
    },
    publishing: {
      channels: ['instagram'],
      countries: ['US', 'BR'],
    },
    metrics: {
      views: 0,
      clicks: 0,
      shares: 0,
      comments: 0,
      downloads: 0,
      leads: 0,
      engagementRate: 0,
    },
    approval: {
      status: 'none',
    },
    createdAt: new Date('2026-02-18T09:00:00'),
    updatedAt: new Date('2026-02-18T09:00:00'),
  },
];

export const mockContentByStatus = (status: ContentStatus): Content[] =>
  mockContent.filter(c => c.status === status);

export const mockContentByType = (type: ContentType): Content[] =>
  mockContent.filter(c => c.type === type);

export const mockGetContentById = (id: string): Content | undefined =>
  mockContent.find(c => c.id === id);

export default mockContent;
