// Mock Data for Global Marketing Dashboard
// Comprehensive mock data for development and testing

import type {
  Campaign,
  Budget,
  Lead,
  CountrySummary,
  GlobalDashboardSummary,
  SocialPost,
  Content,
  Brand,
} from '@domain/types';

// Country Data
export const mockCountries = [
  { code: 'US', name: 'United States', flag: '\u{1F1FA}\u{1F1F8}', currency: 'USD', region: 'North America', directorId: 'user-1', directorName: 'John Smith' },
  { code: 'UK', name: 'United Kingdom', flag: '\u{1F1EC}\u{1F1E7}', currency: 'GBP', region: 'EMEA', directorId: 'user-2', directorName: 'Sarah Johnson' },
  { code: 'DE', name: 'Germany', flag: '\u{1F1E9}\u{1F1EA}', currency: 'EUR', region: 'EMEA', directorId: 'user-3', directorName: 'Hans Mueller' },
  { code: 'FR', name: 'France', flag: '\u{1F1EB}\u{1F1F7}', currency: 'EUR', region: 'EMEA', directorId: 'user-4', directorName: 'Marie Dupont' },
  { code: 'JP', name: 'Japan', flag: '\u{1F1EF}\u{1F1F5}', currency: 'JPY', region: 'APAC', directorId: 'user-5', directorName: 'Tanaka San' },
  { code: 'AU', name: 'Australia', flag: '\u{1F1E6}\u{1F1FA}', currency: 'AUD', region: 'APAC', directorId: 'user-6', directorName: 'Emma Wilson' },
  { code: 'CA', name: 'Canada', flag: '\u{1F1E8}\u{1F1E6}', currency: 'CAD', region: 'North America', directorId: 'user-7', directorName: 'Michael Brown' },
  { code: 'BR', name: 'Brazil', flag: '\u{1F1E7}\u{1F1F7}', currency: 'BRL', region: 'LATAM', directorId: 'user-8', directorName: 'Carlos Silva' },
];

// Campaign Mock Data
export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Q1 Brand Awareness Campaign',
    description: 'Global brand awareness campaign focusing on digital channels',
    status: 'active',
    type: 'awareness',
    channels: ['social', 'display', 'video'],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 50000, targetAudience: 'Professionals 25-45' },
      { countryCode: 'UK', countryName: 'United Kingdom', budget: 30000, targetAudience: 'Professionals 25-45' },
      { countryCode: 'DE', countryName: 'Germany', budget: 25000, targetAudience: 'Professionals 25-45' },
    ],
    budget: {
      total: 105000,
      spent: 67500,
      remaining: 37500,
      currency: 'USD',
    },
    dates: {
      start: new Date('2024-01-01'),
      end: new Date('2024-03-31'),
      createdAt: new Date('2023-12-15'),
      updatedAt: new Date('2024-02-01'),
    },
    metrics: {
      impressions: 12500000,
      clicks: 450000,
      conversions: 8500,
      cost: 67500,
      revenue: 127500,
      leads: 3200,
      ctr: 3.6,
      cpc: 0.15,
      cpa: 7.94,
      roas: 1.89,
      engagement: 4.2,
    },
    owner: { id: 'user-1', name: 'John Smith', email: 'john.smith@gogidix.com' },
    brand: { id: 'brand-1', name: 'Gogidix' },
    tags: ['brand-awareness', 'q1-2024', 'global'],
    objectives: ['Increase brand awareness', 'Generate leads'],
    kpis: [
      { name: 'Impressions', target: 15000000, current: 12500000, unit: '' },
      { name: 'CTR', target: 4, current: 3.6, unit: '%' },
      { name: 'Leads', target: 5000, current: 3200, unit: '' },
    ],
  },
  {
    id: 'camp-2',
    name: 'Product Launch - Email Sequence',
    description: 'Email marketing campaign for new product launch',
    status: 'active',
    type: 'conversion',
    channels: ['email'],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 15000, targetAudience: 'Existing customers' },
    ],
    budget: {
      total: 15000,
      spent: 12000,
      remaining: 3000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2024-01-15'),
      end: new Date('2024-02-28'),
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-02-01'),
    },
    metrics: {
      impressions: 250000,
      clicks: 45000,
      conversions: 1200,
      cost: 12000,
      revenue: 84000,
      leads: 1200,
      ctr: 18,
      cpc: 0.27,
      cpa: 10,
      roas: 7,
      engagement: 12.5,
    },
    owner: { id: 'user-2', name: 'Sarah Johnson', email: 'sarah.j@gogidix.com' },
    brand: { id: 'brand-1', name: 'Gogidix' },
    tags: ['product-launch', 'email', 'conversion'],
    objectives: ['Drive conversions', 'Launch new product'],
    kpis: [
      { name: 'Open Rate', target: 25, current: 22, unit: '%' },
      { name: 'Conversion Rate', target: 3, current: 2.7, unit: '%' },
      { name: 'Revenue', target: 100000, current: 84000, unit: '$' },
    ],
  },
  {
    id: 'camp-3',
    name: 'APAC Market Expansion',
    description: 'Multi-channel campaign for APAC market expansion',
    status: 'active',
    type: 'awareness',
    channels: ['social', 'search', 'display'],
    countries: [
      { countryCode: 'JP', countryName: 'Japan', budget: 40000, targetAudience: 'Business professionals' },
      { countryCode: 'AU', countryName: 'Australia', budget: 25000, targetAudience: 'Business professionals' },
    ],
    budget: {
      total: 65000,
      spent: 42000,
      remaining: 23000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2024-01-01'),
      end: new Date('2024-06-30'),
      createdAt: new Date('2023-12-01'),
      updatedAt: new Date('2024-02-01'),
    },
    metrics: {
      impressions: 8500000,
      clicks: 280000,
      conversions: 4200,
      cost: 42000,
      revenue: 92000,
      leads: 1800,
      ctr: 3.29,
      cpc: 0.15,
      cpa: 10,
      roas: 2.19,
      engagement: 3.8,
    },
    owner: { id: 'user-5', name: 'Tanaka San', email: 'tanaka@gogidix.com' },
    brand: { id: 'brand-1', name: 'Gogidix' },
    tags: ['apac', 'expansion', 'q1-q2-2024'],
    objectives: ['Market expansion', 'Brand awareness'],
    kpis: [
      { name: 'Market Penetration', target: 5, current: 3.2, unit: '%' },
      { name: 'Lead Generation', target: 3000, current: 1800, unit: '' },
    ],
  },
  {
    id: 'camp-4',
    name: 'EMEA Customer Retention',
    description: 'Retention campaign for EMEA customers',
    status: 'paused',
    type: 'retention',
    channels: ['email', 'social'],
    countries: [
      { countryCode: 'UK', countryName: 'United Kingdom', budget: 20000, targetAudience: 'Existing customers' },
      { countryCode: 'DE', countryName: 'Germany', budget: 15000, targetAudience: 'Existing customers' },
      { countryCode: 'FR', countryName: 'France', budget: 15000, targetAudience: 'Existing customers' },
    ],
    budget: {
      total: 50000,
      spent: 35000,
      remaining: 15000,
      currency: 'EUR',
    },
    dates: {
      start: new Date('2024-01-01'),
      end: new Date('2024-03-31'),
      createdAt: new Date('2023-12-10'),
      updatedAt: new Date('2024-01-28'),
    },
    metrics: {
      impressions: 1200000,
      clicks: 85000,
      conversions: 2100,
      cost: 35000,
      revenue: 105000,
      leads: 2100,
      ctr: 7.08,
      cpc: 0.41,
      cpa: 16.67,
      roas: 3,
      engagement: 5.5,
    },
    owner: { id: 'user-3', name: 'Hans Mueller', email: 'hans.m@gogidix.com' },
    brand: { id: 'brand-1', name: 'Gogidix' },
    tags: ['retention', 'emea', 'email'],
    objectives: ['Customer retention', 'Upsell opportunities'],
    kpis: [
      { name: 'Retention Rate', target: 85, current: 78, unit: '%' },
      { name: 'Churn Rate', target: 5, current: 6.2, unit: '%' },
    ],
  },
  {
    id: 'camp-5',
    name: 'Summer Webinar Series',
    description: 'Educational webinar series targeting new prospects',
    status: 'scheduled',
    type: 'consideration',
    channels: ['email', 'social', 'webinars'],
    countries: [
      { countryCode: 'US', countryName: 'United States', budget: 25000, targetAudience: 'Prospects' },
    ],
    budget: {
      total: 25000,
      spent: 0,
      remaining: 25000,
      currency: 'USD',
    },
    dates: {
      start: new Date('2024-06-01'),
      end: new Date('2024-08-31'),
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
    },
    metrics: {
      impressions: 0,
      clicks: 0,
      conversions: 0,
      cost: 0,
      revenue: 0,
      leads: 0,
      ctr: 0,
      cpc: 0,
      cpa: 0,
      roas: 0,
      engagement: 0,
    },
    owner: { id: 'user-1', name: 'John Smith', email: 'john.smith@gogidix.com' },
    brand: { id: 'brand-1', name: 'Gogidix' },
    tags: ['webinar', 'education', 'summer-2024'],
    objectives: ['Lead generation', 'Brand education'],
    kpis: [
      { name: 'Registrations', target: 5000, current: 0, unit: '' },
      { name: 'Attendance Rate', target: 60, current: 0, unit: '%' },
    ],
  },
];

// Budget Mock Data
export const mockBudgets: Budget[] = [
  {
    id: 'budget-1',
    name: '2024 Q1 Marketing Budget',
    fiscalYear: 2024,
    quarter: 1,
    totalAmount: 500000,
    spentAmount: 325000,
    remainingAmount: 175000,
    currency: 'USD',
    status: 'active',
    allocations: [
      { countryId: 'US', countryName: 'United States', amount: 200000, spent: 135000, remaining: 65000, percentage: 40 },
      { countryId: 'UK', countryName: 'United Kingdom', amount: 100000, spent: 65000, remaining: 35000, percentage: 20 },
      { countryId: 'DE', countryName: 'Germany', amount: 80000, spent: 52000, remaining: 28000, percentage: 16 },
      { countryId: 'JP', countryName: 'Japan', amount: 70000, spent: 42000, remaining: 28000, percentage: 14 },
      { countryId: 'AU', countryName: 'Australia', amount: 50000, spent: 31000, remaining: 19000, percentage: 10 },
    ],
    categories: [
      { channel: 'social', amount: 150000, percentage: 30 },
      { channel: 'search', amount: 125000, percentage: 25 },
      { channel: 'email', amount: 75000, percentage: 15 },
      { channel: 'display', amount: 75000, percentage: 15 },
      { channel: 'video', amount: 50000, percentage: 10 },
      { channel: 'webinars', amount: 25000, percentage: 5 },
    ],
    approval: {
      requestedBy: 'user-1',
      requestedAt: new Date('2023-12-01'),
      approvedBy: 'user-9',
      approvedAt: new Date('2023-12-05'),
      status: 'approved',
    },
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'budget-2',
    name: '2024 Q2 Marketing Budget',
    fiscalYear: 2024,
    quarter: 2,
    totalAmount: 550000,
    spentAmount: 45000,
    remainingAmount: 505000,
    currency: 'USD',
    status: 'active',
    allocations: [
      { countryId: 'US', countryName: 'United States', amount: 220000, spent: 18000, remaining: 202000, percentage: 40 },
      { countryId: 'UK', countryName: 'United Kingdom', amount: 110000, spent: 9000, remaining: 101000, percentage: 20 },
      { countryId: 'DE', countryName: 'Germany', amount: 88000, spent: 7200, remaining: 80800, percentage: 16 },
      { countryId: 'JP', countryName: 'Japan', amount: 77000, spent: 6300, remaining: 70700, percentage: 14 },
      { countryId: 'AU', countryName: 'Australia', amount: 55000, spent: 4500, remaining: 50500, percentage: 10 },
    ],
    categories: [
      { channel: 'social', amount: 165000, percentage: 30 },
      { channel: 'search', amount: 137500, percentage: 25 },
      { channel: 'email', amount: 82500, percentage: 15 },
      { channel: 'display', amount: 82500, percentage: 15 },
      { channel: 'video', amount: 55000, percentage: 10 },
      { channel: 'webinars', amount: 27500, percentage: 5 },
    ],
    approval: {
      requestedBy: 'user-1',
      requestedAt: new Date('2024-02-15'),
      approvedBy: 'user-9',
      approvedAt: new Date('2024-02-20'),
      status: 'approved',
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-15'),
  },
];

// Lead Mock Data
export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@company.com',
    phone: '+1-555-0101',
    company: 'Tech Corp',
    jobTitle: 'Marketing Director',
    status: 'qualified',
    quality: 'hot',
    source: 'linkedin',
    campaign: { id: 'camp-1', name: 'Q1 Brand Awareness Campaign', channel: 'social' },
    country: { code: 'US', name: 'United States' },
    assignedTo: { id: 'user-1', name: 'John Smith', email: 'john.smith@gogidix.com' },
    value: { estimated: 25000, currency: 'USD' },
    score: 85,
    activities: [
      { type: 'email_open', description: 'Opened product brochure email', timestamp: new Date('2024-02-01') },
      { type: 'webinar_registration', description: 'Registered for webinar', timestamp: new Date('2024-02-05') },
    ],
    customFields: {},
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'lead-2',
    firstName: 'Emma',
    lastName: 'Schmidt',
    email: 'e.schmidt@gmbh.de',
    company: 'Digital Solutions GmbH',
    jobTitle: 'CEO',
    status: 'proposal',
    quality: 'hot',
    source: 'event',
    campaign: { id: 'camp-3', name: 'APAC Market Expansion', channel: 'events' },
    country: { code: 'DE', name: 'Germany' },
    assignedTo: { id: 'user-3', name: 'Hans Mueller', email: 'hans.m@gogidix.com' },
    value: { estimated: 75000, actual: 65000, currency: 'EUR' },
    score: 92,
    activities: [
      { type: 'meeting', description: 'Product demo meeting completed', timestamp: new Date('2024-02-01') },
      { type: 'proposal_sent', description: 'Proposal sent to client', timestamp: new Date('2024-02-03') },
    ],
    customFields: {},
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-03'),
    convertedAt: new Date('2024-02-05'),
  },
  {
    id: 'lead-3',
    firstName: 'Yuki',
    lastName: 'Tanaka',
    email: 'yuki.tanaka@co.jp',
    company: 'Tokyo Innovations',
    jobTitle: 'Product Manager',
    status: 'contacted',
    quality: 'warm',
    source: 'webinar',
    campaign: { id: 'camp-3', name: 'APAC Market Expansion', channel: 'webinars' },
    country: { code: 'JP', name: 'Japan' },
    assignedTo: { id: 'user-5', name: 'Tanaka San', email: 'tanaka@gogidix.com' },
    value: { estimated: 35000, currency: 'USD' },
    score: 65,
    activities: [
      { type: 'webinar_attended', description: 'Attended product webinar', timestamp: new Date('2024-02-01') },
      { type: 'call', description: 'Initial discovery call', timestamp: new Date('2024-02-04') },
    ],
    customFields: {},
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: 'lead-4',
    firstName: 'Sophie',
    lastName: 'Martin',
    email: 'sophie.martin@entreprise.fr',
    company: 'Solutions Entreprise',
    jobTitle: 'CMO',
    status: 'new',
    quality: 'cold',
    source: 'content',
    campaign: { id: 'camp-4', name: 'EMEA Customer Retention', channel: 'content' },
    country: { code: 'FR', name: 'France' },
    value: { estimated: 15000, currency: 'EUR' },
    score: 45,
    activities: [
      { type: 'form_submit', description: 'Downloaded whitepaper', timestamp: new Date('2024-02-05') },
    ],
    customFields: {},
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
];

// Social Post Mock Data
export const mockSocialPosts: SocialPost[] = [
  {
    id: 'social-1',
    content: 'Excited to announce our latest product launch! Transform your business with Gogidix AI-powered solutions. #Innovation #AI #ProductLaunch',
    platform: 'linkedin',
    status: 'published',
    publishedAt: new Date('2024-02-01T10:00:00'),
    metrics: {
      impressions: 45000,
      reach: 38000,
      engagement: 1250,
      likes: 580,
      comments: 85,
      shares: 120,
      clicks: 465,
      saves: 85,
    },
    country: 'US',
    createdBy: 'user-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'social-2',
    content: 'Join our webinar tomorrow! Learn how to maximize your marketing ROI with our expert tips. Register now: link.gogidix.com/webinar',
    platform: 'twitter',
    status: 'published',
    publishedAt: new Date('2024-02-04T14:30:00'),
    metrics: {
      impressions: 125000,
      reach: 98000,
      engagement: 3200,
      likes: 1850,
      comments: 180,
      shares: 650,
      clicks: 520,
      saves: 120,
    },
    country: 'US',
    createdBy: 'user-2',
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
  {
    id: 'social-3',
    content: 'Behind the scenes at Gogidix! Our team celebrating another successful quarter. #Teamwork #Success #Culture',
    platform: 'instagram',
    status: 'published',
    media: [
      { type: 'image', url: 'https://example.com/team-photo.jpg' },
    ],
    publishedAt: new Date('2024-02-02T16:00:00'),
    metrics: {
      impressions: 28000,
      reach: 24000,
      engagement: 2100,
      likes: 1650,
      comments: 95,
      shares: 45,
      clicks: 310,
      saves: 280,
    },
    country: 'UK',
    createdBy: 'user-2',
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
];

// Content Mock Data
export const mockContent: Content[] = [
  {
    id: 'content-1',
    title: '10 Marketing Trends to Watch in 2024',
    type: 'blog_post',
    status: 'published',
    excerpt: 'Discover the top marketing trends that will shape 2024 and how to leverage them for your business.',
    content: 'Full article content here...',
    author: { id: 'user-1', name: 'John Smith', avatar: '' },
    brandId: 'brand-1',
    campaignIds: ['camp-1'],
    tags: ['marketing', 'trends', '2024'],
    categories: ['Marketing Strategy'],
    seo: {
      title: '10 Marketing Trends to Watch in 2024 | Gogidix Blog',
      description: 'Discover the top marketing trends for 2024',
      keywords: ['marketing trends', '2024 marketing', 'digital marketing'],
      slug: '10-marketing-trends-2024',
    },
    publishing: {
      publishedAt: new Date('2024-01-15'),
      channels: ['blog', 'linkedin', 'twitter'],
      countries: ['US', 'UK', 'DE'],
    },
    metrics: {
      views: 12500,
      clicks: 3200,
      shares: 180,
      comments: 45,
      downloads: 0,
      leads: 420,
      engagementRate: 3.2,
    },
    approval: {
      status: 'approved',
      approvedBy: 'user-9',
      approvedAt: new Date('2024-01-10'),
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
];

// Global Dashboard Summary
export const mockGlobalDashboardSummary: GlobalDashboardSummary = {
  period: {
    start: new Date('2024-01-01'),
    end: new Date('2024-02-01'),
    type: 'monthly',
  },
  globalMetrics: {
    campaigns: { value: 24, label: '24 Active', change: 12, changeType: 'increase' },
    budget: { value: 1200000, label: '$1.2M', change: 8, changeType: 'increase', target: 1500000, attainment: 80 },
    spent: { value: 720000, label: '$720K', change: 15, changeType: 'increase' },
    revenue: { value: 2150000, label: '$2.15M', change: 22, changeType: 'increase' },
    leads: { value: 8500, label: '8,500', change: 18, changeType: 'increase' },
    conversions: { value: 1200, label: '1,200', change: 25, changeType: 'increase' },
    impressions: { value: 45000000, label: '45M', change: -5, changeType: 'decrease' },
    avgROAS: { value: 2.98, label: '2.98x', change: 8, changeType: 'increase' },
    avgROI: { value: 198, label: '198%', change: 12, changeType: 'increase' },
  },
  countriesSummary: mockCountries.map((country, index) => ({
    country,
    metrics: {
      budget: 150000 + index * 20000,
      spent: 90000 + index * 15000,
      revenue: 250000 + index * 30000,
      leads: 1000 + index * 200,
      conversions: 150 + index * 30,
      impressions: 5000000 + index * 1000000,
      clicks: 150000 + index * 30000,
      roi: 180 + index * 10,
      roas: 2.8 + index * 0.2,
    },
    trend: ['up', 'down', 'neutral'][index % 3] as 'up' | 'down' | 'neutral',
    status: ['on_track', 'at_risk', 'off_track'][index % 3] as 'on_track' | 'at_risk' | 'off_track',
  })),
  topCampaigns: mockCampaigns.slice(0, 5).map((campaign, index) => ({
    id: campaign.id,
    name: campaign.name,
    country: mockCountries[index % mockCountries.length],
    channel: campaign.channels[0],
    revenue: campaign.metrics.revenue,
    budget: campaign.budget.total,
    roi: campaign.metrics.roi,
    leads: campaign.metrics.leads,
    rank: index + 1,
  })),
  alerts: [
    {
      id: 'alert-1',
      type: 'warning',
      category: 'budget',
      title: 'Budget Alert: Germany',
      message: 'Germany campaign budget is 85% utilized with 3 weeks remaining.',
      severity: 'medium',
      createdAt: new Date('2024-02-05'),
      read: false,
    },
    {
      id: 'alert-2',
      type: 'success',
      category: 'campaign',
      title: 'Campaign Milestone',
      message: 'Q1 Brand Awareness Campaign reached 10M impressions!',
      severity: 'low',
      createdAt: new Date('2024-02-04'),
      read: false,
    },
  ],
};

// Brand Mock Data
export const mockBrands: Brand[] = [
  {
    id: 'brand-1',
    name: 'Gogidix',
    description: 'Primary corporate brand',
    logo: '/logos/gogidix.png',
    status: 'active',
    colors: {
      primary: '#6366f1',
      secondary: '#8b5cf6',
      accent: '#ec4899',
      neutral: ['#f9fafb', '#e5e7eb', '#d1d5db', '#9ca3af', '#6b7280', '#374151', '#1f2937'],
    },
    typography: {
      primary: 'Inter',
      secondary: 'Roboto',
      headings: 'Montserrat',
    },
    tone: ['Professional', 'Innovative', 'Trustworthy', 'Dynamic'],
    taglines: ['Transform Your Business', 'AI-Powered Solutions', 'Future Ready'],
    assets: [],
    guidelines: [],
    regions: ['US', 'UK', 'DE', 'FR', 'JP', 'AU'],
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
