// Mock Data: Leads
// Comprehensive mock data for lead generation and tracking

import { Lead, LeadStatus, LeadSource, LeadQuality, LeadMetrics } from '../../domain/entities/Lead.entity';

const mockLeads: Lead[] = [
  {
    id: 'lead-001',
    firstName: 'Robert',
    lastName: 'Anderson',
    email: 'robert.anderson@techcorp.com',
    phone: '+1-555-0101',
    company: 'TechCorp Industries',
    jobTitle: 'CTO',
    status: LeadStatus.QUALIFIED,
    quality: LeadQuality.HOT,
    source: LeadSource.SEARCH_ENGINE,
    campaign: {
      id: 'camp-002',
      name: 'EMEA Product Launch - Enterprise Edition',
      channel: 'search',
    },
    country: {
      code: 'US',
      name: 'United States',
    },
    assignedTo: {
      id: 'user-201',
      name: 'Jennifer Walsh',
      email: 'jennifer.walsh@gogidix.com',
    },
    value: {
      estimated: 125000,
      currency: 'USD',
    },
    score: 92,
    activities: [
      { type: 'form_submit', description: 'Submitted demo request form', timestamp: new Date('2026-02-15T10:30:00') },
      { type: 'email_open', description: 'Opened follow-up email', timestamp: new Date('2026-02-15T14:22:00') },
      { type: 'webinar_register', description: 'Registered for enterprise webinar', timestamp: new Date('2026-02-16T09:15:00') },
      { type: 'call', description: 'Discovery call completed', timestamp: new Date('2026-02-17T15:00:00') },
    ],
    customFields: {
      companySize: '1000+',
      industry: 'Technology',
      purchaseTimeline: '1-3 months',
    },
    createdAt: new Date('2026-02-15T10:30:00'),
    updatedAt: new Date('2026-02-17T16:30:00'),
  },
  {
    id: 'lead-002',
    firstName: 'Sophie',
    lastName: 'Martin',
    email: 'sophie.martin@innovate.fr',
    phone: '+33-1-42-86-55-44',
    company: 'Innovate SAS',
    jobTitle: 'Marketing Director',
    status: LeadStatus.NEW,
    quality: LeadQuality.WARM,
    source: LeadSource.LINKEDIN,
    campaign: {
      id: 'camp-002',
      name: 'EMEA Product Launch - Enterprise Edition',
      channel: 'social',
    },
    country: {
      code: 'FR',
      name: 'France',
    },
    assignedTo: {
      id: 'user-202',
      name: 'Pierre Dubois',
      email: 'pierre.dubois@gogidix.com',
    },
    value: {
      estimated: 75000,
      currency: 'EUR',
    },
    score: 78,
    activities: [
      { type: 'ad_click', description: 'Clicked LinkedIn ad', timestamp: new Date('2026-02-18T08:45:00') },
      { type: 'landing_page', description: 'Visited landing page', timestamp: new Date('2026-02-18T08:46:00') },
      { type: 'form_submit', description: 'Submitted contact form', timestamp: new Date('2026-02-18T09:12:00') },
    ],
    customFields: {
      companySize: '50-200',
      industry: 'Marketing Services',
      purchaseTimeline: '3-6 months',
    },
    createdAt: new Date('2026-02-18T09:12:00'),
    updatedAt: new Date('2026-02-18T09:12:00'),
  },
  {
    id: 'lead-003',
    firstName: 'Hans',
    lastName: 'Weber',
    email: 'h.weber@manufacturing.de',
    phone: '+49-89-123-4567',
    company: 'Weber Manufacturing GmbH',
    jobTitle: 'Head of Digital Transformation',
    status: LeadStatus.CONTACTED,
    quality: LeadQuality.WARM,
    source: LeadSource.EVENT,
    campaign: {
      id: 'camp-006',
      name: 'Industry Events - Q1 2026',
      channel: 'events',
    },
    country: {
      code: 'DE',
      name: 'Germany',
    },
    assignedTo: {
      id: 'user-203',
      name: 'Anna Schmidt',
      email: 'anna.schmidt@gogidix.com',
    },
    value: {
      estimated: 150000,
      currency: 'EUR',
    },
    score: 85,
    activities: [
      { type: 'event_meeting', description: 'Met at Hannover Messe', timestamp: new Date('2026-02-10T14:30:00') },
      { type: 'email_send', description: 'Sent follow-up email with brochure', timestamp: new Date('2026-02-11T10:00:00') },
      { type: 'email_open', description: 'Opened follow-up email', timestamp: new Date('2026-02-11T14:22:00') },
      { type: 'call', description: 'Initial discovery call', timestamp: new Date('2026-02-14T11:00:00') },
    ],
    customFields: {
      companySize: '500-1000',
      industry: 'Manufacturing',
      purchaseTimeline: '3-6 months',
      budgetApproved: 'true',
    },
    createdAt: new Date('2026-02-10T14:30:00'),
    updatedAt: new Date('2026-02-14T12:00:00'),
  },
  {
    id: 'lead-004',
    firstName: 'Emma',
    lastName: 'Thompson',
    email: 'emma.t@financialservices.co.uk',
    phone: '+44-20-7123-4567',
    company: 'Financial Services Ltd',
    jobTitle: 'Operations Manager',
    status: LeadStatus.NEGOTIATION,
    quality: LeadQuality.HOT,
    source: LeadSource.REFERRAL,
    campaign: {
      id: 'camp-004',
      name: 'North America Retention Campaign',
      channel: 'email',
    },
    country: {
      code: 'GB',
      name: 'United Kingdom',
    },
    assignedTo: {
      id: 'user-201',
      name: 'Jennifer Walsh',
      email: 'jennifer.walsh@gogidix.com',
    },
    value: {
      estimated: 200000,
      actual: 185000,
      currency: 'GBP',
    },
    score: 95,
    activities: [
      { type: 'referral', description: 'Referred by existing customer', timestamp: new Date('2026-01-20T10:00:00') },
      { type: 'demo', description: 'Product demo completed', timestamp: new Date('2026-01-25T15:00:00') },
      { type: 'proposal', description: 'Proposal sent', timestamp: new Date('2026-02-01T11:00:00') },
      { type: 'meeting', description: 'Contract negotiation meeting', timestamp: new Date('2026-02-15T14:00:00') },
    ],
    customFields: {
      companySize: '200-500',
      industry: 'Financial Services',
      purchaseTimeline: '1-3 months',
      budgetApproved: 'true',
      decisionMaker: 'CFO',
    },
    createdAt: new Date('2026-01-20T10:00:00'),
    updatedAt: new Date('2026-02-15T16:00:00'),
  },
  {
    id: 'lead-005',
    firstName: 'Takeshi',
    lastName: 'Yamamoto',
    email: 'yamamoto.t@techjapan.co.jp',
    phone: '+81-3-1234-5678',
    company: 'Tech Japan Corporation',
    jobTitle: 'General Manager',
    status: LeadStatus.NEW,
    quality: LeadQuality.WARM,
    source: LeadSource.WEBSITE,
    campaign: {
      id: 'camp-003',
      name: 'APAC Expansion - Phase 1',
      channel: 'search',
    },
    country: {
      code: 'JP',
      name: 'Japan',
    },
    value: {
      estimated: 180000,
      currency: 'USD',
    },
    score: 72,
    activities: [
      { type: 'organic_search', description: 'Found via organic search', timestamp: new Date('2026-02-17T03:45:00') },
      { type: 'page_visit', description: 'Visited pricing page', timestamp: new Date('2026-02-17T04:12:00') },
      { type: 'form_submit', description: 'Submitted contact form', timestamp: new Date('2026-02-17T04:30:00') },
    ],
    customFields: {
      companySize: '100-500',
      industry: 'Technology',
      purchaseTimeline: '6-12 months',
      languagePreference: 'Japanese',
    },
    createdAt: new Date('2026-02-17T04:30:00'),
    updatedAt: new Date('2026-02-17T04:30:00'),
  },
  {
    id: 'lead-006',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@retailbrasil.com.br',
    phone: '+55-11-9876-5432',
    company: 'Retail Brasil',
    jobTitle: 'E-commerce Manager',
    status: LeadStatus.CONTACTED,
    quality: LeadQuality.COLD,
    source: LeadSource.SOCIAL_MEDIA,
    campaign: {
      id: 'camp-001',
      name: 'Q1 Global Brand Awareness',
      channel: 'social',
    },
    country: {
      code: 'BR',
      name: 'Brazil',
    },
    value: {
      estimated: 45000,
      currency: 'BRL',
    },
    score: 55,
    activities: [
      { type: 'ad_click', description: 'Clicked Facebook ad', timestamp: new Date('2026-02-10T10:30:00') },
      { type: 'form_submit', description: 'Downloaded whitepaper', timestamp: new Date('2026-02-10T11:00:00') },
      { type: 'email_send', description: 'Welcome email sent', timestamp: new Date('2026-02-10T11:05:00') },
    ],
    customFields: {
      companySize: '50-200',
      industry: 'Retail',
      purchaseTimeline: '6+ months',
    },
    createdAt: new Date('2026-02-10T11:00:00'),
    updatedAt: new Date('2026-02-10T11:05:00'),
  },
  {
    id: 'lead-007',
    firstName: 'Liam',
    lastName: 'O\'Connor',
    email: 'liam.oc@startupdublin.ie',
    phone: '+353-1-234-5678',
    company: 'Startup Dublin',
    jobTitle: 'Founder & CEO',
    status: LeadStatus.QUALIFIED,
    quality: LeadQuality.HOT,
    source: LeadSource.CONTENT,
    campaign: {
      id: 'camp-002',
      name: 'EMEA Product Launch - Enterprise Edition',
      channel: 'content',
    },
    country: {
      code: 'IE',
      name: 'Ireland',
    },
    assignedTo: {
      id: 'user-202',
      name: 'Pierre Dubois',
      email: 'pierre.dubois@gogidix.com',
    },
    value: {
      estimated: 95000,
      currency: 'EUR',
    },
    score: 88,
    activities: [
      { type: 'blog_read', description: 'Read multiple blog posts', timestamp: new Date('2026-02-12T09:00:00') },
      { type: 'case_study_download', description: 'Downloaded case study', timestamp: new Date('2026-02-12T10:30:00') },
      { type: 'form_submit', description: 'Requested demo', timestamp: new Date('2026-02-12T11:00:00') },
      { type: 'demo', description: 'Completed product demo', timestamp: new Date('2026-02-14T15:00:00') },
    ],
    customFields: {
      companySize: '10-50',
      industry: 'SaaS',
      purchaseTimeline: '1-3 months',
      funding: 'Series A',
    },
    createdAt: new Date('2026-02-12T11:00:00'),
    updatedAt: new Date('2026-02-14T16:00:00'),
  },
  {
    id: 'lead-008',
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@asiapacific.com.sg',
    phone: '+65-6789-0123',
    company: 'Asia Pacific Holdings',
    jobTitle: 'VP of Technology',
    status: LeadStatus.PROPOSAL,
    quality: LeadQuality.HOT,
    source: LeadSource.EMAIL,
    campaign: {
      id: 'camp-008',
      name: 'Partner Co-Marketing Program',
      channel: 'email',
    },
    country: {
      code: 'SG',
      name: 'Singapore',
    },
    assignedTo: {
      id: 'user-204',
      name: 'Aisha Rahman',
      email: 'aisha.rahman@gogidix.com',
    },
    value: {
      estimated: 350000,
      currency: 'USD',
    },
    score: 90,
    activities: [
      { type: 'email_click', description: 'Clicked partner email', timestamp: new Date('2026-02-05T08:00:00') },
      { type: 'landing_page', description: 'Visited partner landing page', timestamp: new Date('2026-02-05T08:05:00') },
      { type: 'form_submit', description: 'Submitted inquiry form', timestamp: new Date('2026-02-05T08:30:00') },
      { type: 'call', description: 'Discovery call completed', timestamp: new Date('2026-02-08T14:00:00') },
      { type: 'demo', description: 'Technical demo for team', timestamp: new Date('2026-02-12T15:00:00') },
      { type: 'proposal', description: 'Custom proposal sent', timestamp: new Date('2026-02-16T11:00:00') },
    ],
    customFields: {
      companySize: '1000+',
      industry: 'Conglomerate',
      purchaseTimeline: '1-3 months',
      budgetApproved: 'true',
      decisionMaker: 'CTO',
    },
    createdAt: new Date('2026-02-05T08:30:00'),
    updatedAt: new Date('2026-02-16T12:00:00'),
  },
  {
    id: 'lead-009',
    firstName: 'Isabella',
    lastName: 'Rossi',
    email: 'i.rossi@fashionitalia.it',
    phone: '+39-02-1234-5678',
    company: 'Fashion Italia SpA',
    jobTitle: 'Brand Director',
    status: LeadStatus.WON,
    quality: LeadQuality.HOT,
    source: LeadSource.EVENT,
    campaign: {
      id: 'camp-006',
      name: 'Industry Events - Q1 2026',
      channel: 'events',
    },
    country: {
      code: 'IT',
      name: 'Italy',
    },
    assignedTo: {
      id: 'user-205',
      name: 'Marco Bellini',
      email: 'marco.bellini@gogidix.com',
    },
    value: {
      estimated: 80000,
      actual: 85000,
      currency: 'EUR',
    },
    score: 91,
    activities: [
      { type: 'event_meeting', description: 'Met at Milano Fashion Week', timestamp: new Date('2026-01-15T14:00:00') },
      { type: 'email_send', description: 'Follow-up email sent', timestamp: new Date('2026-01-16T10:00:00') },
      { type: 'call', description: 'Discovery call', timestamp: new Date('2026-01-20T15:00:00') },
      { type: 'demo', description: 'Brand demo presentation', timestamp: new Date('2026-01-25T14:00:00') },
      { type: 'proposal', description: 'Proposal sent', timestamp: new Date('2026-01-28T11:00:00') },
      { type: 'contract', description: 'Contract signed', timestamp: new Date('2026-02-10T16:00:00') },
    ],
    customFields: {
      companySize: '200-500',
      industry: 'Fashion & Luxury',
      purchaseTimeline: '1-3 months',
      budgetApproved: 'true',
    },
    createdAt: new Date('2026-01-15T14:00:00'),
    updatedAt: new Date('2026-02-10T17:00:00'),
    convertedAt: new Date('2026-02-10T16:00:00'),
  },
  {
    id: 'lead-010',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'jwilson@enterprise.ca',
    phone: '+1-416-555-0199',
    company: 'Enterprise Canada Corp',
    jobTitle: 'Director of IT',
    status: LeadStatus.LOST,
    quality: LeadQuality.WARM,
    source: LeadSource.ADVERTISEMENT,
    campaign: {
      id: 'camp-005',
      name: 'Holiday Season Promotion 2025',
      channel: 'display',
    },
    country: {
      code: 'CA',
      name: 'Canada',
    },
    assignedTo: {
      id: 'user-206',
      name: 'Sarah Tremblay',
      email: 'sarah.tremblay@gogidix.com',
    },
    value: {
      estimated: 120000,
      currency: 'CAD',
    },
    score: 68,
    activities: [
      { type: 'ad_click', description: 'Clicked display ad', timestamp: new Date('2025-12-10T10:00:00') },
      { type: 'form_submit', description: 'Submitted info request', timestamp: new Date('2025-12-10T10:30:00') },
      { type: 'email_send', description: 'Information pack sent', timestamp: new Date('2025-12-10T11:00:00') },
      { type: 'call', description: 'Initial call', timestamp: new Date('2025-12-15T14:00:00') },
      { type: 'demo', description: 'Product demo', timestamp: new Date('2025-12-20T15:00:00') },
      { type: 'rejection', description: 'Decided to go with competitor', timestamp: new Date('2026-01-15T10:00:00') },
    ],
    customFields: {
      companySize: '500-1000',
      industry: 'Enterprise Software',
      purchaseTimeline: '3-6 months',
      reason: 'Budget constraints',
      competitor: 'CompetitorX',
    },
    createdAt: new Date('2025-12-10T10:30:00'),
    updatedAt: new Date('2026-01-15T11:00:00'),
  },
];

export const mockLeadMetrics: LeadMetrics = {
  total: 15847,
  new: 2147,
  qualified: 5234,
  converted: 1847,
  conversionRate: 11.66,
  averageValue: 98500,
  totalValue: 1562450000,
  bySource: {
    [LeadSource.WEBSITE]: 4250,
    [LeadSource.EMAIL]: 3100,
    [LeadSource.SOCIAL_MEDIA]: 2850,
    [LeadSource.SEARCH_ENGINE]: 2450,
    [LeadSource.REFERRAL]: 1250,
    [LeadSource.EVENT]: 950,
    [LeadSource.ADVERTISEMENT]: 750,
    [LeadSource.CONTENT]: 247,
  },
  byCountry: {
    US: 4200,
    GB: 2100,
    DE: 1650,
    FR: 1200,
    CA: 1100,
    AU: 850,
    JP: 780,
    SG: 650,
    BR: 520,
    IN: 480,
    IT: 450,
    ES: 380,
    NL: 320,
    CH: 280,
    IE: 220,
    OTHER: 1707,
  },
  byCampaign: {
    'camp-001': 3850,
    'camp-002': 2450,
    'camp-004': 1850,
    'camp-005': 1650,
    'camp-006': 1250,
    'camp-008': 950,
    'other': 3847,
  },
};

export const mockGetLeadById = (id: string): Lead | undefined =>
  mockLeads.find(l => l.id === id);

export const mockLeadsByStatus = (status: LeadStatus): Lead[] =>
  mockLeads.filter(l => l.status === status);

export const mockLeadsByCountry = (countryCode: string): Lead[] =>
  mockLeads.filter(l => l.country.code === countryCode);

export default mockLeads;
