// Mock Data: Social Media Posts
// Comprehensive mock data for social media posts

import { SocialPost, SocialPlatform, SocialPostStatus } from '../../domain/types';

export const mockSocialPosts: SocialPost[] = [
  {
    id: 'social-001',
    content: 'Excited to announce our Q1 results! 🚀 We\'ve seen incredible growth across all markets. Thank you to our amazing team and clients! #MarketingSuccess #Gogidix',
    platform: 'linkedin',
    status: 'published',
    media: [],
    campaignId: 'camp-001',
    contentId: 'content-003',
    publishedAt: new Date('2026-02-10T14:30:00'),
    metrics: {
      impressions: 45230,
      reach: 38450,
      engagement: 8401,
      likes: 4520,
      comments: 387,
      shares: 1234,
      clicks: 6780,
      saves: 560,
    },
    country: 'US',
    createdBy: 'user-003',
    createdAt: new Date('2026-02-10T14:00:00'),
    updatedAt: new Date('2026-02-10T14:30:00'),
  },
  {
    id: 'social-002',
    content: 'New blog post alert! 📝 Learn about the top marketing trends for 2026. Link in bio! #MarketingTrends #DigitalMarketing',
    platform: 'twitter',
    status: 'published',
    media: [],
    campaignId: 'camp-001',
    contentId: 'content-001',
    publishedAt: new Date('2026-02-15T10:00:00'),
    metrics: {
      impressions: 12450,
      reach: 10200,
      engagement: 1820,
      likes: 980,
      comments: 45,
      shares: 320,
      clicks: 2340,
      saves: 75,
    },
    country: 'US',
    createdBy: 'user-003',
    createdAt: new Date('2026-02-15T09:30:00'),
    updatedAt: new Date('2026-02-15T10:00:00'),
  },
  {
    id: 'social-003',
    content: 'Beautiful sunset from our office today! Sometimes the best inspiration comes from nature 🌅 #OfficeLife #Sunset',
    platform: 'instagram',
    status: 'published',
    media: [
      {
        type: 'image',
        url: 'https://example.com/images/sunset.jpg',
        thumbnailUrl: 'https://example.com/images/sunset-thumb.jpg',
      },
    ],
    campaignId: 'camp-001',
    publishedAt: new Date('2026-02-18T18:00:00'),
    metrics: {
      impressions: 28750,
      reach: 24560,
      engagement: 4520,
      likes: 3840,
      comments: 156,
      shares: 89,
      clicks: 980,
      saves: 435,
    },
    country: 'US',
    createdBy: 'user-006',
    createdAt: new Date('2026-02-18T17:30:00'),
    updatedAt: new Date('2026-02-18T18:00:00'),
  },
  {
    id: 'social-004',
    content: 'Join us for our upcoming webinar on B2B marketing strategies! Link in bio to register 🎯 #Webinar #B2BMarketing',
    platform: 'linkedin',
    status: 'published',
    media: [],
    campaignId: 'camp-002',
    contentId: 'content-006',
    publishedAt: new Date('2026-02-20T09:00:00'),
    metrics: {
      impressions: 18560,
      reach: 15230,
      engagement: 2890,
      likes: 1560,
      comments: 89,
      shares: 234,
      clicks: 4230,
      saves: 320,
    },
    country: 'GB',
    createdBy: 'user-002',
    createdAt: new Date('2026-02-19T14:00:00'),
    updatedAt: new Date('2026-02-20T09:00:00'),
  },
  {
    id: 'social-005',
    content: 'Product launch email sequence template - now available! Download link in bio 📧 #EmailMarketing #Templates',
    platform: 'facebook',
    status: 'published',
    media: [
      {
        type: 'image',
        url: 'https://example.com/images/email-template.jpg',
      },
    ],
    campaignId: 'camp-001',
    contentId: 'content-007',
    publishedAt: new Date('2026-02-05T11:00:00'),
    metrics: {
      impressions: 8960,
      reach: 7240,
      engagement: 1456,
      likes: 980,
      comments: 67,
      shares: 123,
      clicks: 2340,
      saves: 286,
    },
    country: 'US',
    createdBy: 'user-003',
    createdAt: new Date('2026-02-05T10:30:00'),
    updatedAt: new Date('2026-02-05T11:00:00'),
  },
  {
    id: 'social-006',
    content: 'Quick tip: Personalization is key to email marketing success! Use recipient names and tailor content based on their interests 💡 #EmailTips #Marketing',
    platform: 'twitter',
    status: 'scheduled',
    media: [],
    campaignId: 'camp-001',
    scheduledFor: new Date('2026-02-25T14:00:00'),
    metrics: {
      impressions: 0,
      reach: 0,
      engagement: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      clicks: 0,
      saves: 0,
    },
    country: 'US',
    createdBy: 'user-003',
    createdAt: new Date('2026-02-20T10:00:00'),
    updatedAt: new Date('2026-02-20T10:00:00'),
  },
  {
    id: 'social-007',
    content: 'Team celebrating after another successful campaign launch! 🎉 Great work everyone! #TeamWork #MarketingLife',
    platform: 'instagram',
    status: 'draft',
    media: [
      {
        type: 'image',
        url: 'https://example.com/images/team.jpg',
      },
      {
        type: 'image',
        url: 'https://example.com/images/team2.jpg',
      },
    ],
    campaignId: 'camp-002',
    metrics: {
      impressions: 0,
      reach: 0,
      engagement: 0,
      likes: 0,
      comments: 0,
      shares: 0,
      clicks: 0,
      saves: 0,
    },
    country: 'US',
    createdBy: 'user-006',
    createdAt: new Date('2026-02-18T09:00:00'),
    updatedAt: new Date('2026-02-18T09:00:00'),
  },
  {
    id: 'social-008',
    content: 'Happy to announce our partnership with TechCorp! Together, we\'re transforming digital marketing. Read more at the link in bio 🤝 #Partnership #Growth',
    platform: 'linkedin',
    status: 'published',
    media: [],
    campaignId: 'camp-008',
    publishedAt: new Date('2026-02-12T10:00:00'),
    metrics: {
      impressions: 32450,
      reach: 28930,
      engagement: 5420,
      likes: 3240,
      comments: 234,
      shares: 567,
      clicks: 8920,
      saves: 435,
    },
    country: 'US',
    createdBy: 'user-007',
    createdAt: new Date('2026-02-11T14:00:00'),
    updatedAt: new Date('2026-02-12T10:00:00'),
  },
  {
    id: 'social-009',
    content: 'Tutorial: How to set up your first Facebook ad campaign in 5 minutes. Link in bio! 📱 #Tutorial #FacebookAds',
    platform: 'facebook',
    status: 'published',
    media: [
      {
        type: 'video',
        url: 'https://example.com/videos/tutorial.mp4',
        thumbnailUrl: 'https://example.com/images/tutorial-thumb.jpg',
      },
    ],
    campaignId: 'camp-001',
    publishedAt: new Date('2026-02-08T15:00:00'),
    metrics: {
      impressions: 15670,
      reach: 12890,
      engagement: 2130,
      likes: 1456,
      comments: 78,
      shares: 234,
      clicks: 5670,
      saves: 292,
    },
    country: 'US',
    createdBy: 'user-003',
    createdAt: new Date('2026-02-07T10:00:00'),
    updatedAt: new Date('2026-02-08T15:00:00'),
  },
  {
    id: 'social-010',
    content: 'Did you know? Video content gets 48% more views than text content. Time to start creating! 🎬 #VideoMarketing #Stats',
    platform: 'twitter',
    status: 'published',
    media: [],
    campaignId: 'camp-001',
    publishedAt: new Date('2026-02-14T12:00:00'),
    metrics: {
      impressions: 9870,
      reach: 8120,
      engagement: 1560,
      likes: 890,
      comments: 34,
      shares: 267,
      clicks: 1890,
      saves: 89,
    },
    country: 'GB',
    createdBy: 'user-002',
    createdAt: new Date('2026-02-14T11:30:00'),
    updatedAt: new Date('2026-02-14T12:00:00'),
  },
];

export const mockSocialPostsByPlatform = (platform: SocialPlatform): SocialPost[] =>
  mockSocialPosts.filter(p => p.platform === platform);

export const mockSocialPostsByStatus = (status: SocialPostStatus): SocialPost[] =>
  mockSocialPosts.filter(p => p.status === status);

export const mockGetSocialPostById = (id: string): SocialPost | undefined =>
  mockSocialPosts.find(p => p.id === id);

export default mockSocialPosts;
