apiVersion: v1
kind: Service
metadata:
  name: ai-notification-service
  namespace: ai-services
  labels:
    app: ai-notification-service
    team: team-f-ai-services
spec:
  type: ClusterIP
  selector:
    app: ai-notification-service
  ports:
  - name: http
    port: 8232
    targetPort: 8232
    protocol: TCP
