package com.gogidix.aiservices.leadgenerationaiservice.application.service;
import org.junit.jupiter.api.*; import com.gogidix.aiservices.leadgenerationaiservice.application.dto.request.*; import com.gogidix.aiservices.leadgenerationaiservice.application.dto.response.*; import com.gogidix.aiservices.leadgenerationaiservice.domain.aggregate.Lead; import com.gogidix.aiservices.leadgenerationaiservice.domain.model.*; import com.gogidix.aiservices.leadgenerationaiservice.domain.port.out.*; import com.gogidix.aiservices.leadgenerationaiservice.domain.policy.LeadScoringPolicy; import com.gogidix.aiservices.leadgenerationaiservice.shared.exception.LeadNotFoundException; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*; import static org.mockito.ArgumentMatchers.*; import java.util.*;
class LeadGenerationServiceTest {
    private LeadRepository repo; private LeadScoringEnginePort scoring; private LeadEnrichmentPort enrich; private EventPublisherPort events; private LeadScoringPolicy policy; private LeadGenerationService svc;
    @BeforeEach void setup() { repo = mock(LeadRepository.class); scoring = mock(LeadScoringEnginePort.class); enrich = mock(LeadEnrichmentPort.class); events = mock(EventPublisherPort.class); doNothing().when(events).publish(anyString(), anyMap()); policy = new LeadScoringPolicy(); svc = new LeadGenerationService(repo, scoring, enrich, events, policy); }
    private Lead mkLead() { var c = ContactInfo.builder().email("t@t.com").firstName("J").lastName("D").build(); var l = Lead.create(c); when(repo.save(any())).thenAnswer(a -> a.getArgument(0)); when(repo.findById(l.getLeadId().toString())).thenReturn(Optional.of(l)); return l; }
    @Test void createLead() { var req = CreateLeadRequest.builder().email("n@t.com").firstName("J").lastName("D").build(); when(enrich.enrichLead(any())).thenAnswer(a -> a.getArgument(0)); var r = svc.createLead(req); assertThat(r).isNotNull(); assertThat(r.getEmail()).isEqualTo("n@t.com"); }
    @Test void getLead() { var l = mkLead(); var r = svc.getLead(l.getLeadId().toString()); assertThat(r).isNotNull(); }
    @Test void getLeadNotFound() { when(repo.findById("x")).thenReturn(Optional.empty()); assertThatThrownBy(() -> svc.getLead("x")).isInstanceOf(LeadNotFoundException.class); }
    @Test void getByStatus() { when(repo.findByStatus(LeadStatus.NEW)).thenReturn(List.of()); assertThat(svc.getLeadsByStatus(LeadStatus.NEW)).isEmpty(); }
    @Test void getByOwner() { when(repo.findByOwnerId("o1")).thenReturn(List.of()); assertThat(svc.getLeadsByOwner("o1")).isEmpty(); }
    @Test void getTopLeads() { when(repo.findTopScores(5)).thenReturn(List.of()); assertThat(svc.getTopLeads(5)).isEmpty(); }
    @Test void updateStatusContacted() { var l = mkLead(); var req = UpdateLeadStatusRequest.builder().leadId(l.getLeadId().toString()).status(LeadStatus.CONTACTED).build(); var r = svc.updateStatus(req); assertThat(r.getStatus()).isEqualTo(LeadStatus.CONTACTED); }
    @Test void updateStatusLost() { var l = mkLead(); var req = UpdateLeadStatusRequest.builder().leadId(l.getLeadId().toString()).status(LeadStatus.LOST).lossReason(LeadLossReason.NOT_INTERESTED).build(); var r = svc.updateStatus(req); assertThat(r.getStatus()).isEqualTo(LeadStatus.LOST); }
    @Test void assignLead() { var l = mkLead(); var req = AssignLeadRequest.builder().leadId(l.getLeadId().toString()).ownerId("o1").ownerName("O").build(); var r = svc.assignLead(req); assertThat(r.getOwnerId()).isEqualTo("o1"); }
    @Test void addQualification() { var l = mkLead(); l.setScore(LeadScore.builder().leadId(l.getLeadId().toString()).score(60).build()); when(repo.findById(l.getLeadId().toString())).thenReturn(Optional.of(l)); var req = AddQualificationRequest.builder().leadId(l.getLeadId().toString()).criteria(QualificationCriteria.BUDGET_CONFIRMED).build(); var r = svc.addQualification(req); assertThat(r).isNotNull(); }
    @Test void addActivity() { var l = mkLead(); var req = AddActivityRequest.builder().leadId(l.getLeadId().toString()).type(ActivityType.EMAIL_SENT).description("d").createdBy("u").build(); var r = svc.addActivity(req); assertThat(r).isNotNull(); }
    @Test void deleteLead() { var l = mkLead(); assertThatCode(() -> svc.deleteLead(l.getLeadId().toString())).doesNotThrowAnyException(); }
    @Test void recalculateScore() { var l = mkLead(); l.setScore(LeadScore.builder().leadId(l.getLeadId().toString()).score(50).build()); when(repo.findById(l.getLeadId().toString())).thenReturn(Optional.of(l)); var r = svc.recalculateScore(l.getLeadId().toString()); assertThat(r).isNotNull(); }
}
