package com.gogidix.finance.cashflow.domain.port.in;

import com.gogidix.finance.cashflow.domain.model.CashflowForecast;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Cashflow Forecast Commands (Input Port)
 * Defines the input commands for cashflow forecast operations
 */
public interface CashflowForecastCommand {

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class CreateForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Name is required")
        private String name;

        private String description;

        @NotNull(message = "Start date is required")
        private LocalDate startDate;

        @NotNull(message = "End date is required")
        private LocalDate endDate;

        @NotNull(message = "Period is required")
        private CashflowForecast.ForecastPeriod period;

        @NotNull(message = "Scenario is required")
        private CashflowForecast.ForecastScenario scenario;

        @NotBlank(message = "Generated by is required")
        private String generatedBy;

        @NotNull(message = "Opening balance is required")
        private BigDecimal openingBalance;

        private CashflowForecast.ConfidenceLevel confidenceLevel;

        private List<String> tags;

        private String notes;

        private Boolean isBaseline;

        private String parentForecastId;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class UpdateForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        private String name;

        private String description;

        private BigDecimal openingBalance;

        private CashflowForecast.ConfidenceLevel confidenceLevel;

        private List<String> tags;

        private String notes;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class GenerateForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        private LocalDate startDate;

        private LocalDate endDate;

        private List<String> itemCategories;

        private List<String> costCenters;

        private List<String> projects;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class ApproveForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        @NotBlank(message = "Approved by is required")
        private String approvedBy;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class RejectForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        @NotBlank(message = "Rejected by is required")
        private String rejectedBy;

        private String reason;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class ArchiveForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class CreateNewVersionCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        @NotBlank(message = "Generated by is required")
        private String generatedBy;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class CalculateVarianceCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        @NotBlank(message = "Category is required")
        private String category;

        @NotNull(message = "Forecasted amount is required")
        private BigDecimal forecastedAmount;

        @NotNull(message = "Actual amount is required")
        private BigDecimal actualAmount;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class DeleteForecastCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    class SetConfidenceCommand {
        @NotBlank(message = "Tenant ID is required")
        private String tenantId;

        @NotBlank(message = "Forecast ID is required")
        private String forecastId;

        @NotNull(message = "Confidence level is required")
        private CashflowForecast.ConfidenceLevel confidenceLevel;

        private BigDecimal variancePercentage;
    }
}
