package com.gogidix.shared.warehousing.reorder.application.dto;

import com.gogidix.shared.warehousing.reorder.domain.entity.PurchaseOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * DTO for PurchaseOrder
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Data transfer object for purchase orders")
public class PurchaseOrderDTO {

    @Schema(description = "Unique identifier")
    private String id;

    @Schema(description = "Tenant identifier")
    private String tenantId;

    @Schema(description = "Purchase order number")
    private String orderNumber;

    @Schema(description = "Supplier ID")
    private String supplierId;

    @Schema(description = "Supplier name")
    private String supplierName;

    @Schema(description = "Order date")
    private LocalDate orderDate;

    @Schema(description = "Expected delivery date")
    private LocalDate expectedDeliveryDate;

    @Schema(description = "Actual delivery date")
    private LocalDate actualDeliveryDate;

    @Schema(description = "Order status")
    private PurchaseOrder.OrderStatus status;

    @Schema(description = "Order items")
    private List<PurchaseOrder.OrderItem> items;

    @Schema(description = "Total order amount")
    private Double totalAmount;

    @Schema(description = "Currency code")
    private String currencyCode;

    @Schema(description = "Payment terms")
    private String paymentTerms;

    @Schema(description = "Shipping terms")
    private String shippingTerms;

    @Schema(description = "Shipping address")
    private String shippingAddress;

    @Schema(description = "Billing address")
    private String billingAddress;

    @Schema(description = "Notes")
    private String notes;

    @Schema(description = "Internal notes")
    private String internalNotes;

    @Schema(description = "Requested by")
    private String requestedBy;

    @Schema(description = "Approved by")
    private String approvedBy;

    @Schema(description = "Approval date")
    private LocalDateTime approvalDate;

    @Schema(description = "Auto-generated flag")
    private Boolean autoGenerated;

    @Schema(description = "Creation timestamp")
    private LocalDateTime createdAt;

    @Schema(description = "Last update timestamp")
    private LocalDateTime updatedAt;
}
