import { Inject, Injectable } from '@nestjs/common';
import { startOfMonth, endOfMonth, addMonths } from 'date-fns';
import { ForecastModel, ForecastPeriod, ForecastGranularity, DEFAULT_FORECAST_HORIZON_MONTHS } from '../../shared/constants';
import { Forecast } from '../../domain/entities/forecast.entity';
import { RequestContextData } from '../../shared/request-context';
import {
  TriggerRollingForecastUseCase,
  TriggerRollingForecastInput,
  TriggerRollingForecastResult,
} from '../../domain/ports/in/trigger-rolling-forecast.use-case';
import { ForecastRepositoryPort } from '../../domain/ports/out/forecast.repository.port';
import { EventPublisherPort } from '../../domain/ports/out/event-publisher.port';
import { RollingForecastTriggeredEvent } from '../../domain/events/rolling-forecast-triggered.event';
import { GenerateForecastUseCase } from '../../domain/ports/in/generate-forecast.use-case';

@Injectable()
export class TriggerRollingForecastUseCaseImpl implements TriggerRollingForecastUseCase {
  constructor(
    @Inject('ForecastRepositoryPort')
    private readonly forecastRepository: ForecastRepositoryPort,
    @Inject('EventPublisherPort')
    private readonly eventPublisher: EventPublisherPort,
    @Inject('GenerateForecastUseCase')
    private readonly generateForecastUseCase: GenerateForecastUseCase,
  ) {}

  async execute(
    context: RequestContextData,
    input: TriggerRollingForecastInput,
  ): Promise<TriggerRollingForecastResult> {
    const triggeredBy = input.triggeredBy || 'MANUAL';
    const reason = input.reason || 'Manual rolling forecast trigger';

    // Find latest forecast for the granularity
    const previousForecast = await this.forecastRepository.findLatestByGranularity(
      context.tenantId,
      (input.granularity as ForecastGranularity) || ForecastGranularity.GLOBAL,
      input.granularityId,
    );

    const previousForecastId = previousForecast?.id;

    // Publish rolling forecast triggered event
    const triggerEvent = new RollingForecastTriggeredEvent({
      tenantId: context.tenantId,
      correlationId: context.correlationId,
      previousForecastId,
      triggerDate: new Date(),
      periodType: ForecastPeriod.MONTHLY,
      granularity: (input.granularity as ForecastGranularity) || ForecastGranularity.GLOBAL,
      triggeredBy,
      reason,
    });

    await this.eventPublisher.publishRollingForecastTriggered(triggerEvent);

    // Generate new forecast
    const startDate = startOfMonth(new Date());
    const endDate = endOfMonth(addMonths(startDate, DEFAULT_FORECAST_HORIZON_MONTHS - 1));

    const forecastName = previousForecast
      ? `${previousForecast.name} (Rolling ${new Date().toISOString().split('T')[0]})`
      : `Rolling Forecast ${new Date().toISOString().split('T')[0]}`;

    const generateResult = await this.generateForecastUseCase.execute(context, {
      name: forecastName,
      description: `Rolling forecast generated by ${triggeredBy}`,
      model: previousForecast?.model || ForecastModel.WEIGHTED_PIPELINE,
      period: ForecastPeriod.MONTHLY,
      granularity: (input.granularity as ForecastGranularity) || ForecastGranularity.GLOBAL,
      granularityId: input.granularityId,
      currency: previousForecast?.currency || 'USD',
      startDate,
      endDate,
      horizonMonths: DEFAULT_FORECAST_HORIZON_MONTHS,
      confidenceLevel: previousForecast?.confidenceLevel || 85,
    });

    return {
      forecast: generateResult.forecast,
      previousForecastId,
    };
  }
}






