apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: progress-step-service-pdb
  namespace: transaction-orchestration
  labels:
    app: progress-step-service
    team: team-b-transaction
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: progress-step-service
