apiVersion: v1
kind: Secret
metadata:
  name: progress-step-service-secrets
  namespace: transaction-orchestration
  labels:
    app: progress-step-service
    team: team-b-transaction
type: Opaque
stringData:
  database-username: "progress_step_user"
  database-password: "CHANGE_ME_PROD_PASSWORD"
