apiVersion: v1
kind: Service
metadata:
  name: progress-step-service
  namespace: transaction-orchestration
  labels:
    app: progress-step-service
    team: team-b-transaction
spec:
  type: ClusterIP
  selector:
    app: progress-step-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  sessionAffinity: None
