apiVersion: v1
kind: Secret
metadata:
  name: transaction-monitoring-service-secrets
  namespace: transaction-orchestration
  labels:
    app: transaction-monitoring-service
    team: team-b-transaction
type: Opaque
stringData:
  database-username: "transaction_monitoring_user"
  database-password: "CHANGE_ME_PROD_PASSWORD"
