apiVersion: v1
kind: Service
metadata:
  name: transaction-monitoring-service
  namespace: transaction-orchestration
  labels:
    app: transaction-monitoring-service
    team: team-b-transaction
spec:
  type: ClusterIP
  selector:
    app: transaction-monitoring-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  sessionAffinity: None
