spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_inventory
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        inventoryEvents-out-0:
          destination: inventory-events
          content-type: application/json
server:
  port: 8076
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.inventory: DEBUG
