package com.gogidix.hr.benefitsadministration.domain.enums;

public enum BenefitType {
    HEALTH_INSURANCE,
    DENTAL_INSURANCE,
    VISION_INSURANCE,
    LIFE_INSURANCE,
    DISABILITY_INSURANCE,
    RETIREMENT_401K,
    RETIREMENT_PENSION,
    STOCK_OPTIONS,
    GYM_MEMBERSHIP,
    COMMUTER_BENEFITS,
    TUITION_REIMBURSEMENT,
    CHILD_CARE,
    PARENTAL_LEAVE,
    FLEXIBLE_SPENDING_ACCOUNT,
    HEALTH_SAVINGS_ACCOUNT,
    EMPLOYEE_ASSISTANCE_PROGRAM,
    WELLNESS_PROGRAM,
    OTHER
}
