apiVersion: v1
kind: Secret
metadata:
  name: supply-chain-optimization-service-secrets
  namespace: ai-services
  labels:
    app: supply-chain-optimization-service
    team: team-f-ai-services
type: Opaque
stringData:
  mongodb-user: "supply-chain-optimization-service_user"
  mongodb-password: "CHANGE_ME_PROD_PASSWORD"
  redis-password: ""
