spring:
  application:
    name: pricing-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_pricing
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        pricingEvents-out-0:
          destination: pricing-events
          content-type: application/json

server:
  port: 8066

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gogidix.ecommerce.pricing: DEBUG
