apiVersion: v1
kind: Service
metadata:
  name: inventory-core-service
  namespace: warehousing-core
  labels:
    app: inventory-core-service
    service: inventory-core-service
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    port: 8210
    targetPort: http
    protocol: TCP
  - name: management
    port: 8211
    targetPort: management
    protocol: TCP
  selector:
    app: inventory-core-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-core-service-headless
  namespace: warehousing-core
  labels:
    app: inventory-core-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8210
    targetPort: http
    protocol: TCP
  selector:
    app: inventory-core-service
