spring:
  application:
    name: payment-method-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_paymentmethod
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        paymentmethodEvents-out-0:
          destination: paymentmethod-events
          content-type: application/json
server:
  port: 8087
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.gogidix.ecommerce.paymentmethod: DEBUG
