apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-model-management-service-pdb
  namespace: ai-services
  labels:
    app: ai-model-management-service
    team: team-ai-mlops
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ai-model-management-service
