spring:
  application:
    name: rate-limiting-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: gogidix_rate_limit
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

server:
  port: 8086

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.gogidix: DEBUG
